### PR TITLE
Introduce IntrospectionBeanPropertyBinder as alternative to JacksonBeanPropertyBinder

### PR DESCRIPTION
**Pull request by dstepanov**
I had another look at properties binding, PR based on https://github.com/micronaut-projects/micronaut-core/pull/3859
Moved all the keys processing to `JacksonBeanPropertyBinder` with some refactoring.

Probably not for a minor release.

### CODE REVIEW

**Comment by graemerocher** [comment]
Will need to be rebased. Scheduled to look at it for 2.1

**Comment by dstepanov** [comment]
@graemerocher Rebased, `buildSourceMapNode` is producing a `Map` of `Map,List,String,Number,Boolean` so new introspected impl. can be added.

**Comment by dstepanov** [comment]
@graemerocher My take to add alternative `BeanPropertyBinder` using `BeanIntrospection`.
There are a lot of cases when `ConfigurationProperties`'s beans need to be introspected also some HTTP tests fail for the same reason, it looks like there are some Map->Object conversions inside of HTTP processing.

**Comment by graemerocher** [comment]
@dstepanov nice work, could you target 2.1.x branch? Think we can start off having this disabled and gradually deprecate the jackson one in 3.0

**Comment by dstepanov** [comment]
@graemerocher There are still tests failing because of missing `@Intercepted` do you want to fix them and enable `IntrospectionBeanPropertyBinder` by default?

**Comment by graemerocher** [comment]
We can't enable it by default in 2.x as that would be a breaking change, but we could potentially enable it for newly created apps

**Comment by dstepanov** [comment]
I think `BeanPropertyBinderRegistrar` should throw exception in some of conversion errors.

**Pull request closed without merging**
