### PR TITLE
Metrics datasource

### PR DESCRIPTION
**Pull request by ctoestreich**
This is the work for datasource metrics.  This is specific to connection and pool metrics.  The database table metrics belong into another story.  

Things to note during review:

Hikari uses the built in MeterRegistry setter method that they have added to support.  They support micrometer and drop wizard: https://github.com/brettwooldridge/HikariCP/blob/471e27ece03fc99eb848e96291352648465c6c08/src/main/java/com/zaxxer/hikari/pool/HikariPool.java#L281

Tomcat and DBCP borrow on the method that spring boot uses in actuator auto config to wire up some common set of pool properties.

See the metricsEndpoint.adoc or tests for differences in the metric names.  I do have a commit in this chain where the hikari is bound in the same way as tomcat and dbcp if a commonly named metric is preferred to the additional metrics provided with hikari.  See #391 for more comments on this.

### CODE REVIEW

**Comment by ctoestreich** [comment]
There is an issue with optionally required deps.  Fixing then will reopen.

**Comment by ctoestreich** [comment]
@graemerocher Before I submit this PR please also review https://github.com/micronaut-projects/micronaut-core/compare/master...tardisoft:metrics-datasource-metadata?expand=1

I am not super happy about the compileOnly metrics in the jdbc-hikari project that catches the NoClassDefFoundError for people that DON'T include metrics but I don't see another way to have an "Optional" runtime dep.

I also created a branch uses the same `jdbc.connections.xxxx` names but uses a new interface https://github.com/tardisoft/micronaut-core/blob/f21089fb4607bf3b60fb00078a498a18d24e62af/jdbc/src/main/java/io/micronaut/jdbc/metadata/VerboseDataSourcePoolMetadata.java to provide some additional metrics from hikari that are accessible.  When I was reviewing their code they do the following, which we just can't do given that the timings are tracked internally.  Snippet from https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java

```java
MicrometerMetricsTracker(final String poolName, final PoolStats poolStats, final MeterRegistry meterRegistry)
   {
      this.poolStats = poolStats;

      this.connectionObtainTimer = Timer.builder(METRIC_NAME_WAIT)
         .description("Connection acquire time")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.connectionCreation = Timer.builder(METRIC_NAME_CONNECT)
         .description("Connection creation time")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.connectionUsage = Timer.builder(METRIC_NAME_USAGE)
         .description("Connection usage time")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.connectionTimeoutCounter = Counter.builder(METRIC_NAME_TIMEOUT_RATE)
         .description("Connection timeout total count")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.totalConnectionGauge = Gauge.builder(METRIC_NAME_TOTAL_CONNECTIONS, poolStats, PoolStats::getTotalConnections)
         .description("Total connections")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.idleConnectionGauge = Gauge.builder(METRIC_NAME_IDLE_CONNECTIONS, poolStats, PoolStats::getIdleConnections)
         .description("Idle connections")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.activeConnectionGauge = Gauge.builder(METRIC_NAME_ACTIVE_CONNECTIONS, poolStats, PoolStats::getActiveConnections)
         .description("Active connections")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.pendingConnectionGauge = Gauge.builder(METRIC_NAME_PENDING_CONNECTIONS, poolStats, PoolStats::getPendingThreads)
         .description("Pending threads")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.maxConnectionGauge = Gauge.builder(METRIC_NAME_MAX_CONNECTIONS, poolStats, PoolStats::getMaxConnections)
         .description("Max connections")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

      this.minConnectionGauge = Gauge.builder(METRIC_NAME_MIN_CONNECTIONS, poolStats, PoolStats::getMinConnections)
         .description("Min connections")
         .tags(METRIC_CATEGORY, poolName)
         .register(meterRegistry);

   }
```

Here is the effective difference of these two.  https://github.com/tardisoft/micronaut-core/compare/metrics-datasource...tardisoft:metrics-datasource-metadata?expand=1

**Comment by ctoestreich** [comment]
Opening up now that this branch is fixed.  Just need to decide if this or the other branch...

**Comment by graemerocher** [comment]
I don't understand the need to include a dependency on `spring-jdbc` and `DelegatingDataSource` in this change

**Comment by ctoestreich** [comment]
It was added for testing as the DataSourse is spring proxy and doesn't correctly coerce to type HikariDataSource.  When I ran application with @Transactional support, the metric binding doesn't work unless is checks for wrapped DataSourse aka the delegating data source.  When I get to my computer I will add some more details.

**Comment by ctoestreich** [comment]
do not merge, found issue that I am fixing with tomcat pool

**Comment by ctoestreich** [comment]
@graemerocher here is more details about the datasource when you include `runtime "org.springframework:spring-jdbc"` as I iterate the datasource to create the pool meta data.  Without checking for the delegating data source we can't effectively get the raw datasource to get the pool and metrics.

screen shot 2018-08-07 at 9 52 06 am

**Comment by ctoestreich** [comment]
Realized I have another option maybe.

```java
 @EachBean(org.apache.tomcat.jdbc.pool.DataSource.class)
    @Requires(beans = {DatasourceConfiguration.class})
    public TomcatDataSourcePoolMetadata tomcatPoolDataSourceMetadataProvider(
            @Parameter String dataSourceName,
            org.apache.tomcat.jdbc.pool.DataSource dataSource) {
        return new TomcatDataSourcePoolMetadata(dataSource);
    }
```

trying now

**Comment by ctoestreich** [comment]
The other option is to create the singleton inline like this perhaps

```java
 private final ApplicationContext applicationContext;

    public DatasourceFactory(ApplicationContext applicationContext) {
        this.applicationContext = applicationContext;
    }
    
    /**
     * @param datasourceConfiguration A {@link DatasourceConfiguration}
     * @return An Apache Tomcat {@link DataSource}
     */
    @EachBean(DatasourceConfiguration.class)
    public DataSource dataSource(DatasourceConfiguration datasourceConfiguration) {
        org.apache.tomcat.jdbc.pool.DataSource ds = new org.apache.tomcat.jdbc.pool.DataSource(datasourceConfiguration);
        dataSources.add(ds);
        applicationContext.registerSingleton(TomcatDataSourcePoolMetadata.class, new TomcatDataSourcePoolMetadata(ds), Qualifiers.byName(datasourceConfiguration.getName()));
        return ds;
    }
```

**Comment by ctoestreich** [comment]
I also tried adding a `BeanCreatedEventListener<DataSourcePoolMetadata>` but the method `applicationContext.registerSingleton(TomcatDataSourcePoolMetadata.class, new TomcatDataSourcePoolMetadata(ds), Qualifiers.byName(datasourceConfiguration.getName()));` does not fire `BeanCreatedEvent`...

I am out of options for how to remove the check for the spring proxy.

**Comment by ctoestreich** [comment]
@graemerocher I removed the compileOnly dependency.  I am a big unclear how your suggestion gets around having the types available on the path.  The best solution i could devise was to check if the datasources super class has the targetDataSource field and then get that as the datasource if so.  Let me know if this is not an acceptable approach.

I have been stuck in maven-land for a long time and I am not sure which gradle target would get around having the spring-jdbc as "optional".  I wanted to keep it out of the runtime if possible because having it would essentially proxy all datasources unnecessarily.

**Comment by ctoestreich** [comment]
The alternative is to keep the `compileOnly` in the same way the `:spring` module defines it and use something like this...


```java
package io.micronaut.configuration.jdbc.tomcat;

import io.micronaut.configuration.jdbc.tomcat.metadata.TomcatDataSourcePoolMetadata;
import io.micronaut.context.annotation.EachBean;
import io.micronaut.context.annotation.Factory;
import io.micronaut.context.annotation.Parameter;
import io.micronaut.context.annotation.Requires;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DelegatingDataSource;

import javax.sql.DataSource;

@Factory
public class DataSourcePoolMetadataFactory {

    /**
     * Method to create a metadata object that allows pool value lookup for each datasource object.
     *
     * @param dataSourceName The name of the datasource
     * @param dataSource     The datasource
     * @return a {@link TomcatDataSourcePoolMetadata}
     */
    @EachBean(DataSource.class)
    @Requires(beans = {DatasourceConfiguration.class, DataSourceTransactionManager.class})
    public TomcatDataSourcePoolMetadata tomcatPoolDataSourceMetadataDelegatingProvider(
            @Parameter String dataSourceName,
            DataSource dataSource) {
        return new TomcatDataSourcePoolMetadata((org.apache.tomcat.jdbc.pool.DataSource) ((DelegatingDataSource) dataSource).getTargetDataSource());
    }

    @EachBean(DataSource.class)
    @Requires(beans = {DatasourceConfiguration.class})
    @Requires(missingBeans = {DataSourceTransactionManager.class})
    public TomcatDataSourcePoolMetadata tomcatPoolDataSourceMetadataProvider(
            @Parameter String dataSourceName,
            DataSource dataSource) {
        return new TomcatDataSourcePoolMetadata((org.apache.tomcat.jdbc.pool.DataSource) dataSource);
    }
}
```

**Comment by graemerocher** [comment]
On vacation atm will look when I get back

**Comment by graemerocher** [comment]
@ctoestreich I have pushed to a branch this commit https://github.com/micronaut-projects/micronaut-core/commit/cdfd07d1e3f65d82ba3029a91eb67da9b7ed0290

This avoids using reflection. If you incorporate that change then I think this will probably be ready to merge. Although `DatasourceTransactionManagementSpec` fails locally for me both with and without my changes.

**Comment by ctoestreich** [comment]
@graemerocher working on it now

**Comment by ctoestreich** [comment]
I fixed the test.  I am not sure if this uncovered a bug or a feature that I am not familiar with.

The test config looks like

```java
       given:
        ApplicationContext ctx = ApplicationContext.run(
                'datasources.default': ['defaultAutoCommit': false, 'enableAutoCommitOnReturn': false],
                'datasources.secondary': ['defaultAutoCommit': false, 'enableAutoCommitOnReturn': false]
        )
```

The fix was to add the `@Named('default')` to the service data source.

When using 

```java
private final DataSource dataSource;
    private final DataSource secondary;

    public BookService(DataSource dataSource, @Named("secondary") DataSource secondary) throws SQLException {
        this.dataSource = dataSource;
        this.secondary = secondary;
...
```

This was causing the injector for the unnamed `DataSource dataSource` to create ANOTHER "default" datasource.  Then there would be 3 datasources instead of two.

screen shot 2018-08-30 at 3 04 13 pm

Adding `public BookService(@Named("default") DataSource dataSource, @Named("secondary") DataSource secondary) throws SQLException {` fixes this issue.

It seems like it isn't treating null and "default" for datasources when not providing a qualifier on the injection.  I feel like this is a special case with datasources so I am not sure how you want to solve.

It also seems like the bean creation is happening in a later phase than the normal wiring as this is called three (x3) times. 

```java
@EachBean(DatasourceConfiguration.class)
    public DataSource dataSource(DatasourceConfiguration datasourceConfiguration) {
        org.apache.tomcat.jdbc.pool.DataSource ds = new org.apache.tomcat.jdbc.pool.DataSource(datasourceConfiguration);
        dataSources.add(ds);
        return ds;
    }
```

however this is only called twice (x2), which I don't fully grok. 

```java
/**
     * Method to create a metadata object that allows pool value lookup for each datasource object.
     *
     * @param dataSource     The datasource
     * @return a {@link TomcatDataSourcePoolMetadata}
     */
    @EachBean(DataSource.class)
    @Requires(beans = {DatasourceConfiguration.class})
    public TomcatDataSourcePoolMetadata tomcatPoolDataSourceMetadataProvider(
            DataSource dataSource) {

        TomcatDataSourcePoolMetadata dataSourcePoolMetadata = null;

        DataSource resolved = dataSourceResolver.resolve(dataSource);

        if (resolved instanceof org.apache.tomcat.jdbc.pool.DataSource) {
            dataSourcePoolMetadata = new TomcatDataSourcePoolMetadata((org.apache.tomcat.jdbc.pool.DataSource) resolved);
        }
        return dataSourcePoolMetadata;
    }

```

Seems like creating the new datasource replaces the previously created one due to replacing the map entry is my best guess.

screen shot 2018-08-30 at 3 32 20 pm

Let me know if this is expected.

**Comment by ctoestreich** [comment]
I have confirmed that this NOT happening in the dbcp and hikari projects.  It seems to be something about the tomcat only.  😖

**Comment by ctoestreich** [comment]
@graemerocher I think this is finally ready to go.

**Pull request merged**
