### PR TITLE
Documentation updates for 2.2

### PR DESCRIPTION
**Pull request by graemerocher**
@ilopmar @alvarosanchez this branch needs updating for the Micronaut Maven plugin when it is integrated and this needs to be merged before 2.2 is out

### CODE REVIEW

**Comment by graemerocher** [comment]
@alvarosanchez any progress on this?

**Comment by alvarosanchez** [comment]
> @alvarosanchez any progress on this?

Not yet. It's on my list.

**Comment by graemerocher** [comment]
@alvarosanchez if you could also update https://github.com/micronaut-projects/micronaut-core/pull/4477

Thanks

**Comment by alvarosanchez** [comment]
@graemerocher done both

**Pull request merged**
