### PR TITLE
Prepare for Jakarta validation

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Comment by graemerocher** [comment]
Breaks tests?

**Comment by dstepanov** [comment]
Need to investigate

**Comment by nbrugger-tgm** [comment]
Contributed towards https://github.com/micronaut-projects/micronaut-core/issues/4770

**Comment by dstepanov** [comment]
Yes, work in progress to switch to Jakarta

**Pull request merged**
