### PR TITLE
ci: GraalVM workflow remove dev

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Is this only for 3.5? Or will you merge up?

**Comment by sdelamo** [comment]
> Is this only for 3.5? Or will you merge up?

I will merge up

**Comment by alvarosanchez** [comment]
I don't think we should merge this up. We're trying a permanent solution [here](https://github.com/micronaut-projects/micronaut-project-template/pull/318)

**Review by alvarosanchez — APPROVED** [review]
Note that now you already have this change in #8597, so no need to merge up all the way through 4.0.x

**Comment by sdelamo** [comment]
@alvarosanchez I am not sure the GraalVM builds got executed?. above it shows only the Test report

**Comment by alvarosanchez** [comment]
I think you made a mistake in the indentation.

In #8597 it generated the correct set of jobs:

image

**Comment by sdelamo** [comment]
Close via https://github.com/micronaut-projects/micronaut-core/pull/8671

**Pull request closed without merging**
