### PR TITLE
Replace deprecated output method for Github actions

### LINKED ISSUE #8720: remove deprecated set-output and save-state
see: https://github.com/micronaut-projects/micronaut-project-template/pull/324

and https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### PR DESCRIPTION
**Pull request by timyates**
Closes #8720

### CODE REVIEW

**Comment by graemerocher** [comment]
should this not go in the template? Also thought we were removing/deprecating the release notes workflow

**Comment by alvarosanchez** [comment]
I guess he's testing https://github.com/micronaut-projects/micronaut-project-template/pull/326 ?

And yes, release notes workflow can be removed, BUT then we will have to draft new releases manually, providing tag, target and title.

**Comment by timyates** [comment]
This was raised by @sdelamo here https://github.com/micronaut-projects/micronaut-core/issues/8720

Does the template update old branches?  This is for 3.8.x

**Comment by graemerocher** [comment]
> I guess he's testing [micronaut-projects/micronaut-project-template#326](https://github.com/micronaut-projects/micronaut-project-template/pull/326) ?
> 
> And yes, release notes workflow can be removed, BUT then we will have to draft new releases manually, providing tag, target and title.

This is pretty simple with github automatic generation. It generates the title and description for you, you just have to enter the tag and we don't have a bunch of drafts hanging around.

**Comment by sdelamo** [comment]
> And yes, release notes workflow can be removed, BUT then we will have to draft new releases manually, providing tag, target and title.

I think we should remove it. Providing tag, target and title we can do it manually.

**Comment by sdelamo** [comment]
> > And yes, release notes workflow can be removed, BUT then we will have to draft new releases manually, providing tag, target and title.
> 
> I think we should remove it. Providing tag, target and title we can do it manually.

To do this would be as easy as removing `.github/workflows/release-notes.yml`?

**Comment by alvarosanchez** [comment]
> To do this would be as easy as removing .github/workflows/release-notes.yml?

Removing it from here or from the project template won't propagate across the repos. The trick we have done in the past is to include a `rm` statement to get it removed:

https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/files-sync.yml#L101-L104C63

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
> > To do this would be as easy as removing .github/workflows/release-notes.yml?
> 
> Removing it from here or from the project template won't propagate across the repos. The trick we have done in the past is to include a `rm` statement to get it removed:
> 
> https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/files-sync.yml#L101-L104C63

Thanks @alvarosanchez 
I have created a separate issue to remove the workflow. https://github.com/micronaut-projects/micronaut-project-template/issues/328

can you review this PR?

**Review by alvarosanchez — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
