### PR TITLE
Disable Cloud environment deduction by default. Fixes #7758

### LINKED ISSUE #7758: Disable environment deduction by default in Micronaut 4.0
### Issue description

Micronaut currently by default attempts to deduce the cloud environment it is running, whilst convenient this is comes at a performance cost and also is potentially not secure since the logic to deduce the environment has to probe remote endpoints.

This functionality should be disabled by default and enabled on a case by case basis by the developer.

### PR DESCRIPTION
**Pull request by graemerocher**
* Introduces a new method ` deduceCloudEnvironment` to `ApplicationContextBuilder` that allows re-enabling of this functionality
* Retains environment deduction only for the test environment

### CODE REVIEW

**Comment by dstepanov** [comment]
Maybe we can have the env detectors being contributed by the cloud support modules, so aws, azure, oracle cloud will contribute own detectors but the pure core will not have it?

**Review by sdelamo — CHANGES_REQUESTED** [review]
This PR should update as well: 

https://docs.micronaut.io/snapshot/guide/#environments

It currently talks about environment deduction being on and how to disable it. We should update to tell the oposite. 

moreover, in addition to the mention in breaks we need a section in the documentation talking specifically about cloud environment deduction.

**Comment by sdelamo** [comment]
> Maybe we can have the env detectors being contributed by the cloud support modules, so aws, azure, oracle cloud will contribute own detectors but the pure core will not have it?

In think we could do that in addition to this PR. We should move that into a separate issue.

**Comment by graemerocher** [comment]
> Maybe we can have the env detectors being contributed by the cloud support modules, so aws, azure, oracle cloud will contribute own detectors but the pure core will not have it?

good idea

**Review by dstepanov — APPROVED** [review]

**Comment by sdelamo** [comment]
> This PR should update as well:
> 
> https://docs.micronaut.io/snapshot/guide/#environments
> 
> It currently talks about environment deduction being on and how to disable it. We should update to tell the oposite.
> 
> moreover, in addition to the mention in breaks we need a section in the documentation talking specifically about cloud environment deduction.

@graemerocher can you do this doc update?

**Comment by graemerocher** [comment]
> > This PR should update as well:
> > https://docs.micronaut.io/snapshot/guide/#environments
> > It currently talks about environment deduction being on and how to disable it. We should update to tell the oposite.
> > moreover, in addition to the mention in breaks we need a section in the documentation talking specifically about cloud environment deduction.
> 
> @graemerocher can you do this doc update?

@sdelamo I have added additional docs. There is already a section in the documentation that talks about cloud environment deduction. I have updated this section.

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
