### PR TITLE
Bump micronaut-liquibase to 2.0.0.M1

### PR DESCRIPTION
**Pull request by micronaut-build**

### CODE REVIEW

**Comment by graemerocher** [comment]
@ilopmar group ID needs updating before this can be merged

**Comment by ilopmar** [comment]
Updated in this same branch

**Comment by graemerocher** [comment]
Thanks. Will need a PR to starter as well...

**Comment by ilopmar** [comment]
https://github.com/micronaut-projects/micronaut-starter/pull/267

**Pull request merged**
