### PR TITLE
Fixes null body inconsistency inside HttpRequest

### PR DESCRIPTION
**Pull request by utsav0209**
Fixes issue #5195

### CODE REVIEW

**Comment by jameskleeh** [comment]
This needs tests

**Comment by jameskleeh** [comment]
@utsav0209 Are you interested in taking this forward?

**Comment by utsav0209** [comment]
@jameskleeh sorry for the delay, I will get it done over the weekend.

**Comment by jameskleeh** [comment]
Please remove the new methods. That would technically be a new feature or improvement and can cause incompatibility between patch versions.

**Comment by jameskleeh** [comment]
Thanks for your contribution!

**Pull request merged**
