### PR TITLE
Trim element collection in env property

### PR DESCRIPTION
**Pull request by eutkin**
Issue #5615

### CODE REVIEW

**Comment by jameskleeh** [comment]
As I said in the issue I'm not sure we can assume this is the desired behavior. It is easily avoided by simply not putting spaces in the config. This is also not backwards compatible

**Comment by jeffscottbrown** [comment]
I see that this has been moved from `2.5.x` to `3.0.x`.  If this is brought into 3.0, will there still be a way to express leading and trailing whitespace in a config value?

**Comment by eutkin** [comment]
> I see that this has been moved from `2.5.x` to `3.0.x`. If this is brought into 3.0, will there still be a way to express leading and trailing whitespace in a config value?

only:

```yml
property:
  - 'one'
  - ' two'
 ```

**Comment by jeffscottbrown** [comment]
@eutkin I see.  I didn't run it but from looking at the PR it looked like that probably wouldn't work.  Sorry for the noise.

**Pull request closed without merging**
