### PR TITLE
Oracle updates

### PR DESCRIPTION
**Pull request by aalmiray**

### CODE REVIEW

**Review by sdelamo — APPROVED** [review]

**Comment by ilopmar** [comment]
This is a breaking change and, at least should be documented as such. Any application using the old coordinates would fail, like the GraalVM tests just failed: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/695117552#L56

**Comment by graemerocher** [comment]
@ilopmar in that case we would need to maintain in the BOM the old coordinates and point to the older version of the driver

**Comment by graemerocher** [comment]
ie version `19.3.0.0`

**Comment by ilopmar** [comment]
I think we should definitely do that, specially for a patch release. We did that when the GraalVM team modified the coordinates, updated to the new one but keep the old for compatibility (until 2.0 that we removed it)

I'll submit a PR with the old version.

**Comment by aalmiray** [comment]
Would it be possible to keep both old and new coordinates in the BOM?

**Comment by ilopmar** [comment]
@aalmiray https://github.com/micronaut-projects/micronaut-core/pull/3934

**Pull request merged**
