### PR TITLE
Add tracing where MDCSpecs randomly fail

### PR DESCRIPTION
**Pull request by lgathy**
@graemerocher I could not reproduce [this failure](https://github.com/micronaut-projects/micronaut-core/runs/699190252?check_suite_focus=true#step:7:1462), but analysing the logs how it failed I added some extra tracing to better see what might have gone wrong when the trace_id is not found. I am only creating this PR as a draft hoping that build will still be triggered. Since it surfaces randomly we might need to trigger the build multiple times, is that possible?

### CODE REVIEW

**Comment by lgathy** [comment]
Relates to reverted PR #3298

**Comment by graemerocher** [comment]
I think you can only restart builds that fail. Only a change can trigger another build I think, so you may need to add a comment or something

**Comment by graemerocher** [comment]
Actually no I can restart them.. I restarted again

**Comment by graemerocher** [comment]
Actually it looks like it may be unrelated to the PR, since it just failed again with  https://github.com/micronaut-projects/micronaut-core/pull/3323/checks?check_run_id=699694930#step:7:1341

Looks like we need to investigate why that is happening

**Comment by lgathy** [comment]
It may help then to merge this PR as it will provide further detail when this fails again as the call stack of the failing thread will be logged.

**Comment by graemerocher** [comment]
Looks like the trace ID is missing when it fails https://github.com/micronaut-projects/micronaut-core/runs/700013955?check_suite_focus=true#step:7:1482

So potentially there is still some thread safety issues with the current solution. @dstepanov Any idea why the impl could sometimes fail under load?

**Comment by lgathy** [comment]
It always seems to be the very first invocation failing, which could indicate spinning up a new thread has something to do with it. Stack traces are identical to when it does not fail, Logs show that `MDC.put` has been successfully executed. If MDC adapter is not different, it leaves only one possibilty: `MDC.remove()` or `MDC.clear()` gets executed between the filter and the controller, I will try to find a way to track that, it could be MdcInstrumenter, since that part changed recently. Btw, filter and controller seem to get executed on the same thread.

@graemerocher I will add more tracing and submit it in a new PR. I was still not able to reproduce this locally no matter what I tried, so I see no alternatives atm.

**Comment by graemerocher** [comment]
So yeah currently in Micronaut 2.x we don’t do thread branching and leave that up to the user to manage with scheduleOn etc

**Pull request merged**
