### PR TITLE
change missed Java 11 ref in github workflow files

### PR DESCRIPTION
**Pull request by wetted**

### CODE REVIEW

**Review by timyates — CHANGES_REQUESTED** [review]
That's not a version number, that's removing the first 11 chars from GITHUB_REF

**Comment by altro3** [comment]
@timyates Not sure you are right. Look to micronaut tracing commit by @sdelamo :

изображение

Or, maybe it is mistake took and need to revert 11 in this place

**Comment by timyates** [comment]
I believe that's a mistake

**Comment by timyates** [comment]
As an explanation, bash and zsh allow the following 3 forms of variable expansion (there are more, but this change is one of these)

```
# just the variable
echo ${VAR}
# variable with offset
echo ${VAR:3}
# variable with offset and length
echo ${VAR:3:2}
```

So, if VAR was set to "micronaut" then the above would print

```
micronaut
ronaut
ro
```

I believe the line that changed here strips the first 11 chars off GITHUB_REF, which just leaves you with the branch name

**Pull request closed without merging**
