### PR TITLE
build:  bump native-maven-plugin to 0.9.19

### PR DESCRIPTION
**Pull request by sdelamo**
see: https://github.com/graalvm/native-build-tools/releases/tag/0.9.19

### CODE REVIEW

**Comment by alvarosanchez** [comment]
@melix despite #8399 this is still not being picked up by Renovate. I checked the [Dependency Dashboard](https://github.com/micronaut-projects/micronaut-core/issues/7293) but it's not rate-limited.

I noticed #8370, but that's something else.

**Comment by melix** [comment]
@alvarosanchez it is the same thing: our `libs.versions.toml` only contains a _version_ for the plugin. There are no GAV coordinates associated with it, so there's no way renovate can figure out it has to upgrade it. If we want automatic upgrade we must add a dummy entry in the `[libraries]` section with the coordinates of that library.

**Comment by alvarosanchez** [comment]
I did add an entry: https://github.com/micronaut-projects/micronaut-core/pull/8399/files

**Comment by melix** [comment]
Right, but it's not on the main branch yet: https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/gradle/libs.versions.toml

**Comment by alvarosanchez** [comment]
Aaaaaah ok, I keep forgetting that 4.0.x is the default branch.

Then we are (will be?) good to go.

**Review by alvarosanchez — APPROVED** [review]

**Pull request merged**
