### PR TITLE
Support for customizing the management port. Fixes #948

### LINKED ISSUE #948: Dedicated management port
Like `spring boot 2`, it would be nice to have a dedicated management port.  K8 and service mesh providers dictate this as a good practice.

```
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.server.port=7999

``` 
This feature request is follow up of this https://github.com/micronaut-projects/micronaut-core/issues/538

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.1
- **JDK Version:** JDK8

### PR DESCRIPTION
**Pull request by graemerocher**
This resolves #948 by adding a condition to each `@Endpoint` route and exposing an additional port.

### CODE REVIEW

**Comment by dave08** [comment]
Would it be possible to add some kind of `@Port` annotation for controllers too? It would be extremely useful for internal api... @graemerocher

**Comment by graemerocher** [comment]
@dave08 yes it would be possible, the implementation allows that. We will see what we can do.

**Comment by jameskleeh** [comment]
@dave08 I would suggest creating a new issue to add support for that

**Comment by sollecitom** [comment]
Good work, even if it'd be nice to have the management port logged alongside the main one on startup.

**Comment by graemerocher** [comment]
@sollecitom maybe report another issue with an improvement request

**Pull request merged**
