### PR TITLE
Remove GraalVM resource generation for Graal visitor

### LINKED ISSUE #5556: Remove generation of GraalVM resource-config.json from GraalTypeElementVisitor
The `GraalTypeElementVisitor` shouldn't create the GraalVM `resource-config.json` with all the static resources. That should be done in the Gradle/Maven plugins.

There are pending PRs for the plugins and this PR shouldn't be merged until those are merged and released:

- Gradle: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/215
- Maven: https://github.com/micronaut-projects/micronaut-maven-plugin/pull/184

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #5556

This PR shouldn't be merged until the following PRs are merged and plugins released:

- Gradle: https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/215
- Maven: https://github.com/micronaut-projects/micronaut-maven-plugin/pull/184

### CODE REVIEW

**Comment by graemerocher** [comment]
I think we need to alter the visitor as well to only process `ReflectiveAccess` and `TypeHint`

This may require splitting it into 2 visitors

**Comment by graemerocher** [comment]
Actually it probably won't. You just have to override `getSupportedAnnotationNames()` so it can remain a single aggregating visitor

**Comment by ilopmar** [comment]
I'm doing that in a separate issue because I think they are different things. Both changes modify the visitor but they can be done independently. See #5557

**Comment by graemerocher** [comment]
Oops realised shouldn't have merged 🤦‍♂️

**Comment by graemerocher** [comment]
Sorry restored as https://github.com/micronaut-projects/micronaut-core/pull/5567

**Pull request merged**
