### PR TITLE
Fix incorrect PropertySourcePropertyResolver.getAllProperties behaviour when StringConvention.RAW

### LINKED ISSUE #8117: `StringConvention.RAW` not working when used in `PropertySourcePropertyResolver.getAllProperties`
### Expected Behavior

When `StringConvention.RAW`  is passed to `PropertySourcePropertyResolver#getAllProperties` then property keys must not be changed.

### Actual Behaviour

When `StringConvention.RAW` is passed to `PropertySourcePropertyResolver#getAllProperties` method then all keys are hyphenated. 
For example key `CamelCase.property` is translated into `camel-case.property`. 

### Steps To Reproduce

Execute following code:
```
public class Main {
    public static void main(String[] args) {
        Map<String, Object> source = Map.of("camelCase.property", "theValue");
        PropertySourcePropertyResolver resolver = new PropertySourcePropertyResolver(PropertySource.of(source));
        Map<String, Object> target = resolver.getAllProperties(StringConvention.RAW, MapTransformation.FLAT);

        System.out.println("Actual  : " + target);
        System.out.println("Expected: " + source);
    }
}
```

Output will be:
```
Actual  : {camel-case.property=theValue}
Expected: {camelCase.property=theValue}
```

### Environment Information

- Ubuntu 22.04.1 LTS
- openjdk version "17.0.4" 2022-07-19 LTS

### Example Application

https://github.com/hurynovich/example1/blob/main/src/main/java/org/example/Main.java

### Version

3.7.1

### PR DESCRIPTION
**Pull request by hurynovich**
This pull request fixes https://github.com/micronaut-projects/micronaut-core/issues/8117 issue.

### CODE REVIEW

**Comment by graemerocher** [comment]
thanks, could you sign the CLA?

**Comment by hurynovich** [comment]
CLA is signed.

**Review by graemerocher — APPROVED** [review]

**Comment by sdelamo** [comment]
I have backported this to 3.7.x https://github.com/micronaut-projects/micronaut-core/pull/8178

**Comment by sdelamo** [comment]
I have backported this to 3.7.x https://github.com/micronaut-projects/micronaut-core/pull/8178

**Pull request closed without merging**
