### PR TITLE
#639 Ability to specify and merge additional Swagger files

### PR DESCRIPTION
**Pull request by puneetbehl**
* System property `micronaut.openapi.additional.files` to read additional Swagger YAML files from disk.
* Updated OpenApiApplicationVisitor to parse and merge additional swagger files into the application `OpenAPI` object.

### CODE REVIEW

**Comment by puneetbehl** [comment]
The only confusion which might occur is that:

When the actual file path is: 
```{project.home}/src/main/resources/swagger```

Then, user may set the `SystemProperty` as: 
```
String additionalSwaggerDir = new File(getClass().getResource("/swagger").toURI()).parent
System.setProperty(OpenApiApplicationVisitor.MICRONAUT_OPENAPI_ADDITIONAL_FILES, additionalSwaggerFilesDir)
```

The above will not work as that would refer to the `build` directory the directory but files doesn't exists in `build`. That's the reason we defined `SystemProperty` in the first place. As, I wasn't able to generate a path relative to `project.home` from `OpenApiApplicationVisitor`.

**Comment by graemerocher** [comment]
Ok, we may want to do a simple check to see if `src/main/swagger.yml` exists are some agreed upon path. Other than that this will probably need to go into the new openapi repo as it is too late for large changes like this in 1.1

**Comment by sdelamo** [comment]
We should include documentation for this as well.

**Comment by puneetbehl** [comment]
I was thinking that we could have multiple additional Swagger YAML files instead of one single. Also, I am not sure if it's possible but we could generate some default YAML for `security`, `security-jwt` and `management` modules in the documentation which would be updated automatically as we make changes in the respective modules and users can use as reference. 

So, we might have multiple files depending on the modules in `src/main/swagger` location which would be merge in the final OpenAPI object.

**Comment by puneetbehl** [comment]
@graemerocher I will update the open-api repo and then the PR on same after we release 1.1.0 as currently we decided to hold it.

**Comment by puneetbehl** [comment]
These changes have been merged in https://github.com/micronaut-projects/micronaut-openapi/commit/9f051a9053cacd11afac78bb7f66e59b7aa28716

**Pull request closed without merging**
