### PR TITLE
Disable checkstyle check for empty line after license (before package)

### PR DESCRIPTION
**Pull request by ilopmar**
This is related to #188

### CODE REVIEW

**Comment by graemerocher** [comment]
I'm not sure this is even desirable. It seems a good thing to have a space after the license and before the package.

**Comment by ilopmar** [comment]
Ok, then we need to do it manually because the license plugin doesn't support it yet: https://github.com/hierynomus/license-gradle-plugin/issues/61

Feel free to close and reject this PR.

**Comment by graemerocher** [comment]
Oh I see. I didn't understand that part. Will leave it up to @jeffbrown to decide

**Comment by jeffbrown** [comment]
I don't care about a blank line after the license statement.  We need to stop spending time on style issues that don't affect code quality, maintainability or are otherwise valuable.  If we have inconsistency in the code base with respect to whether or not there is a blank line after the license, that doesn't trouble me at all.

**Comment by jeffbrown** [comment]
@ilopmar Does the change in this PR make the system not complain about the blank line?  If yes, then we probably should apply it.  I closed it and then realized that probably was a mistake.

**Comment by ilopmar** [comment]
@jeffbrown Exactly. With this change checkstyle won't complain about the blank line after the header.

**Pull request closed without merging**
