### PR TITLE
Fixed compile scope

### PR DESCRIPTION
**Pull request by pditommaso**

### CODE REVIEW

**Comment by jameskleeh** [comment]
@pditommaso The documentation is correct. The `inject-groovy` only needs to be in `compileOnly`. If that is done then `inject` should be `compile`.

**Comment by pditommaso** [comment]
But would the `compile "io.micronaut:micronaut-inject:1.1.2"` still required, then?

**Comment by jameskleeh** [comment]
@pditommaso You could either:


Best practice:
```
compileOnly "io.micronaut:micronaut-inject-groovy"
compile "io.micronaut:micronaut-inject"
```

Still works:
```
compile "io.micronaut:micronaut-inject-groovy"
```

**Comment by jameskleeh** [comment]
The second option is not as good because it results in a dependency on your runtime classpath that adds no value at runtime

**Comment by pditommaso** [comment]
Ok, now I'm understanding. Reading the docs it seems to suggest you need to replace `compile "io.micronaut:micronaut-inject"` with `compileOnly "io.micronaut:micronaut-inject-groovy"` which does not work.

**Comment by jameskleeh** [comment]
@pditommaso If you think you can make that more clear, feel free to submit another PR

**Pull request closed without merging**
