### PR TITLE
Fix for #2061 - Task may have fired too early.

### PR DESCRIPTION
**Pull request by croudet**
https://github.com/micronaut-projects/micronaut-core/issues/2061

Add a check to see if the task have been fired before its fire time.

### CODE REVIEW

**Comment by jameskleeh** [comment]
Can you think of a way to test this?

**Comment by croudet** [comment]
I had the same problem with spring some years ago:
- https://github.com/spring-projects/spring-framework/issues/11669
- https://github.com/spring-projects/spring-framework/commit/dea5918d66aa25ea9ad9f44598cea3f765e21f75

I don't know ow to test this. May be we have to pass a `Clock` to that we can test it.

**Comment by jameskleeh** [comment]
@croudet Can you please rebase this to 1.2.x ?

**Comment by croudet** [comment]
Closing this one, replace by https://github.com/micronaut-projects/micronaut-core/pull/2080 based on branch `1.2.x`

**Pull request closed without merging**
