### PR TITLE
Jmx support

### PR DESCRIPTION
**Pull request by jameskleeh**

### CODE REVIEW

**Comment by graemerocher** [comment]
There are check style failures

**Comment by jameskleeh** [comment]
@graemerocher Fixed

**Comment by graemerocher** [comment]
Few problems so far:

1. `ReturnType` appears as `io.reactivex.Single`
2. Currently the raw value is returned, which is not hugely useful in some cases. If an endpoint returns a map we should represent that as tabular data https://www.oracle.com/technetwork/java/javase/tech/best-practices-jsp-136021.html#mozTocId977869
3. The health endpoint can't be invoked as a Principal is required
4. The LoggersEndpoint fails with ClassNotFoundException. Looks like for either need to alter it or return strings from the JMX MBean
5. Blank is being returned for parameters names? So parameters are represented as "Paramter-0" etc. in the JConsole UI
6. Maybe all endpoints should be grouped under `io.micronaut.management` instead of having a folder per Endpoint?

**Comment by jameskleeh** [comment]
@graemerocher 

1. The return type is `Single` with no generic because the interface that returns the data is defined as returning `Object` to allow users to return anything they like.
2. What if the map returns more/less data for any given row? Should we assume the first row is the definition of the columns? I think that could lead to inconsistent results.
3. It can be invoked, just not through the jconsole. jconsole doesn't support invoking operations with more than the basic input types.
4. OK
5. I'll take a look
6. That would require us to hard code the package for that case, but OK.

**Comment by jameskleeh** [comment]
@graemerocher Re: the parameter names. That is just how the console UI is displaying the data with a header "Parameter-0". You can see in this screenshot the parameter name is set:

screen shot 2018-09-17 at 12 05 25 pm

**Pull request merged**
