### PR TITLE
[core] Update common files for branch 2.3.x

### PR DESCRIPTION
**Pull request by micronaut-build**
Update common files

### CODE REVIEW

**Comment by alvarosanchez** [comment]
@ilopmar so can this be merged now?

**Comment by alvarosanchez** [comment]
Or we could possibly wait for https://github.com/micronaut-projects/micronaut-project-template/pull/97 to arrive here.

**Comment by ilopmar** [comment]
We could merge this and rebase this changes in #4954. But I think we've agreed to release first 2.3.3 and then merge this. Right @jameskleeh?

**Comment by ilopmar** [comment]
Oh damn! Updating the template reverted my changes back :cry:

**Pull request merged**
