### PR TITLE
Fix issues with multiple validation errors response

### PR DESCRIPTION
**Pull request by goeh**
This PR fix some but not all of the issues described in https://github.com/micronaut-projects/micronaut-core/issues/980

- Remove extra dot after property paths. This issue is only visible (in 1.0.1) when there are multiple violations.
- Change extra nested "_embedded" key to "errors". I'm not sure if this can be fixed on the 1.0.x branch as it alters the JSON response. I hope no one depends on the wrong structure in 1.0.1.

### CODE REVIEW

**Comment by graemerocher** [comment]
Changing "errors" to "_embedded" is not possible as it is breaking change. In additional, the format chosen is based on https://github.com/blongden/vnd.error

Which is a common error format and specifies the use of `_embedded` for multiple errors

**Comment by goeh** [comment]
But it's currently two nested `_embedded` and no `errors`. Is that really correct?
```
{
    "_embedded": {
        "_embedded": [
            {
                "message": "body.email.:must not be blank"
            }, 
            {
                "message": "body.username.:must not be blank"
            }
        ]
    }, 
    "_links": {
        "self": {
            "href": "/account/create", 
            "templated": false
        }
    }, 
    "message": "Bad Request"
}
```

**Comment by graemerocher** [comment]
No that is in fact a bug, it should be:

```
{
    "_embedded": {
        "errors": [
            {
                "message": "body.email.:must not be blank"
            }, 
            {
                "message": "body.username.:must not be blank"
            }
        ]
    }, 
    "_links": {
        "self": {
            "href": "/account/create", 
            "templated": false
        }
    }, 
    "message": "Bad Request"
}
```

**Comment by graemerocher** [comment]
I misunderstood the PR, yes this should be merged.

**Pull request merged**
