### PR TITLE
Handle WebLogic classloader URIs

### LINKED ISSUE #8636: Micronaut war fails to start under WebLogic 12c
### Expected Behavior

A Micronaut war file should deploy successfully to Oracle WebLogic 12c.

### Actual Behaviour

The application fails to start because it cannot find a `ApplicationEventPublisher` bean. This bean cannot cannot be created, because the startup process (via `SoftServiceLoader`) fails to find and instantiate the `ApplicationEventPublisherFactory`.

Please see the README file in the sample repository for full details on the application behavior.

Note that this may or may not be the only issue in getting a Micronaut war working in WebLogic 12c; it's certainly the first issue and affects many beans/Micronaut services.

### Steps To Reproduce

I created a default Micronaut 3.5.4 application with `mn create-app demo.weblogic-war` and only a few minor changes to `build.gradle`. I then built a war file and attempted to deploy to Oracle WebLogic 12c.

Please see the README file in the sample repository for full details to reproduce.

### Environment Information

- WebLogic 12c (running in docker)
- Java 8
- Micronaut 3.5.4

### Example Application

https://github.com/mattmoss/weblogic-war

### Version

3.5.4

### PR DESCRIPTION
**Pull request by mattmoss**
Fixes issue #8636

### CODE REVIEW

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
This needs to target 3.8.x branch

**Comment by sdelamo** [comment]
> This needs to target 3.8.x branch

No, we need to target 3.5.x because we need a patch version of the minor version used by Grails 5.
 
I will merge up the change.

**Comment by sdelamo** [comment]
I added a test. Moreover, I [verified locally that with this change, a war file deployed to WebLogic no longer throws the exception. ](https://github.com/mattmoss/weblogic-war)

**Review by graemerocher — APPROVED** [review]

**Comment by mattmoss** [comment]
Just to be clear on my change in [dcf1ab4](https://github.com/micronaut-projects/micronaut-core/pull/8646/commits/dcf1ab434029e22d7a6c8233052beed435d678f6)...  `Path.of` is not available in Java 8; that came later.

**Pull request merged**
