### PR TITLE
Changed the LoggersEndpoint to default to be disabled. Previously was enabled by default.

### PR DESCRIPTION
**Pull request by JoeBeeton**
Changed the LoggersEndpoint to default to be disabled. Previously was enabled by default.
To enable the LoggersEndpoint the following property needs to be set.
endpoints.loggers.enabled = true
This is due to the LoggersEndpoint allows unauthenticated users to modify the logging configuration of the service by default. This is inconsistent with the other management endpoints that allow modification of the internal state of the application, such as CachesEndpoint or ServerStopEndpoint which default to disabled.

Also updated the tests to validate the new behaviour and updated the documentation to reflect this change.

### CODE REVIEW

**Comment by jameskleeh** [comment]
Making the loggers endpoint disabled by default does not change the core issue here that it allows unauthorized users to modify it. It should be sensitive by default. You can update this PR to make the endpoint sensitive by default, and also ensure to list this breaking change in `breaks.adoc`

**Comment by jameskleeh** [comment]
Also please sign the CLA

**Comment by JoeBeeton** [comment]
Hello, I'm waiting on approval to sign the CLA, that may take some time. But in the mean time I'll make the requested changes.

**Comment by graemerocher** [comment]
@jameskleeh I think we should just independently apply this change and close the PR

**Comment by JoeBeeton** [comment]
Hello. Apologies, we are still waiting on getting approval of the CLA.  Ill check what the status is today.

**Comment by JoeBeeton** [comment]
Hi, still waiting, if this is going to hold up a release please do as you say "independently apply" the change and close the PR.

**Comment by graemerocher** [comment]
Applied manually. Thanks anyway

**Comment by JoeBeeton** [comment]
No problem, just glad the change is in place.

**Pull request closed without merging**
