### PR TITLE
implement client attribute annotation

### PR DESCRIPTION
**Pull request by ahmedlafta**
Related to #1074 

Also we should wait to merge until #1085 is discussed, there may be changes to this PR depending on the outcome of that.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the PR!

Few comments:

* I think `@Attribute` should be renamed to `@RequestAttribute` as the former may apply to messaging systems etc. If you want we can leave `@Attribute` as a meta annotation and have a `@RequestAttribute` use `@AliasFor` to support both. 
* We probably need to add an implementation of `AbstractAnnotatedArgumentBinder` that binds from request attributes to so we can support the same annotation on the server.
* There are check style failures that are failing to build

**Comment by ahmedlafta** [comment]
Thanks for the quick review! I agree with your comments. I will address the changes and push up soon.

**Comment by ahmedlafta** [comment]
@graemerocher this is ready for review again

**Comment by graemerocher** [comment]
Looks good, thanks for the contribution!

**Pull request merged**
