### PR TITLE
docs: add reactor context propagation example

### LINKED ISSUE #10219: docs: enhance reactor context propagation documentation
We might want to add [in] core, a note on how to add the context in the middle of the reactive chain:

```
PropagatedContext propagatedContext = PropagatedContext.get();
    mono.contextWrite(ctx -> ReactorPropagation.addPropagatedContext(ctx, propagatedContext))
```

_Originally posted by @dstepanov in https://github.com/micronaut-projects/micronaut-reactor/issues/385#issuecomment-1840475815_

### PR DESCRIPTION
**Pull request by wetted**
closes #10219

I believe we agreed in the meeting that a kotlin example is not necessary (nor appropriate).

### CODE REVIEW

**Comment by dstepanov** [comment]
I would make a note before the context is got that it was modified in some way. Otherwise, it doesn't make sense to do.

**Comment by wetted** [comment]
> I would make a note before the context is got that it was modified in some way. Otherwise, it doesn't make sense to do.

Sorry, I'm not sure I understand what you mean "that it was modified". (this is all new to me). Can you clarify for me further, please.

**Comment by dstepanov** [comment]
```
@Get('/hello')
        Mono<String> hello() {
            // The propagated context is modified ( PropagatedContext.get().add / remove etc)
            PropagatedContext propagatedContext = PropagatedContext.get() // <1>
            return Mono.just('Hello, World')
                .contextWrite(ctx -> ReactorPropagation.addPropagatedContext(ctx, propagatedContext)) // <2>
        }
```

**Comment by wetted** [comment]
> // The propagated context is modified ( PropagatedContext.get().add / remove etc)

I changed the adoc comment. See if that's OK.

**Review by dstepanov — APPROVED** [review]

**Comment by dstepanov** [comment]
Looks fine; the other option would be to add some propagation context element to make it make more clear. Please take a look @sdelamo if it's understandable.

**Comment by wetted** [comment]
@dstepanov I updated the example to add an element. See if that's OK. Thanks for the feedback.

**Review by sdelamo — APPROVED** [review]
@dstepanov should we do this for Kotlin as well?

**Comment by dstepanov** [comment]
For Kotlin we have `KotlinCoroutinePropagation`

**Comment by sdelamo** [comment]
@dstepanov do you think we should merge it in the current status?

**Review by dstepanov — APPROVED** [review]

**Comment by dstepanov** [comment]
Looks good

**Pull request merged**
