### PR TITLE
Add breaking change note about the removal of `OncePerRequestHttpServerFilter`

### LINKED ISSUE #9384: Document OncePerRequestHttpServerFilter removal
### Issue description

We removed OncePerRequestHttpServerFilter in #9344, I think we should add a note in breaks.doc 

This is what our javadoc said: 

> * @deprecated All filters are executed once per request starting in Micronaut 3.0. Directly implement {@link HttpServerFilter} instead of extending this class and replace any usages of `micronaut.once` attributes with a custom attribute name.

### PR DESCRIPTION
**Pull request by wetted**
closes #9384

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
we have to tell the users what to use instead

**Comment by dstepanov** [comment]
There is no need for this filter `server filters are executed once per request`

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
@jeremyg484 if possible this should be incorporated to OpenRewrite

**Comment by jeremyg484** [comment]
> @jeremyg484 if possible this should be incorporated to OpenRewrite

We've already got a recipe for it - https://github.com/openrewrite/rewrite-micronaut/blob/main/src/main/java/org/openrewrite/java/micronaut/OncePerRequestHttpServerFilterToHttpServerFilter.java

I'll add it to the list of recipes that get applied in the 3-to-4 migration.

**Pull request merged**
