### PR TITLE
Add support for retry with CompletableFuture

### PR DESCRIPTION
**Pull request by jameskleeh**

### CODE REVIEW

**Comment by jameskleeh** [comment]
Not sure about which executor to use, let me know

**Comment by Im-dex** [comment]
Maybe it will be better to use ScheduledExecutorService just to avoid blocking on Thread.sleep?

**Comment by jameskleeh** [comment]
@lm-dex This PR is already using the scheduled executor https://github.com/micronaut-projects/micronaut-core/pull/1565/files#diff-4d671d6772a62991306f01f02e4563d0R86

**Comment by Im-dex** [comment]
> @lm-dex This PR is already using the scheduled executor https://github.com/micronaut-projects/micronaut-core/pull/1565/files#diff-4d671d6772a62991306f01f02e4563d0R86

@jameskleeh Yes, it is used as an ExecutorService interface, but ScheduledExecutorService interface provides a more convenient method 'schedule' which could be used to delay the execution in a nonblocking manner instead of Thread.sleep.

**Comment by jameskleeh** [comment]
@lm-dex Thanks for the tip - done!

**Comment by Im-dex** [comment]
> @lm-dex Thanks for the tip - done!

@jameskleeh Nice! Thanks.

**Pull request merged**
