### PR TITLE
Ensure logout cookie has domain and path set

### PR DESCRIPTION
**Pull request by christianjank**
Issue is that logout doesn't work if path or domain configurations are set.

As a side note, when you set the cookie path, it can mean that you have to adjust the logout url to ensure the browser sends the cookie to the LogoutController. I don't know if it's worth addressing the issue and allow access to the LogoutController even if no cookie has been sent (and thus not authorization occurs). Or perhaps this is something to be mentioned in the documentation somewhere.

### CODE REVIEW

**Comment by jameskleeh** [comment]
Could this be tested without Geb?

**Comment by christianjank** [comment]
> Could this be tested without Geb?

I think Geb makes it easy to check the browser behaviour in response to the cookie value. We are using the browser as source of truth for the spec. 
In a plain code test you would have to do some work to correctly interpret the RFC spec yourself, because few http clients outside of the browser implement proper cookie handling (it's just rarely relevant).

**Comment by jameskleeh** [comment]
@christianjank Isn't this line enough to test the functionality is working as intended? https://github.com/micronaut-projects/micronaut-core/pull/1361/files#diff-ab822949faa6ec01ecd93153e22d5fa9R74

The rest of it just seems like it's redundant

**Comment by christianjank** [comment]
> @christianjank Isn't this line enough to test the functionality is working as intended? [...]
Sorry not sure what line you mean, don't think the link works.

I any case, thinking about it, you are probably right, and it should be entirely sufficient to assert that the login cookie is the same as the logout cookie (with the exception of value and expiration). I'll make the change.

**Comment by christianjank** [comment]
Anyone know why the build failed? It's not clear to me.

**Comment by graemerocher** [comment]
@christianjank was a temporary unrelated failure in master. If you rebase should be ok

**Pull request merged**
