### PR TITLE
Upgrade to Netty 4.1.52

### LINKED ISSUE #3842: Upgrade netty to 4.1.52.Final
https://netty.io/news/2020/07/09/4-1-51-Final.html mentions some changes to accommodate openssl and GraalVM

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #3842

### CODE REVIEW

**Comment by graemerocher** [comment]
Causing build to hang?

**Comment by ilopmar** [comment]
Yes, it seems so. I'll try to find locally which test hangs...

**Comment by ilopmar** [comment]
@graemerocher fixed! 

This was because of [this change](https://github.com/netty/netty/pull/10407) introduced in Netty that makes necessary to bump `tcnative` to 2.0.33. Is this something we should highlight in the "what's new" section in the docs?

**Comment by graemerocher** [comment]
Probably worth mentioning yes. Nice find!

**Comment by ilopmar** [comment]
Done

**Pull request merged**
