### PR TITLE
build: use micronaut rxjava2 bom

### LINKED ISSUE #6858: Update Library Catalogue to use rxjava2 bom included in 1.2.0
### Issue description

[Micronaut RxJava2 1.2.0](https://github.com/micronaut-projects/micronaut-rxjava2/releases/tag/v1.2.0) introduced a bom module.

### PR DESCRIPTION
**Pull request by timyates**
Closes #6858

### CODE REVIEW

**Comment by dstepanov** [comment]
After this change I cannot use reference:
- `mn.micronaut.reactor`
- `mn.micronaut.rxjava2`
- `mn.reactor`
-  `mn.rxjava2`

Those references were used in the Micronaut Data

@melix Is there a different syntax?

**Comment by dstepanov** [comment]
IMHO we should keep the reference without the version.

**Comment by melix** [comment]
That's correct, it's the drawback of moving everything to BOMs. Possibly we could automate the creation of those "nested BOMs" in catalogs if the included BOMs are themselves published as catalogs (we could parse the TOML file and deduce what elements to add).

**Comment by sdelamo** [comment]
> After this change I cannot use reference:
> 
> * `mn.micronaut.reactor`
> * `mn.micronaut.rxjava2`
> * `mn.reactor`
> * `mn.rxjava2`
> 
> Those references were used in the Micronaut Data
> 
> @melix Is there a different syntax?

can you not use? 

```
implementation(platform("io.micronaut.reactor:micronaut-reactor-bom"))
implementation("io.micronaut.reactor:micronaut-reactor")
```

**Comment by melix** [comment]
> can you not use?

You can, but it defeats the concept of catalogs and type-safe accessors.

**Pull request merged**
