### PR TITLE
Removed unused imports

### PR DESCRIPTION
**Pull request by marceloverdijk**
While going through some Micronaut code I noticed some unused imports. This PR removes them.

### CODE REVIEW

**Comment by jameskleeh** [comment]
Can you rebase this to 1.0.x ?

**Comment by marceloverdijk** [comment]
@jameskleeh done

**Comment by jameskleeh** [comment]
@marceloverdijk This PR is still targeting master

**Comment by marceloverdijk** [comment]
@jameskleeh then I misunderstood, what should I do?

**Comment by jameskleeh** [comment]
@marceloverdijk Check out this guide https://akrabat.com/the-beginners-guide-to-rebasing-your-pr/

**Comment by marceloverdijk** [comment]
I've rebased again (like I did before, but maybe something went wrong earlier).
PS: I rebased against `master` or should I rebase against a different branch?

**Comment by jameskleeh** [comment]
Closing this as it appears the changes have already been made in the 1.0.x. Appreciate the effort!

**Pull request closed without merging**
