### PR TITLE
Fix micronaut-test bom inclusion

### PR DESCRIPTION
**Pull request by timyates**
After the update to 3.1.0 in #7008, we no longer need the aliases for the
managed dependencies

### CODE REVIEW

**Comment by timyates** [comment]
Hmmm, no...this is wrong... 🤔

**Review by melix — APPROVED** [review]

**Comment by timyates** [comment]
@melix I get failures here and locally...  I can't see why...  It should be importing from the bom shouldn't it?

```
    testImplementation(libs.managed.micronaut.test.junit5) {
```

is failing in http-client

**Comment by melix** [comment]
No, if you remove them from the catalog, there won't be accessors anymore. You'd get accessors if we actually used the catalog that we generate in the same build, which is obviously a chicken and egg problem. It's probably fine to keep them in the catalog then.

**Comment by timyates** [comment]
I'll close this then 😀

**Pull request closed without merging**
