### PR TITLE
Upgrade Netty to 4.1.63

### PR DESCRIPTION
**Pull request by ilopmar**

### CODE REVIEW

**Comment by ilopmar** [comment]
A test fails and a few of them get stuck during execution:

### Failing test

[This test fails](https://github.com/micronaut-projects/micronaut-core/blob/4d6a732c5671d8f90977321742c1c0592342f69c/http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/HttpResponseSpec.groovy#L125) but doesn't make sense because the `content-length` header is there:

DeepinScreenshot_select-area_20210312123626

Test failure log: https://github.com/micronaut-projects/micronaut-core/runs/2093408533?check_suite_focus=true#step:7:3889

### Stuck tests

- `testPostVertx` gets stuck [here](https://github.com/micronaut-projects/micronaut-core/blob/dcbc9226f50bb1b701303e549f1f8194cf20773b/http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2PostTest.java#L100).

- The tests `"test the file is not corrupted with transferTo"` are also stuck:
[MixedUploadSpec](https://github.com/micronaut-projects/micronaut-core/blob/a81e3125b28a3e886adbe7042a7cf2037b6ac139/test-suite/src/test/groovy/io/micronaut/upload/MixedUploadSpec.groovy#L369) 
[StreamUploadSpec](https://github.com/micronaut-projects/micronaut-core/blob/a81e3125b28a3e886adbe7042a7cf2037b6ac139/test-suite/src/test/groovy/io/micronaut/upload/StreamUploadSpec.groovy#L492)
[DiskUploadSpec](https://github.com/micronaut-projects/micronaut-core/blob/a81e3125b28a3e886adbe7042a7cf2037b6ac139/test-suite/src/test/groovy/io/micronaut/upload/DiskUploadSpec.groovy#L369)


Netty 4.1.60 release notes: https://netty.io/news/2021/03/09/4-1-60-Final.html

From the issues fixed there I'm not really sure what made these things fail. Maybe [this for the header](https://github.com/netty/netty/commit/89c241e3b1795ff257af4ad6eadc616cb2fb3dc4) and [this for the POST requests](https://github.com/netty/netty/issues/10508) but I'm not really sure.

@jameskleeh @graemerocher any thoughts?

**Comment by graemerocher** [comment]
No idea personally, and away this week @jameskleeh might be related to the general issues with file uploads those tests have been failing intermittently in the past. We should prioritise this upgrade for the next release since there is a CVE associated

**Comment by jameskleeh** [comment]
Currently blocked by https://github.com/netty/netty/issues/11143

**Comment by ilopmar** [comment]
Tried GraalVM with Netty 4.1.63 and it works properly.

**Pull request merged**
