### PR TITLE
fix configuration inheritance path calculation

### LINKED ISSUE #8480: Configuration chains do not get correctly applied
In the Redis module, preparing for Micronaut 4.0.0 (in [this PR](https://github.com/micronaut-projects/micronaut-redis/pull/331) there is a Session configuration object

https://github.com/micronaut-projects/micronaut-redis/blob/6.0.x/redis-lettuce/src/main/java/io/micronaut/configuration/lettuce/session/RedisHttpSessionConfiguration.java

In one of the tests, we set the write-mode to background

https://github.com/micronaut-projects/micronaut-redis/blob/6.0.x/redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/session/RedisSessionSpec.groovy#L155

But this is never configured.

It works if I change the setter in the configuration object to

```diff
-    public void setWriteMode(WriteMode writeMode) {
+    public void setWriteMode(@Property(name = "micronaut.session.http.redis.write-mode") WriteMode writeMode) {
         this.writeMode = writeMode;
     }
```

But this shouldn't be required

### PR DESCRIPTION
**Pull request by graemerocher**
Fixes #8480

### CODE REVIEW

**Comment by graemerocher** [comment]
@dstepanov I added a failing test, could you have a look? Thanks.

**Comment by graemerocher** [comment]
the test failure is one of the flakey ones

**Review by dstepanov — APPROVED** [review]

**Review by timyates — APPROVED** [review]

**Comment by timyates** [comment]
@graemerocher With this [PR applied to core](https://github.com/micronaut-projects/micronaut-core/wiki/Gradle-Build-Tips#building-a-module-against-a-local-version-of-micronaut-core), we still have some failing tests on the https://github.com/micronaut-projects/micronaut-redis/pull/331 PR

It seems to be `redis.uri` is ignored in the configuration applied here

https://github.com/micronaut-projects/micronaut-redis/blob/5aa26639ed31f7beea0c386a6cce367fd4ada9d8/redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/session/SessionSpec.groovy#L50-L55

**Comment by timyates** [comment]
Ahhh, it could be the different types in the setter and getter causing it to be ignored?

```
    /**
     * @return Get the Redis URI for configuration.
     */
    public Optional<RedisURI> getUri() {
        if (uri != null) {
            uri.setClientName(getClientName());
        }
        return Optional.ofNullable(uri);
    }

    /**
     * Sets the Redis URI for configuration by string.
     *
     * @param uri The URI
     */
    public void setUri(URI uri) {
        this.uri = RedisURI.create(uri);
    }
```

**Comment by timyates** [comment]
uri doesn't appear in the generated `$DefaultRedisConfiguration$Definition.class` at the moment 🤔

**Comment by timyates** [comment]
We don't get `uris` either, I guess for the same reason...

```
    /**
     * @return Get the Redis URIs for cluster configuration.
     */
    public List<RedisURI> getUris() {
        return uris;
    }

    /**
     * Sets the Redis URIs for cluster configuration.
     *
     * @param uris The URI
     */
    public void setUris(URI... uris) {
        this.uris = Arrays.stream(uris).map(RedisURI::create).collect(Collectors.toList());
    }
```

**Comment by timyates** [comment]
I can get `uris` working by adding

```
    public void setUris(List<URI> uris) {
        this.uris = uris.stream().map(RedisURI::create).collect(Collectors.toList());
    }
```

But I don't know if this is the right direction to take...  and not sure what to do with `uri` for the best 🤔

**Comment by graemerocher** [comment]
looking into this

**Comment by graemerocher** [comment]
probably to do with the differing return types

**Comment by graemerocher** [comment]
I pushed another fix for this, lets see if it passes

**Comment by timyates** [comment]
If it does, that fixes the redis PR 👍

**Comment by timyates** [comment]
Think it's just CheckStyle failing with a couple of unused imports and some todos?

https://ge.micronaut.io/s/erv4cetphmoz2/console-log?task=:core-processor:checkstyleMain

**Pull request merged**
