### PR TITLE
Upgrade Brave tracing libs

### PR DESCRIPTION
**Pull request by dstepanov**
New Brave version reduces the number of spans, instead of having two spans for one call CLIENT -> SERVER it will only keep SERVER span if a server is traced otherwise CLIENT span will be kept; that’s why there is so many changes in tests.

I did some refactoring, removing deprecated code and tagging that is already done by the brave framework.

### CODE REVIEW

**Comment by graemerocher** [comment]
Is there a changelog in Brave that mentions this change in behaviour? Just want to confirm that it is not something we are doing wrong here.

**Comment by dstepanov** [comment]
I haven't found anything specifically mentioned.
First I thought it's a bug, this behavior does make sense, I was able to replicate it by modifying the nested test to run a separate micronaut instance without tracing enabled then one SERVER span switched to CLIENT, which I think is a prove no spans are lost.

**Comment by graemerocher** [comment]
Ok, will research a bit further, but other than that the PR seems ok.

**Comment by dstepanov** [comment]
I will need to correct the PR after serviceName PR got merged.
I can also refactor to use `CurrentTraceContext#wrap` instead of `TracingRunnable` and `TracingCallable`.

**Comment by graemerocher** [comment]
Sounds good.

**Comment by dstepanov** [comment]
I did some refactoring regarding wrapping of `Runnable` and `Callable` when Brave is present then `CurrentTraceContext#wrap` is used.

Somehow build is failing on unrelated tests.

**Comment by graemerocher** [comment]
Yeah we are looking into those tests. Sorry about that. They happen on master following a recent change.

Regarding the changes could you restore their deleted classes and mark them as deprecated instead. Deleting would be a breaking change

**Comment by dstepanov** [comment]
Done. Can you merge 1.2 to master so I can solve the conflict?

**Comment by graemerocher** [comment]
Done

**Comment by dstepanov** [comment]
Merged master and added a test to test not-traced server call will have CLIENT span with service name set.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
