### PR TITLE
Upgraded logback to 1.4.11

### LINKED ISSUE #9835: Micronaut application won't start when including the logback dependency and configuring the log levels via application.properties
### Expected Behavior

The application start and set the right log level for the packages that have been specified in the application.properties file.

### Actual Behaviour

The application does not start due to the following error:
`
Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.logging.PropertiesLoggingLevelsConfigurer]

Message: 'void ch.qos.logback.classic.util.ContextInitializer.configureByResource(java.net.URL)'
Path Taken: new PropertiesLoggingLevelsConfigurer(Environment environment,List loggingSystems)
`

Debugging noticed that the latest `logback-classic` version (1.4.11) removed the method: `ContextInitializer.configureByResource`, but `LogbackUtils` from `micronaut-context:4.1.3` still uses it. 

### Steps To Reproduce

1. Create a micronaut service including logback dependency.
2. Configure the log level for a certain package using the application.properties like `logger.levels.com.example=DEBUG`
3. Try to run the application and it won't start.

It can also be reproduced just running the following test: https://github.com/jaime-mugico/micronaut-4.1.0-logback-context-bug/blob/main/src/test/kotlin/com/example/LogbackContextTest.kt#L9 that is included in the example application.

### Environment Information

- Operating system: macOS 13.5
- JDK: 1.17

### Example Application

https://github.com/jaime-mugico/micronaut-4.1.0-logback-context-bug/tree/main

### Version

4.1.0

### PR DESCRIPTION
**Pull request by msupic**
Changes:
- upgraded logback to 1.4.11
- modified `LogbackUtils` class (the `configureByResource` method was removed from the `ContextInitializer` class, so replaced it with the same method from the `DefaultJoranConfigurator` class)
- added native tests for logging

Closes #9835

### CODE REVIEW

**Review by timyates — APPROVED** [review]
We should update micronaut-logging as well people writing apps will be using the version of logback from the micronaut-logging-pom

**Comment by timyates** [comment]
I added this to the 4.1.1 project

Added @sdelamo as a reviewer for visibility (as he's on the https://github.com/micronaut-projects/micronaut-core/issues/9835 issue)

**Review by sdelamo — APPROVED** [review]

**Comment by yawkat** [comment]
@melix does this work with aot

**Comment by sdelamo** [comment]
> @melix does this work with aot

does logback 1.4.11 has problems with AoT @melix ?

**Comment by melix** [comment]
I think it should. Given that AOT simply parses the logback.xml file and replaces it itself with the default Joran configurator, there should be no change.

**Comment by sdelamo** [comment]
we have a PR which upgraded AOT to use Micronaut logging to logging 1.1.0 which updates to 1.4.11 which passed https://github.com/micronaut-projects/micronaut-aot/pull/237  I assume that would have failed if we had problems.

**Comment by sdelamo** [comment]
I created an issue in Logback to see if they can ship the reflect-config.json themselves. 

https://github.com/qos-ch/logback/issues/703

**Comment by sdelamo** [comment]
I created an[ issue also to clarify whether they use semantic versioning](https://github.com/qos-ch/logback/issues/704).

**Comment by sdelamo** [comment]
I created an issue in the GraalVM Reachability repository: 

https://github.com/oracle/graalvm-reachability-metadata/issues/396

**Pull request merged**
