### PR TITLE
Add nullable annotations transformers

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by graemerocher** [comment]
please target 4.0.x move them all to the `core-processor` module

**Comment by altro3** [comment]
@graemerocher done

**Comment by graemerocher** [comment]
The PR includes other commits from 3.9.x please alter it to include only the changes in this PR

**Comment by altro3** [comment]
@graemerocher new PR here: https://github.com/micronaut-projects/micronaut-core/pull/9247

**Pull request closed without merging**
