### PR TITLE
Fix #2066 - Add support for native transport channel options

### LINKED ISSUE #2066: Ability to use native transport options with Netty
### Steps to Reproduce

1. Try to use `TCP_CORK` or `TCP_QUICKACK`
2. Can't
3. See below in *Example Application* for code example

### Expected Behaviour

It would be really cool to be able to use higher-level options for `epoll` and `kqueue`

### Actual Behaviour

Instead, they are seen as "unknown options" on a given channel, even if `use-native-transport` is `true`. This is because Micronaut currently looks for socket options on the regular [`ChannelOption`](https://netty.io/4.0/api/io/netty/channel/ChannelOption.html), instead of knowing to look on the implementation-specific ones (like, say, [`EpollChannelOption`](https://netty.io/4.0/api/io/netty/channel/epoll/EpollChannelOption.html) and [`KQueueChannelOption`](https://netty.io/4.1/api/io/netty/channel/kqueue/KQueueChannelOption.html).

### Environment Information

- **Operating System**: `macOS 10.14.6` and `Alpine Linux`
- **Micronaut Version:** `master`
- **JDK Version:**
   ```
   java version "1.8.0_221"
   Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
   Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
   ```

### Example Application

**`application.yml`**
```yaml
micronaut:
  server:
    netty:
      use-native-transport: true
      childOptions:
        tcpNodelay: true
        tcpQuickack: true
````

*Note: I'm told one should never enable both `TCP_NODELAY` and `TCP_QUICKACK` at the same time, but I'm doing it here to illustrate that one is supported, and the other is not.*

Here is the output when trying to run an app with the above config:
```
17:25:25 [INFO]: Startup completed in 2152ms. Server Running: http://0.0.0.0:8080
17:25:40 [WARN]: Unknown channel option 'TCP_QUICKACK' for channel '[id: 0x23d15fe9, L:/0:0:0:0:0:0:0:1%0:8080 - R:/0:0:0:0:0:0:0:1%0:63150]'
[... app logs begin...]
```

### PR DESCRIPTION
**Pull request by croudet**
Options can be specified like regular options and childOptions

Ref: https://github.com/micronaut-projects/micronaut-core/issues/2066
https://github.com/micronaut-projects/micronaut-core/pull/2106

### CODE REVIEW

**Comment by croudet** [comment]
Questions: in `NettyConverters` there is two entries for `ChannelOption`. Is it expected?

```java
         conversionService.addConverter(
                CharSequence.class,
                ChannelOption.class,
                (TypeConverter<CharSequence, ChannelOption>) (object, targetType, context) -> {
                    String str = object.toString();
                    String name = NameUtils.underscoreSeparate(str).toUpperCase(Locale.ENGLISH);
                    ChannelOption<Object> channelOption = ChannelOption.valueOf(name);
                    if (channelOption != null) {
                        return Optional.of(channelOption);
                    }
                    return Optional.empty();
                }
        );
  ...
        conversionService.addConverter(
                String.class,
                ChannelOption.class,
                s -> ChannelOption.valueOf(NameUtils.environmentName(s))
        );
```

**Comment by croudet** [comment]
I also have another branch with a different approach, where ChannelOption converter is choosed upon native transport availability.
https://github.com/croudet/micronaut-core/commit/386dac0ff01f4f4283cbd6ece3d4c02198233889

**Comment by croudet** [comment]
I have another branch https://github.com/croudet/micronaut-core/tree/GenerateChannelOptionsLookupClasses

Where lookup classes (source) are generated at compilation time to avoid using reflection at runtime.
It uses a gradle task for that purpose.
The generated classes looks like:
```java
/**
 * ChannelOptions look up functions.
 *
 * @author autogenerated class
 */
@Singleton
@Internal
@Primary
public class DefaultChannelOptions implements ChannelOptions {

    @Override
    public Optional<Class> channelOptionType(ChannelOption<?> option) {
        switch (option.name()) {
            case "ALLOCATOR": return Optional.of(io.netty.buffer.ByteBufAllocator.class);
            case "ALLOW_HALF_CLOSURE": return Optional.of(java.lang.Boolean.class);
            case "AUTO_CLOSE": return Optional.of(java.lang.Boolean.class);
            case "AUTO_READ": return Optional.of(java.lang.Boolean.class);
            case "CONNECT_TIMEOUT_MILLIS": return Optional.of(java.lang.Integer.class);
            case "DATAGRAM_CHANNEL_ACTIVE_ON_REGISTRATION": return Optional.of(java.lang.Boolean.class);
            case "IP_MULTICAST_ADDR": return Optional.of(java.net.InetAddress.class);
            case "IP_MULTICAST_IF": return Optional.of(java.net.NetworkInterface.class);
            case "IP_MULTICAST_LOOP_DISABLED": return Optional.of(java.lang.Boolean.class);
            case "IP_MULTICAST_TTL": return Optional.of(java.lang.Integer.class);
            case "IP_TOS": return Optional.of(java.lang.Integer.class);
            case "MAX_MESSAGES_PER_READ": return Optional.of(java.lang.Integer.class);
            case "MESSAGE_SIZE_ESTIMATOR": return Optional.of(io.netty.channel.MessageSizeEstimator.class);
            case "RCVBUF_ALLOCATOR": return Optional.of(io.netty.channel.RecvByteBufAllocator.class);
            case "SINGLE_EVENTEXECUTOR_PER_GROUP": return Optional.of(java.lang.Boolean.class);
            case "SO_BACKLOG": return Optional.of(java.lang.Integer.class);
            case "SO_BROADCAST": return Optional.of(java.lang.Boolean.class);
            case "SO_KEEPALIVE": return Optional.of(java.lang.Boolean.class);
            case "SO_LINGER": return Optional.of(java.lang.Integer.class);
            case "SO_RCVBUF": return Optional.of(java.lang.Integer.class);
            case "SO_REUSEADDR": return Optional.of(java.lang.Boolean.class);
            case "SO_SNDBUF": return Optional.of(java.lang.Integer.class);
            case "SO_TIMEOUT": return Optional.of(java.lang.Integer.class);
            case "TCP_NODELAY": return Optional.of(java.lang.Boolean.class);
            case "WRITE_BUFFER_HIGH_WATER_MARK": return Optional.of(java.lang.Integer.class);
            case "WRITE_BUFFER_LOW_WATER_MARK": return Optional.of(java.lang.Integer.class);
            case "WRITE_BUFFER_WATER_MARK": return Optional.of(io.netty.channel.WriteBufferWaterMark.class);
            case "WRITE_SPIN_COUNT": return Optional.of(java.lang.Integer.class);
            default: return Optional.empty();
        }
    }
}
```

```java
/**
 * ChannelOptions look up functions.
 *
 * @author autogenerated class
 */
@Singleton
@Internal
@Named("EpollChannelOptions")
public class EpollChannelOptions extends DefaultChannelOptions {

    @Override
    public String channelOptionInternalName(String name) {
        switch (name) {
            case "EPOLL_MODE": return "io.netty.channel.epoll.EpollChannelOption#EPOLL_MODE";
            case "SO_BUSY_POLL": return "io.netty.channel.epoll.EpollChannelOption#SO_BUSY_POLL";
            case "TCP_CORK": return "io.netty.channel.epoll.EpollChannelOption#TCP_CORK";
            case "TCP_DEFER_ACCEPT": return "io.netty.channel.epoll.EpollChannelOption#TCP_DEFER_ACCEPT";
            case "TCP_FASTOPEN": return "io.netty.channel.epoll.EpollChannelOption#TCP_FASTOPEN";
            case "TCP_FASTOPEN_CONNECT": return "io.netty.channel.epoll.EpollChannelOption#TCP_FASTOPEN_CONNECT";
            case "TCP_KEEPCNT": return "io.netty.channel.epoll.EpollChannelOption#TCP_KEEPCNT";
            case "TCP_KEEPIDLE": return "io.netty.channel.epoll.EpollChannelOption#TCP_KEEPIDLE";
            case "TCP_KEEPINTVL": return "io.netty.channel.epoll.EpollChannelOption#TCP_KEEPINTVL";
            case "TCP_NOTSENT_LOWAT": return "io.netty.channel.epoll.EpollChannelOption#TCP_NOTSENT_LOWAT";
            case "TCP_QUICKACK": return "io.netty.channel.epoll.EpollChannelOption#TCP_QUICKACK";
            case "TCP_USER_TIMEOUT": return "io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT";
            case "DOMAIN_SOCKET_READ_MODE": return "io.netty.channel.unix.UnixChannelOption#DOMAIN_SOCKET_READ_MODE";
            case "SO_REUSEPORT": return "io.netty.channel.unix.UnixChannelOption#SO_REUSEPORT";
            default : return super.channelOptionInternalName(name);
        }
    }

    @Override
    public Optional<Class> channelOptionType(ChannelOption<?> option) {
        switch (option.name()) {
            case "IP_FREEBIND": return Optional.of(java.lang.Boolean.class);
            case "IP_RECVORIGDSTADDR": return Optional.of(java.lang.Boolean.class);
            case "IP_TRANSPARENT": return Optional.of(java.lang.Boolean.class);
            case "MAX_DATAGRAM_PAYLOAD_SIZE": return Optional.of(java.lang.Integer.class);
            case "TCP_MD5SIG": return Optional.of(java.util.Map.class);
            case "io.netty.channel.epoll.EpollChannelOption#EPOLL_MODE": return Optional.of(io.netty.channel.epoll.EpollMode.class);
            case "io.netty.channel.epoll.EpollChannelOption#SO_BUSY_POLL": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_CORK": return Optional.of(java.lang.Boolean.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_DEFER_ACCEPT": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_FASTOPEN": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_FASTOPEN_CONNECT": return Optional.of(java.lang.Boolean.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_KEEPCNT": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_KEEPIDLE": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_KEEPINTVL": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_NOTSENT_LOWAT": return Optional.of(java.lang.Long.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_QUICKACK": return Optional.of(java.lang.Boolean.class);
            case "io.netty.channel.epoll.EpollChannelOption#TCP_USER_TIMEOUT": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.unix.UnixChannelOption#DOMAIN_SOCKET_READ_MODE": return Optional.of(io.netty.channel.unix.DomainSocketReadMode.class);
            case "io.netty.channel.unix.UnixChannelOption#SO_REUSEPORT": return Optional.of(java.lang.Boolean.class);
            default: return super.channelOptionType(option);
        }
    }
}
```

```java
/**
 * ChannelOptions look up functions.
 *
 * @author autogenerated class
 */
@Singleton
@Internal
@Named("KQueueChannelOptions")
public class KQueueChannelOptions extends DefaultChannelOptions {

    @Override
    public String channelOptionInternalName(String name) {
        switch (name) {
            case "RCV_ALLOC_TRANSPORT_PROVIDES_GUESS": return "io.netty.channel.kqueue.KQueueChannelOption#RCV_ALLOC_TRANSPORT_PROVIDES_GUESS";
            case "SO_ACCEPTFILTER": return "io.netty.channel.kqueue.KQueueChannelOption#SO_ACCEPTFILTER";
            case "SO_SNDLOWAT": return "io.netty.channel.kqueue.KQueueChannelOption#SO_SNDLOWAT";
            case "TCP_NOPUSH": return "io.netty.channel.kqueue.KQueueChannelOption#TCP_NOPUSH";
            case "DOMAIN_SOCKET_READ_MODE": return "io.netty.channel.unix.UnixChannelOption#DOMAIN_SOCKET_READ_MODE";
            case "SO_REUSEPORT": return "io.netty.channel.unix.UnixChannelOption#SO_REUSEPORT";
            default : return super.channelOptionInternalName(name);
        }
    }

    @Override
    public Optional<Class> channelOptionType(ChannelOption<?> option) {
        switch (option.name()) {
            case "io.netty.channel.kqueue.KQueueChannelOption#RCV_ALLOC_TRANSPORT_PROVIDES_GUESS": return Optional.of(java.lang.Boolean.class);
            case "io.netty.channel.kqueue.KQueueChannelOption#SO_ACCEPTFILTER": return Optional.of(io.netty.channel.kqueue.AcceptFilter.class);
            case "io.netty.channel.kqueue.KQueueChannelOption#SO_SNDLOWAT": return Optional.of(java.lang.Integer.class);
            case "io.netty.channel.kqueue.KQueueChannelOption#TCP_NOPUSH": return Optional.of(java.lang.Boolean.class);
            case "io.netty.channel.unix.UnixChannelOption#DOMAIN_SOCKET_READ_MODE": return Optional.of(io.netty.channel.unix.DomainSocketReadMode.class);
            case "io.netty.channel.unix.UnixChannelOption#SO_REUSEPORT": return Optional.of(java.lang.Boolean.class);
            default: return super.channelOptionType(option);
        }
    }
}
```

**Comment by graemerocher** [comment]
The reflection approach is probably fine since it is limited use of reflection. To make it work on GraalVM we would probably need to add the following declaration to `MicronautSubstitutions`:

```
@TypeHint(value = ChannelOption.class, accessType = TypeHint.AccessType.ALL_DECLARED_FIELDS)
```

**Comment by graemerocher** [comment]
although I see we would need one for `KQueueChannelOption` as well

**Comment by croudet** [comment]
Replaced by https://github.com/micronaut-projects/micronaut-core/pull/3056

**Pull request closed without merging**
