### PR TITLE
Support reading BeanDefinitionReference from nested JARS

### LINKED ISSUE #12589: Runnable jar fails for 5.2.0
### Expected Behavior

App should start normally

### Actual Behaviour

Get a stack trace,  app doesn't start.
```
ava.nio.file.FileSystemAlreadyExistsException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:722)
	at io.micronaut.core.io.service.SoftServiceLoader$DefaultServiceCollector.collect(SoftServiceLoader.java:536)
	at io.micronaut.core.io.service.SoftServiceLoader.collectDynamicServices(SoftServiceLoader.java:199)
	at io.micronaut.core.io.service.SoftServiceLoader.collectAll(SoftServiceLoader.java:175)
	at io.micronaut.context.DefaultBeanContext.resolveBeanDefinitionReferences(DefaultBeanContext.java:1730)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapPropertySourceLocatorPresent(DefaultApplicationContext.java:153)
	at io.micronaut.context.DefaultApplicationContext.isBootstrapEnabled(DefaultApplicationContext.java:149)
	at io.micronaut.context.DefaultApplicationContext.createEnvironment(DefaultApplicationContext.java:137)
	at io.micronaut.context.DefaultApplicationContext.getEnvironment(DefaultApplicationContext.java:181)
	at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:181)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:485)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:472)
	at foo.app.Application.main(Application.groovy:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.nio.file.FileSystemAlreadyExistsException: null
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
	at io.micronaut.core.io.IOUtils.eachFile(IOUtils.java:88)
	at io.micronaut.core.io.service.SoftServiceLoader.computeServiceTypeNames(SoftServiceLoader.java:277)
	at io.micronaut.core.io.service.SoftServiceLoader.access$1100(SoftServiceLoader.java:68)
	at io.micronaut.core.io.service.SoftServiceLoader$MicronautMetaServicesLoader.compute(SoftServiceLoader.java:565)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
### Steps To Reproduce

1. [Install SDKMan](https://sdkman.io/install)
2. sdk install grails 5.2.0
3. grails create-app foobar
4. cd foobar
5. ./gradlew clean bootJar
6. java -jar build/libs/foobar-0.1.jar

### Environment Information

MacOSX 12.4

sdk current

Using:

ant: 1.10.12
gradle: 7.4.2
grails: 5.2.0
groovy: 3.0.11
java: 11.0.15.fx-zulu
kotlin: 1.7.0
maven: 3.8.6
micronaut: 3.5.2
springboot: 2.7.1
tomcat: 10.0.22
SBortman-MacBook-Pro /tmp/foo-app $

### Example Application

_No response_

### Version

5.2.0

### PR DESCRIPTION
**Pull request by puneetbehl**
Update `IOUtils.eachFile` method to read `META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference` files from the nested JAR. For instance, `jar:file:/Users/pbehl/Downloads/foobar/build/libs/foobar-0.1.jar!/BOOT-INF/lib/micronaut-inject-3.5.3-SNAPSHOT.jar!/META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference`.

Fixes https://github.com/grails/grails-core/issues/12589

### CODE REVIEW

**Comment by puneetbehl** [comment]
It appear that it is failing for usage of `Files.createTempFile`. However, I can see usages of the same at other places in the code. It maybe that I am missing something. Could you please help point out the correct way to solve this?

**Comment by codeconsole** [comment]
@graemerocher  or @sdelamo ?

**Comment by dstepanov** [comment]
Is there a way to have a reproducer?

**Comment by codeconsole** [comment]
> Is there a way to have a reproducer?

@dstepanov This issue comes from https://github.com/grails/grails-core/issues/12589

```
sdk use java 22.1.0.r11-grl 
git clone https://github.com/codeconsole/website
cd website
./gradlew bootJar
```

**Comment by puneetbehl** [comment]
FYI, I am also trying to add a test in Micronaut Core which reproduces the problem.

**Pull request closed without merging**
