### PR TITLE
@Property must be placed in constructor for Kotlin

### PR DESCRIPTION
**Pull request by debuglevel**
Documentation of the solution for issue https://github.com/micronaut-projects/micronaut-core/issues/971

### CODE REVIEW

**Comment by jameskleeh** [comment]
@debuglevel I'm not certain the report you linked should have been closed. `@Property` should work in Kotlin classes.

**Comment by debuglevel** [comment]
Would be nice, of course, if this worked. But I've seen same issues like "in Kotlin, you have to place this thing in the constructor" elsewhere. (On the other hand, I'm just a Kotlin user and have no idea about the internals of Kotlin :-))

**Comment by jameskleeh** [comment]
The following works:

```
    @set:Inject
    @setparam:Property(name="app.string")
    var stringParam:String ?= null

    @set:Inject
    @setparam:Property(name="app.map")
    @setparam:MapFormat(transformation = MapFormat.MapTransformation.FLAT)
    var mapParam:Map<String, String> ?= null
```

**Comment by jameskleeh** [comment]
I'm going to improve the documentation to show examples specific to Kotlin

**Pull request closed without merging**
