### PR TITLE
Support escaping the default value delimiter 

### PR DESCRIPTION
**Pull request by jameskleeh**

### CODE REVIEW

**Comment by graemerocher** [comment]
couldn't this just be resolved by using 2 variables 

ie. `${CONSUL_HOST:localhost}:${CONSUL_PORT:8755}`

**Comment by graemerocher** [comment]
Also note that this change differs to how Grails/Spring handle this case https://stackoverflow.com/questions/31711308/spring-value-escape-colon-in-default-value

**Comment by jameskleeh** [comment]
@graemerocher There are use cases where using a ':' in the default value is necessary. Would you prefer to only support a single default value?

**Comment by graemerocher** [comment]
The options as I see it are 

1. Support escaping (this pull request)
2. Support quotes (pre-Spring 4.2 behaviour), may be more elegant than this solution
3. Support only a single default value (seems to be the way Spring/Grails behave now)

Option 3 is maybe less surprising for users, however I believe the reason to drop the quote behaviour and only allow a single default value is because Spring supports SpEL expressions (something we don't want to support for the moment because of performance/memory consumption).

**Comment by ilopmar** [comment]
I've found one issue related to this change. I want to define the following in `application.yml`
```yml
datasources:
    default:
        url: ${JDBC_URL:jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}
```
The `url` resolved when the property `JDBC_URL` is not defined is `default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE` instead of `jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`

You can reproduce it adding modifying the test in this same PR to:

```groovy
    void "test escaping the value delimiter"() {
        given:
        def values = [
                'foo.bar'   : '10',
                'foo.baz'   : 20,
                'bar'       : '${foo:some\\:value}',
                'baz'       : '${foo:some\\:value:some\\:other\\:value}',
                'datasource': '${JDBC_URL:jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}'
        ]
        PropertySourcePropertyResolver resolver = new PropertySourcePropertyResolver(
                PropertySource.of("test", values)
        )

        expect:
        resolver.getProperty("bar", String).get() == "some:value"
        resolver.getProperty("baz", String).get() == "some:other:value"
        resolver.getProperty("datasource", String).get() == "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    }
```

**Comment by ilopmar** [comment]
I'm sorry, I should have read the test carefully. Defining the property follow makes the test pass:

```
'datasource': '${JDBC_URL:jdbc\\:h2\\:mem\\:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}'
```

But in `application.yml` I need to define it with only one `\`:

```
datasources:
    default:
        url: ${JDBC_URL:jdbc\:h2\:mem\:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
```

I think that this PR should also include an update to the documentation.

**Comment by graemerocher** [comment]
That seems ugly to me. I think we should support quotes instead of escaping IMO

**Comment by jameskleeh** [comment]
The problem with quotes is that someone will have to escape them unless we support both types of quotes. It's also more complicated to implement. Groovy has to escape single quotes because the whole string has to be in single quotes. Java has to escape double quotes for the same reason.

**Pull request merged**
