### PR TITLE
Add instructions on how to install CLI via MacPorts

### PR DESCRIPTION
**Pull request by breun**
I maintain the Micronaut CLI port for [MacPorts](https://www.macports.org). This PR adds instructions for installing the Micronaut CLI using MacPorts.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks. However is the port updated automatically? My concern would be if the port becomes out of date

**Comment by breun** [comment]
It's not updated automatically, but it's maintained by me based on the GitHub releases feed.

**Comment by graemerocher** [comment]
Do you have a link to the port sources or process that shows how it is updated?

**Comment by breun** [comment]
The Portfile is here: https://github.com/macports/macports-ports/blob/master/java/micronaut/Portfile

Updating it is usually only a matter of changing the version number and determining the new checksums.

**Comment by graemerocher** [comment]
Ok, would be nice if we could automate that via our release process. But I guess that is beyond the scope of this PR.

**Comment by jameskleeh** [comment]
Thank you for your contribution @breun !

**Pull request merged**
