### PR TITLE
Bump micronaut-tracing to 4.2.0

### PR DESCRIPTION
**Pull request by micronaut-build**

### CODE REVIEW

**Comment by sdelamo** [comment]
checkBom fails: 

```

> Task :bom:checkBom
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) is not a Micronaut BOM but it imports another BOM (io.opentelemetry:opentelemetry-bom:1.15.0)
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) is not a Micronaut BOM but it imports another BOM (io.opentelemetry:opentelemetry-bom-alpha:1.15.0-alpha)
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-javaagent-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-javaagent-extension-api:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-javaagent-tooling:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-muzzle:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-testing-common:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-agent-for-testing:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent:opentelemetry-javaagent-tooling-java9:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-executors-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-jdbc-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-rmi-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-tomcat:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-undertow-1.4-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-jaxrs-common-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-servlet-common-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-kafka-clients-0.11-bootstrap:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry:opentelemetry-bom:1.15.0 which doesn't belong to group io.opentelemetry.instrumentation.
BOM io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha (via io.micronaut:micronaut-bom:3.6.0-SNAPSHOT -> io.micronaut.tracing:micronaut-tracing-bom:4.2.0 -> io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.15.0-alpha) declares dependency on io.opentelemetry:opentelemetry-bom-alpha:1.15.0-alpha which doesn't belong to group io.opentelemetry.instrumentation.
```

@melix @timyates please advice

**Comment by melix** [comment]
You need to accept the fact that the opentelemetry BOM is not following our standards, like we did in the tracing module itself: https://github.com/micronaut-projects/micronaut-tracing/blob/master/tracing-bom/build.gradle#L7-L14

**Comment by sdelamo** [comment]
> You need to accept the fact that the opentelemetry BOM is not following our standards, like we did in the tracing module itself: https://github.com/micronaut-projects/micronaut-tracing/blob/master/tracing-bom/build.gradle#L7-L14

@timyates can you do this change?

**Comment by timyates** [comment]
@sdelamo @melix done in [e7f345b](https://github.com/micronaut-projects/micronaut-core/pull/7631/commits/e7f345be563febc30e3e77a22c2e1a629ada6c32) PTAL

**Review by melix — APPROVED** [review]

**Pull request merged**
