### PR TITLE
Bean introspection: store constructor arguments in a field instead of recreating the array

### PR DESCRIPTION
**Pull request by dstepanov**
This is now exposing a mutable array, not sure if it makes sense to guard it by making a copy

### CODE REVIEW

**Comment by graemerocher** [comment]
I guess creating a copy would add overhead?

**Comment by dstepanov** [comment]
Not a big one

**Comment by graemerocher** [comment]
probably best to create one in that case since could lead to weird bugs

**Comment by dstepanov** [comment]
I have added an array copy

**Pull request merged**
