### PR TITLE
Some fixes kasp for windows

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by dstepanov** [comment]
What does it fix?

**Comment by altro3** [comment]
in micronaut openapi some pathes can conains `/` symbol, windows normally understand both symbols in pathes - `\` and `/`, but when you ask FileSystem  separator java will return you `\`. 

Because of it final path can contain both symbols. Your solution works only in all places will be one of these symbols - `\` or `/`. My solution allow you use symbols `\` and `/` together. This case often happens when part of the path can be set by the user.

Second minor fix (not for windows), just more optimized code - don't need to create arrayList for empty array

**Comment by altro3** [comment]
@dstepanov Hi! What do you think about this fix?

**Comment by dstepanov** [comment]
Does it fix https://github.com/micronaut-projects/micronaut-core/issues/9670 ?

**Comment by altro3** [comment]
@dstepanov no, this fix for windows: when you set part of path with `/`, but system separator is `\`. For example, you have part of path `META-INF/swagger`, but system separator is `\` (windows) - in this case you can't correct split `META-INF/swagger`. My solution fixed it

**Comment by dstepanov** [comment]
Ok, thanks! Are you going to the other meta-inf issue?

**Comment by altro3** [comment]
@dstepanov I have tried. But I still don't understand why the directory is not correct. I see that other micronaut files are created correctly, but in my case, open api files for some reason try to be created in the daemon directory. I tried to debug the code to figure out what's wrong - but I still can't figure it out :-(

**Pull request merged**
