### PR TITLE
Add Micronaut Hibernate JCache configuration

### PR DESCRIPTION
**Pull request by marceloverdijk**
This `hibernate-jcache` configuration is responsible for:
* adding the `org.hibernate:hibernate-jcache` dependency
* Binds the JSR-107 `CacheManager` to Hibernate (if `CacheManager` exists

To share the Hibernate version used by `hibernate-jpa` and `hibernate-jcache` configuration I moved the Hibernate version to `gradle.properties` and added Hibernate to `dependencyVersions` in the build file.

### CODE REVIEW

**Comment by marceloverdijk** [comment]
Yes I was thinking of that myself as well.

How should the user then add the `org.hibernate:hibernate-jcache` dependency?
Off course manually, but I'm thinking of the version of the dep here. It should be the same as hibernate dep itself. Has Micronaut something for this?

**Comment by graemerocher** [comment]
They can simply declare it as `org.hibernate:hibernate-jcache` (without the version) then it will use the version you specified in the BOM entry

**Comment by marceloverdijk** [comment]
Great, shall I combine them? I can do it later today.

**Comment by graemerocher** [comment]
Sure no problem. Thanks

**Comment by marceloverdijk** [comment]
@graemerocher I've updated the PR and moved the cache binder to the `hibernate-jpa` module.

**Comment by graemerocher** [comment]
@marceloverdijk thanks, the only other thing I am thinking is maybe you may want different `CacheManager` beans for different JPA configurations, current implementation limits to a single bean for all JPA entity managers

**Comment by marceloverdijk** [comment]
@graemerocher correct, it currently only uses the same cache manager instance.
Do you have a suggestion how to make that more flexible?

**Comment by graemerocher** [comment]
@marceloverdijk I will give it some thought

**Comment by marceloverdijk** [comment]
@graemerocher ok, let me know if I can help with anything.

PS: I added the `org.hibernate.cache.jcache.ConfigSettings` to the required classes (on the `io.micronaut.configuration.hibernate.jpa.jcache` package level). This was needed after merging the code to the `hibernate-jpa` configuration.

**Pull request merged**
