### PR TITLE
Oneof features & Lang flag

### PR DESCRIPTION
**Pull request by ZacharyKlein**
Added support for OneOf and DefaultOneOf features. Immediate use case is to allow the use of `application-[lang]` features so that Groovy projects have an `Application.groovy` class, Kotlin projects have a `Application.kt` class. Select `defaultOneOf` if no selection was made. Warn if multiple `oneOf` features are selected,.

Example:

```
description: The service profile
features:
    defaultOneOf: application-java
    oneOf:
        - application-java
        - application-groovy
        - application-kotlin
```

Also added a `-lang` flag which services as a shortcut to specifying the `application-[lang]` feature.

```
> mn create-app my-groovy-app -lang groovy //same as -features application-groovy 
```

Updated the docs to reflect the new CLI usage.

Corresponding PR in the profiles project: https://github.com/micronaut-projects/micronaut-profiles/pull/32

### CODE REVIEW

**Comment by jameskleeh** [comment]
I think instead of defaultOneOf, each oneOf should have a precedence. If multiple are selected, the one with the highest precedence wins

**Comment by jameskleeh** [comment]
I also don't see the need for the lang flag if each of the application- features are a dependency of their respective language features

**Comment by ZacharyKlein** [comment]
@jameskleeh `-lang` flag was a suggestion from Graeme, I think it's useful shortcut and consistent with the behavior of `create-function`. The `application` features are not dependencies of the language features. Only the other way around.

For example, you could create a Java project and add the Groovy language support: 

```
> mn create-app my-java-app -features groovy
```

The project will have an `Application.java` class but will also have Groovy support.

**Comment by ZacharyKlein** [comment]
@jameskleeh I'm okay with the order of precedence, but it seemed a bit complicated and I don't really have a use for it at this point. Right now the only purpose of the `defaultOneOf` is to make sure that at least one is chosen, with Java is the default.  In the case of `application-` creating a project with `application-groovy` and `application-java` doesn't make sense, so issuing a warning makes more sense to me than silently ignoring the others.

**Comment by jameskleeh** [comment]
Having both `-features groovy` and `-lang groovy` is confusing to say the least. 

if someone says they want the groovy feature, it makes sense to me that the Application class should be in Groovy. Same logic goes for Kotlin. If the language features depend on their application- features, then we can apply logic as to which one should be included based on their precedence.

`create-app -features groovy` => both application-java and application-groovy will be there, however groovy has precedence over java. Same logic for kotlin.

`create-app -features groovy,kotlin` => all application-features will be there and the one with the highest precedence will be applied (most likely groovy in this case)

What is the issue with that approach? No lang flag is needed and no defaultOneOf is needed.

**Comment by ZacharyKlein** [comment]
I don't think it's confusing, they mean different things. `create-app -lang groovy` means I want a Groovy app. `create-app -features groovy` means I want Groovy support in my project. 

That being said, if we want to make the `-features` flag behave the way you describe I'm fine with that, it's not a major change.  The precedence change makes sense to me,  although IMHO it's not really any simpler than having a "default" property.

**Comment by jameskleeh** [comment]
You're right in that it isn't simpler, but it is better as it allows more control over which feature is chosen.

**Comment by ZacharyKlein** [comment]
Replaced with PR #249

**Comment by graemerocher** [comment]
One thing I would say is that not having a `lang` flag is inconsistent with the rest of the commands (`create-function`, `create-controller` etc.) which may in fact be confusing by itself

**Comment by ZacharyKlein** [comment]
@graemerocher James and I discussed this offline, and what we decided was to keep the `lang`, but make it function simply as a shortcut for choosing the existing Groovy/Java/Kotlin features. So whether you choose a language using the `lang` flag or `features` flag, you will get an `Application` class in the chosen language. If you do not choose a language, the default is Java.

**Comment by ZacharyKlein** [comment]
@graemerocher please see the new PR #249

**Pull request closed without merging**
