### PR TITLE
adds support for pagination in GetParametersByPath for AWSParameterStore

### PR DESCRIPTION
**Pull request by xoiram**
Attempt at fixing https://github.com/micronaut-projects/micronaut-core/issues/2296

It will keep calling AWS as long as the parameter store returns a "nextToken". Should this be limited in any way? A configurable limit of how many pages it will attempt at paginating?

Also added some TRACE logging to AWSParameterStoreConfigClient to ease what parameters are retrieved from paramstore.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks, will review soon. Would you be able to target the `1.2.x` branch for this pull request?

**Comment by xoiram** [comment]
That didn't feel to good with a force push and all, but I've changed the base of the PR and targeted 1.2.x instead. Hopefully that was the way to do it, if not I can create a new PR straight from 1.2.x.

**Comment by graemerocher** [comment]
Looks good. Thanks we will review shortly.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
