### PR TITLE
Moving random port check outside of bind method

### PR DESCRIPTION
**Pull request by zendern**
I cant seem to get this to fail on my travis ci instance in the way its failing on master. 

Master
https://travis-ci.com/zendern/micronaut-core/builds/126608701

Reverted dual protocol change
https://travis-ci.com/zendern/micronaut-core/builds/126600426

This change to only calculate random port once
https://travis-ci.com/zendern/micronaut-core/builds/126606379

### CODE REVIEW

**Comment by zendern** [comment]
Force pushing a few times to see if its always `ValidateAnnotationMetadataSpec` that fails now.

**Comment by graemerocher** [comment]
@zendern might be a new test failure since we haven't had a clean build for a while

**Comment by zendern** [comment]
@graemerocher that would make sense. Im going to force push this change a few times throughout the day to make sure it does in fact fix it. It might be too early in the day for port contention?? maybe not?? Validating it has not been the easiest thing locally and like i said above for whatever reason i could not get it to fail with port contention on "my version" of travis ci. Second PR failure was again `ValidateAnnotationMetadataSpec` so so far looking good, bad but good :)

**Comment by zendern** [comment]
3rd time was green. One more time and if it works this time I'll change this to a real boy PR

**Comment by zendern** [comment]
Finally after all of this i think i have found the issue. Working on a real test now to validate it but long story short if the server had port contention and had to rebind it would but then if the code under test used the getURL() or getPort() it would be the original port that had contention and not the port that was actually used. Going to close this and will open a new once I have tested it and validated it was fixed.

**Pull request closed without merging**
