### PR TITLE
Gradle upgrade

### PR DESCRIPTION
**Pull request by zendern**
WIP : To upgrade to gradle 5.6.2. 

Notes so far: 
* Micronaut-test junit dependency was not resolving correctly, hardcoded deps for junit-api for now. (https://github.com/micronaut-projects/micronaut-core/pull/2128/commits/5aa86aeb45cc12082f4ab5df784ee0b8687d66c4)

### CODE REVIEW

**Comment by zendern** [comment]
Getting close. Post commit https://github.com/micronaut-projects/micronaut-core/pull/2128/commits/5aa86aeb45cc12082f4ab5df784ee0b8687d66c4 the code compiles but running the tests sees this error in the discovery-client. Will continue to work through it and move onto publishing once the tests all pass. 

``` o.micronaut.discovery.eureka.EurekaMockBasicAuthSpec > test authentication works FAILED
    io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [router] of class: io.micronaut.http.server.netty.NettyHttpServer

    Message: No bean of type [io.micronaut.web.router.Router] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
    Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,Optional serverSslBuilder,List outboundHandlers,EventLoopGroupFactory eventLoopGroupFactory,HttpCompressionStrategy httpCompressionStrategy)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:998)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2279)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1948)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1923)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:584)
        at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:242)
        at io.micronaut.context.ApplicationContext.run(ApplicationContext.java:218)
        at io.micronaut.discovery.eureka.EurekaMockBasicAuthSpec.test authentication works(EurekaMockBasicAuthSpec.groovy:36)```

**Comment by graemerocher** [comment]
@zendern would seem to indicate that bean definitions are not being generated?

**Comment by zendern** [comment]
Running into this now in discovery-client tests.

```Caused by:
        java.lang.NoClassDefFoundError: io/micronaut/caffeine/cache/Cache
            at io.micronaut.context.AbstractBeanDefinition.getTypeArguments(AbstractBeanDefinition.java:211)
            at io.micronaut.inject.DelegatingBeanDefinition.getTypeArguments(DelegatingBeanDefinition.java:167)
            at io.micronaut.inject.BeanDefinition.getTypeArguments(BeanDefinition.java:193)
            at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:205)
            at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:217)
            at io.micronaut.context.DefaultBeanContext$BeanKey.<init>(DefaultBeanContext.java:2840)
            at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1501)
            at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2604)
            at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2524)
            at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:882)
            at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1096)
            at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1734)
            at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1091)
            at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:966)
            at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1560)
            ... 19 more```

Looking a little more i see this was changed a few days ago by @jameskleeh maybe that broke things?? I dont see a clean master build and the last master build had an issue resolving that cache-core jar. 
https://github.com/micronaut-projects/micronaut-cache/commit/28041715b5d4b1900c97c09ccfe75b10108bff82

**Comment by zendern** [comment]
Rebased with master and now all caching test issues i was seeing are all fixed. Now to work through publishing.

**Comment by zendern** [comment]
Getting real close. Diff still shows that the micronaut-core jar is not the same or close. Appears the shadowJar plugin is not working as expected.

**Comment by jameskleeh** [comment]
@zendern Is this something you plan to continue taking forward?

**Comment by zendern** [comment]
> @zendern Is this something you plan to continue taking forward?

I'd like to but I've still yet figured out why the shadow jar is behaving the way it is. There was a suggestion on the issue to roll back to 4.x release of that plugin but I've yet to get that to work either.

**Comment by graemerocher** [comment]
Will have a look shortly....

**Comment by zendern** [comment]
pkg-diff has been attached. [pkgdiff_reports.zip](https://github.com/micronaut-projects/micronaut-core/files/3834414/pkgdiff_reports.zip)

Breakdown of differences that mean something. Most other differences in the pom files for example are ordering. 

- `micronaut-cli` - has no dependencies. I believe this is fine since Im not sure of the usecase where you would depend on cli and need its dependencies. The zip distribution unzips and works as expected so thus the this is fine comment.
- `micronaut-bom` - no longer has variables and sets everything as compile scope. I believe this is fine as well just a difference between plugin generated and what we used to do. bom also no longer outputs sources/javadoc jar..... is that ok??

----

Couple things : 

1. `pTML` goal now works but it regressed and now `check` doesn't compile
2. publishing.gradle needs some love after its been fiddled now to use Maven

**Comment by zendern** [comment]
Getting really close now.  I was able to get both `check` and `pTML` to run successfully. Diff is looking better post the publishing tweaks. cc @graemerocher if you started to look at it here is the latest.

- `micronaut-cli` is still missing deps but again i think this is probably fine. They could be added back if needed
- `micronaut-bom` generated pom looks to be referencing the non `micronaut-*` prefixed libraries. So this will need to be looked into. I believe its since we include the projects but it doesn't know how to translate those to the maven coordinates with the way we are doing it. See here 
image


[pkgdiff_reports.zip](https://github.com/micronaut-projects/micronaut-core/files/3836435/pkgdiff_reports.zip)

**Comment by zendern** [comment]
Will deal with the merge conflicts later today hopefully.

**Comment by graemerocher** [comment]
I think the variables are needed. Since that is how the consumer of the BOM can override which version to use.

**Comment by zendern** [comment]
Latest diff based on 53d10cbdb8c278f35a7029d0082d883dae7bb846. Both pTML and check work locally. What's fun is now travis is blowing up with a core dump. 

[pkgdiff_reports.zip](https://github.com/micronaut-projects/micronaut-core/files/3853750/pkgdiff_reports.zip)

**Comment by zendern** [comment]
Core dump stack is as follows. 

```Stack: [0x00007fd60d390000,0x00007fd60d491000],  sp=0x00007fd60d48a698,  free space=1001k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x1552ad]
C  [libzip.so+0x12c7f]  ZIP_GetEntry2+0xff
C  [libzip.so+0x3ec0]  Java_java_util_zip_ZipFile_getEntry+0xf0
J 221  java.util.zip.ZipFile.getEntry(J[BZ)J (0 bytes) @ 0x00007fd617d7db8e [0x00007fd617d7dac0+0xce]
J 3622 C2 java.util.zip.ZipFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (101 bytes) @ 0x00007fd61862a1c4 [0x00007fd618629e60+0x364]
J 767 C2 java.util.jar.JarFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry; (22 bytes) @ 0x00007fd617f00498 [0x00007fd617f00460+0x38]
j  sun.net.www.protocol.jar.URLJarFile.getEntry(Ljava/lang/String;)Ljava/util/zip/ZipEntry;+2
j  sun.net.www.protocol.jar.JarURLConnection.connect()V+62
j  sun.net.www.protocol.jar.JarURLConnection.getInputStream()Ljava/io/InputStream;+1
j  java.net.URL.openStream()Ljava/io/InputStream;+4
j  java.util.ServiceLoader.parse(Ljava/lang/Class;Ljava/net/URL;)Ljava/util/Iterator;+15
j  java.util.ServiceLoader.access$200(Ljava/util/ServiceLoader;Ljava/lang/Class;Ljava/net/URL;)Ljava/util/Iterator;+3
j  java.util.ServiceLoader$LazyIterator.hasNextService()Z+140
j  java.util.ServiceLoader$LazyIterator.hasNext()Z+11
j  java.util.ServiceLoader$1.hasNext()Z+21
j  io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.writeConfigurationMetadata()V+29
j  io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.process(Ljava/util/Set;Ljavax/annotation/processing/RoundEnvironment;)Z+203
j  org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(Ljava/util/Set;Ljavax/annotation/processing/RoundEnvironment;)Z+6
j  org.gradle.api.internal.tasks.compile.processing.DynamicProcessor.process(Ljava/util/Set;Ljavax/annotation/processing/RoundEnvironment;)Z+16
j  org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(Ljava/util/Set;Ljavax/annotation/processing/RoundEnvironment;)Z+6```

**Comment by zendern** [comment]
I found this https://issues.gradle.org/browse/GRADLE-3370 ....although not exactly the same I think something similar is what is going on. The new version of gradle is holding onto a jar file that at compile time micronaut is attempting to write out to. In commit c42b845 the thing that made travis no longer core dump was `-Dsun.zip.disableMemoryMapping=true`. Build is still not happy but not core dumping and still different than local. Hopefully will find time this weekend to dig a little more.

**Comment by graemerocher** [comment]
@zendern I took a look at the progress. Thanks for looking into this. Something is very broken though, possibly in Gradle. It seems that Gradle is locking some of the JAR files that are produced as part of the build and they then cannot be read from another subprojects that use these produced JAR files on the annotation processor classpath. 

Using `-Dsun.zip.disableMemoryMapping=true` is a hack around that, but it then manifests again later in the build where you can see warnings like:

```
warning: Unable to load ConfigurationMetadataWriter due to : io.micronaut.inject.configuration.ConfigurationMetadataWriter: Error reading configuration file
```

The tests are failing because the type element visitors that generate introspections are failing to load which are loaded via service loader:

```java
       SoftServiceLoader<TypeElementVisitor> serviceLoader = SoftServiceLoader.load(TypeElementVisitor.class, getClass().getClassLoader());
    ...
```

It seems that since these annotation processors are part of the same project, Gradle is locking the JARs that contain the annotation processors and preventing the classes within them from being used somehow. I don't understand enough about what Gradle is doing but this is a problem for taking this upgrade forward.

I also tried with Gradle 6.0.1 and see the same behaviour.

@oehme @melix Do you have any idea what could be going on here? Why `-Dsun.zip.disableMemoryMapping=true` is needed and why Gradle 5.x and 6.x is locking produced JAR files so they cannot be re-read in other subprojects?

**Comment by graemerocher** [comment]
I reported an issue to Gradle since I don't know how to advance this as Gradle seems fundamentally broken for our use case https://github.com/gradle/gradle/issues/11619

**Comment by graemerocher** [comment]
Finally got the changes merged. Thanks for starting the work on this

**Pull request closed without merging**
