### PR TITLE
Fix mutated metadata being cleared before it was written in Groovy classes

### LINKED ISSUE #6744: Error compiling Data JDBC interface
### Expected Behavior

Micronaut Data JDBC applications should compile.

### Actual Behaviour

All the Data JDBC test applications in GraalVM CI have failed during compilation today with the error:

```
> Task :compileJava FAILED
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
error: Unable to implement Repository method: PetRepository.update(Object entity). No value available for annotation member @io.micronaut.data.annotation.AutoPopulated[updateable] of type: class java.lang.Boolean
Note: Creating bean classes for 7 type elements
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
1 error
2 warnings
```

They worked yesterday and nothing has changed in Micronaut Data so the error should be here in core.

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout 3.2.x_h2`
- `./gradlew compileJava`

### Environment Information

Linux Mint 20.3
JDK 8

### Example Application

_No response_

### Version

3.2.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by jameskleeh**
@dstepanov Please give this a try with data

### CODE REVIEW

**Comment by dstepanov** [comment]
It fixes runtime errors but there are still some compile problems with `getRequiredValue` not returning default values. You can reproduce them by reverting modified Java files.

**Comment by jameskleeh** [comment]
Right because the code to retrieve the default values only looks at the runtime source of that information. If we should not leak the compile time data to runtime, which was the cause of the original issue, then either default value data will not be available at compile time or the methods to get the defaults needs to look at the compile time defaults.

**Comment by dstepanov** [comment]
We have code that relies on compile-time default values so we need to fix it somehow 🤔

**Comment by graemerocher** [comment]
@jameskleeh can you link to the original issue, the original PR that broke everything to solve that issue and so on. None of the PRs that tried to mitigate this issue include any references to the issues they solve so it is hard to trace back the history of the issue

**Comment by dstepanov** [comment]
The problem in 3.1.4 was caused by https://github.com/micronaut-projects/micronaut-core/pull/6455 and the fix that broke more stuff https://github.com/micronaut-projects/micronaut-core/pull/6734

**Comment by jameskleeh** [comment]
@graemerocher The original issue is https://github.com/micronaut-projects/micronaut-core/issues/6433

The fix I created for that was https://github.com/micronaut-projects/micronaut-core/pull/6455 which basically reused the runtime cache at compile time. Because there was a singular cache the data from Groovy was leaking to Java. Groovy is creating proxies for annotation instances and the Java annotation metadata stuff is not designed to handle them.

I tried to solve that issue by clearing the cache after compilation but that caused lots of issues with compiling code at runtime in our tests, so it was evident the runtime cache could not be cleared.

The next step I took was to separate the compile time from runtime default value caches so the compile time cache could be cleared after compilation preventing one languages values leaking to another. https://github.com/micronaut-projects/micronaut-core/pull/6734

Unfortunately I mistakenly cleared the mutated metadata too early for Groovy so that caused runtime issues of mutated metadata being missing. It also had the side effect of annotation default values not being available at compile time because the metadata only looks at the runtime cache and we aren't populating it

**Comment by dstepanov** [comment]
I can confirm these changes fix the problems in Micronaut Data

**Pull request merged**
