### PR TITLE
Check for multi-valued headers in a header map that encodes headers as strings

### PR DESCRIPTION
**Pull request by BenTels**
This is a suggested fix for issue #5425 , which is currently closed but is not fixed.

### CODE REVIEW

**Comment by dstepanov** [comment]
Would you be able to add a test to one of the existing WS specs like `PojoWebSocketSpec` that replicated the problem?

**Comment by BenTels** [comment]
> Would you be able to add a test to one of the existing WS specs like `PojoWebSocketSpec` that replicated the problem?

Yeah, sort of...

I've added a Spock version of a very nasty, low-level test I set up when working on the fix idea. However, I cannot run it because the test suite doesn't run on my machine. It wants to copy a file .../micronaut-core/http-server-netty/src/test/resources/public/??????-0.0.yml which sort of doesn't give me enough information to fix it. Still, I hope it helps...

By the way, on a totally unrelated note, my fix doesn't correct for the fact that the value of Upgrade might actually also be multi-valued. That will most likely not occur, but theoretically....

And on another, totally unrelated, note: have you guys taken into account that in HTTP/2 the WebSocket start doesn't use the Upgrade header?

**Comment by dstepanov** [comment]
You should be able to send a request to the running test server without mocking anything

**Comment by BenTels** [comment]
Like I said, I wouldn't know -- the test suite won't even start on my system. 

In any case, the problem is in the way Netty handles headers. The Connection header isn't parsed at all, so if you look for a Connection header with a value of "upgrade", you won't find it; in the case of Firefox, the value will be "keep-alive, Upgrade".

**Comment by BenTels** [comment]
Sorry, but I give up. I figured out what the problem was in the processTestResources task (it's the yml file in the http-netty-server test resources with the Japanese name; gradle in my environment doesn't play well with UTF-16 filenames). With a lot of massaging and skipping of tests I can get the whole source tree to compile and I can verify the test I wrote. But I can't get the test with the test server in PojoWebSocketSpec working, it fails to start with a failure to inject a bean of type io.micronaut.http.server.codec.TextStreamCodec .

The test I created may be ugly, but it proves the point. I'm not going to get any further than that.

**Comment by dstepanov** [comment]
No worries, I will try to add the test

**Comment by jameskleeh** [comment]
I fixed this by reverting to the code that was in 2.4.x

**Pull request closed without merging**
