### PR TITLE
Add jaxrs-server-security to catalog

### PR DESCRIPTION
**Pull request by pgressa**
This one is missing from the https://github.com/micronaut-projects/micronaut-jaxrs

### CODE REVIEW

**Comment by graemerocher** [comment]
Ideally in the future the module should publish a BOM

**Comment by pgressa** [comment]
Maybe we should have automatically add bom support to all projects while working on this new build plugins. But for now, the launcher with jaxrs-security just fails since it doesn't have proper version set.

**Comment by melix** [comment]
I'm not sure adding a BOM to all modules makes sense. It probably only makes sense for multi-module projects. Note that we can also improve our BOMs for Gradle, to enable version alignment.

**Review by graemerocher — APPROVED** [review]

**Comment by pgressa** [comment]
> I'm not sure adding a BOM to all modules makes sense. It probably only makes sense for multi-module projects. Note that we can also improve our BOMs for Gradle, to enable version alignment.

Yes, I was referring to multi-module projects only.

**Pull request merged**
