### PR TITLE
Implement enum constant in kotlin element factory

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by altro3** [comment]
@dstepanov Hi! Could you help with this change? Without it we can't use micronaut-openapi with KSP for enums. But I did something wrong and now I have this exception in test:

изображение

Need help!

**Comment by dstepanov** [comment]
Can you please include only necessary changes? The other once please add in another PR

**Comment by altro3** [comment]
@dstepanov i think, it's better, if merge all changes from branch 4.1.x to 4.2.x. and after it you will see only my changes.

I don't know another way to sync new branch in fork. I need to create branch with the same name - 4.2.x, but I need to start this branch from 4.1.x. And in original repo ypu still didn't merge branch 4.1.x. Jsut merge 4.1.x to 4.2.x

**Comment by altro3** [comment]
Continue here: https://github.com/micronaut-projects/micronaut-core/pull/9774

**Pull request closed without merging**
