### PR TITLE
Hyphenate should replace spaces as well

### LINKED ISSUE #2564: YAML Map Keys are read incorrectly
When try to read map object from application.yml file with Keys containing spaces and starting with uppercase then keys are converted to kebab notation. But if root of the map is defined with Uppercase then everything works fine. Is it Micronaut default behaviour or is it a bug?

Below code gives Map with ["Key with space":[ "some more key", "some other key" ]]
```
Test:
  Key with space:
    - some more key
       some other key
```

But below code gives Map with ["k-ey with space":[ "some more key", "some other key" ]]

```
test:
  Key with space:
    - some more key
       some other key
```

Im not able to find documentation for it.

### PR DESCRIPTION
**Pull request by jameskleeh**
Fixes #2564

### CODE REVIEW

**Comment by graemerocher** [comment]
Any performance implications for this change?

**Comment by jameskleeh** [comment]
@graemerocher Replacing via regex should be slightly slower but i don't think this warrants custom logic to achieve better perf

**Comment by graemerocher** [comment]
I think one thing that could help is replacing the call with a precompiled `Pattern` since using `replaceAll(..)` directly will recompile the regex `Pattern` for each call

**Comment by jameskleeh** [comment]
@graemerocher Good point - done

**Pull request merged**
