### PR TITLE
Use the current JDK for testing, but 17 for building

### PR DESCRIPTION
**Pull request by timyates**
Previously we added a PR to run (and compile) under Java 21

https://github.com/micronaut-projects/micronaut-core/pull/9978

This did not work as expected, as in reality this is configuring under the current JDK, but compilation is being done by Java 17 from the ToolChain set up by the micronaut-build plugin.

This PR modifies the test tasks to run on the JDK that is used to start the build.

But all compilation will be done via Java 17 from the toolchain.

I believe this supersedes both https://github.com/micronaut-projects/micronaut-core/pull/9978 and https://github.com/micronaut-projects/micronaut-core/pull/9985

### CODE REVIEW

**Review by melix — APPROVED** [review]

**Comment by dstepanov** [comment]
There is no need for the open hack?

**Comment by timyates** [comment]
~~No, because all of the compilation is done under 17, but the tests are executed under Java 21 (on the 21 pipelines)~~

@dstepanov I'm changing my answer 😉 We do need the open hack, as no matter what I try, I cannot get a kotlin daemon to start with the toolchain JDK

Added it in https://github.com/micronaut-projects/micronaut-core/pull/9989/commits/c60ac06d08f482047708faab7ed11daa0b2a3d1e

**Comment by timyates** [comment]
@yawkat  do the test changes I had to make make sense?  I think with 21 we get an extra executer

**Comment by timyates** [comment]
[Java 21 build](https://ge.micronaut.io/s/kt7cfngshluhk/timeline?details=kzblhtg2plsuy&name=test&outcome=success):

image

[Java 17 build](https://ge.micronaut.io/s/tovaasx6mhjwy/timeline?details=kzblhtg2plsuy&name=test&outcome=success):

image

**Review by sdelamo — APPROVED** [review]

**Review by dstepanov — APPROVED** [review]

**Pull request merged**
