### PR TITLE
Update netty to 4.1.107.Final

### PR DESCRIPTION
**Pull request by yawkat**

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
why 3.8.x and not 3.10.x? It seems the sonar task fails.

**Comment by yawkat** [comment]
we have an internal customer on 3.8. we probably dont need a release of 3.8.x but i just want to make sure it works

**Review by graemerocher — APPROVED** [review]

**Comment by sdelamo** [comment]
I will try to make the build pass.

**Comment by yawkat** [comment]
thanks!

**Pull request merged**
