### PR TITLE
#2366 log a warning if a specified property file fails to load

### PR DESCRIPTION
**Pull request by mickoallen**

### CODE REVIEW

**Comment by jameskleeh** [comment]
We appreciate the PR. I think the idea of the issue was to prevent the application from starting if a file was not found. This PR simply just logs the error. Can you update the PR to shut down the application? Also can you please sign the CLA?

**Comment by mickoallen** [comment]
> We appreciate the PR. I think the idea of the issue was to prevent the application from starting if a file was not found. This PR simply just logs the error. Can you update the PR to shut down the application? Also can you please sign the CLA?

I was mildly concerned of breaking existing applications that are currently configured incorrectly (and starting fine). A warning provides feedback that something is misconfigured without potential breakage.

I'm happy to change it though.

**Comment by jameskleeh** [comment]
@graemerocher Thoughts on where this change should be made? 1.3 or 2.0 ?

**Comment by graemerocher** [comment]
think it should go into 1.3, seems like a bug to me

**Comment by jameskleeh** [comment]
I merged the warning log into 1.2.x and we can make it fail for 2.0

**Pull request closed without merging**
