### PR TITLE
Connect ttl changes

### PR DESCRIPTION
**Pull request by SamathaUppula**

### CODE REVIEW

**Comment by SamathaUppula** [comment]
Issue link https://github.com/micronaut-projects/micronaut-core/issues/2070

**Comment by graemerocher** [comment]
@SamathaUppula Thanks, can you sign the CLA please. Also you may need to sign with the CLA with the account you did the commits with which differs from the Github account you are using. Thanks.

**Comment by SamathaUppula** [comment]
@graemerocher I have signed several times till now. But I don't know why still this page is showing I am not signed.

**Comment by graemerocher** [comment]
Previously the reason was that you did the commits with a different account to the one which you submitted the PR with. This seems to have been rectified. Thanks we will review soon.

**Comment by SamathaUppula** [comment]
@graemerocher This feature is very important for us as are getting many productions performance issues which are related to connections. Please consider it for quicker review. Thanks :-)

**Comment by graemerocher** [comment]
@SamathaUppula Currently this change is targeting `master` if you wish it to be included in a future 1.2.x release could you rebase the PR to target 1.2.x

Thank you.

**Comment by SamathaUppula** [comment]
@graemerocher sure

**Comment by graemerocher** [comment]
Sorry you have changed the version in `gradle.properties` to 1.2.x but you have not rebased the PR. It is still targeting the `master` branch. When creating the PR you must select the `1.2.x` branch instead of `master`. You will likely need to close this PR and create a new one.

**Comment by SamathaUppula** [comment]
Will open another one

**Pull request closed without merging**
