### PR TITLE
use aws-bom

### PR DESCRIPTION
**Pull request by pgressa**

### CODE REVIEW

**Comment by sdelamo** [comment]
relates to https://github.com/micronaut-projects/micronaut-aws/pull/963

**Comment by sdelamo** [comment]
This PR https://github.com/micronaut-projects/micronaut-core/pull/5146/files needs to be merged before this one

**Comment by jameskleeh** [comment]
@sdelamo That other PR is targeting 2.5.x, so why does that need to be merged before this one that targets 2.4.x? The other change wouldn't be in this branch

**Comment by sdelamo** [comment]
This PR should target 2.5.x

**Comment by jameskleeh** [comment]
@pgressa Changing the target to 2.5.x is bringing in a bunch of old commits. Try rebasing the branch on top of 2.5.x

**Comment by pgressa** [comment]
@jameskleeh done

**Pull request merged**
