### PR TITLE
Fixes URITemplate to parse query param

### LINKED ISSUE #6246: UriBuilder/UriTemplate.PATTERN_FULL_URI: Query Parameters Parsed as Part of Path
### Expected Behavior

When using `UriBuilder` to add query parameters to a URI that already has query parameters, the RegEx within `UriTemplate.PATTERN_FULL_URI` should recognize the query parameters as query parameters.

For example, `UriBuilder.of("https://google.com/search?q=TESTING")` should interpret a `path` of `"/search"` and a `queryParams`  with the key/value pair of `[q: "TESTING"]`.

### Actual Behaviour

`DefaultUriBuilder(CharSequence uri)`, calling the PATTERN_FULL_URI matcher, returns the query portion of the URI as part of the path. 

For example, `UriBuilder.of("https://google.com/search?q=TESTING")` interprets a `path` of "/search?q=TESTING" and an empty map for `queryParams`. 

### Steps To Reproduce

1. Build the following:

```java
package example;

import io.micronaut.http.uri.UriBuilder;

public class Application {

    public static void main(String[] args) {
        String testUri = "https://google.com/search?q=Thisisatest";

        UriBuilder builder = UriBuilder.of(testUri);

        builder.queryParam("bad_param", "ThisIsInvalid");

        System.out.println(builder.toString());
    }
}
```
2. (Optional) Break at line 12 (`builder.queryParam(<snip>`) and observe empty map at `builder.queryParams`

3. Observe two question marks in results:
```
https://google.com/search?q=Thisisatest?bad_param=ThisIsInvalid
```

### Environment Information

Operating System: Windows 10 Version 20H2, Build 19042 (x86_64)
Java Version: 1.8

### Example Application

_No response_

### Version

3.0.2

### PR DESCRIPTION
**Pull request by ashishkujoy**
closes: #6246

Signed-off-by: ashishku <ashishku@thoughtworks.com>

### CODE REVIEW

**Comment by jameskleeh** [comment]
Looks like this is causing a test failure in `UriTemplateSpec`

**Comment by ashishkujoy** [comment]
> Looks like this is causing a test failure in `UriTemplateSpec`

In my first change, I missed considering cases. 
In this change i corrected regex for query param. 
Still trying to fix regex for path. So far it is matching anything before `#`, `?` need to update it also consider anything before `{?` .

**Comment by ashishkujoy** [comment]
Not able to make any further, stuck with regex for path to match anything before `{?`

**Comment by ashishkujoy** [comment]
Closing this, as I am not able to make any further progress.

**Pull request closed without merging**
