### PR TITLE
Allow to use @Around and @Introduction(interfaces) together

### PR DESCRIPTION
**Pull request by dstepanov**
I have a use case where I want to implement an interface and also intercept all the methods, at the moment is not possible.

### CODE REVIEW

**Comment by dstepanov** [comment]
@jameskleeh @graemerocher What do you think about this one? It's a small change with a big potential 😄

**Comment by graemerocher** [comment]
looks good to me. @jameskleeh ?

**Comment by jameskleeh** [comment]
This seems like it would only work if the `@Type` is the same. If you had a different interceptor for around and introduction I think only one of them would be invoked because the annotation specified later would override the value for `@Type`. I'm having trouble understanding the use case as well.

**Comment by graemerocher** [comment]
seems like the test is using different interceptors unless I am missing something

**Comment by dstepanov** [comment]
@jameskleeh I have updated the test to show that different interceptors are invoked.

Use-case is to implement a proxy, we need to interceptor for all the methods and we want to introduce a new interface that provides some functionality related to the proxy implementation.

**Comment by dstepanov** [comment]
@jameskleeh @graemerocher Can this one make to 2.1.0?

**Pull request merged**
