### PR TITLE
Small bean context perf improvement

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by graemerocher** [comment]
Seems to break stuff

**Comment by dstepanov** [comment]
Seems fine now

**Comment by graemerocher** [comment]
So how much does it improve in terms of perf?

**Comment by dstepanov** [comment]
Not sure really, but I noticed that we have compile time info if the bean is iterable so we don't need to check annotations being present.

**Comment by graemerocher** [comment]
Ok let's wait until after 3.1 for this and do more testing since I want to avoid regression

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
