### PR TITLE
Migrate discovery-client to an external project

### PR DESCRIPTION
**Pull request by graemerocher**
New project located at https://github.com/micronaut-projects/micronaut-discovery-client

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Can we take the opportunity to split the modules so that service discovery and distributed configuration goes in 2 different modules?

**Comment by graemerocher** [comment]
@alvarosanchez I think that would be a good idea for the 2.1.x line, for 2.0.x we should keep it the same but in principal I agree. Also I would say the `compileOnly` dependency on Oracle Cloud should be moved to a separate module

**Comment by alvarosanchez** [comment]
2.1.x of core? That is what master is (or will be) soon.

In my opinion, spinning off core but keeping the same coupling might not be worth. If the structure is going to be the same for 2.0.x, you can leave the module in core.

**Comment by graemerocher** [comment]
No what I meant was 2.0.x branch of https://github.com/micronaut-projects/micronaut-discovery-client/tree/2.0.x

**Pull request merged**
