### PR TITLE
Add a way to extract the value from `JsonNode` and construct it from it

### PR DESCRIPTION
**Pull request by dstepanov**
It would be nice to have them, otherwise it's a bit complicated to do

### CODE REVIEW

**Comment by yawkat** [comment]
whats the point of this? we already have decodeArbitrary

**Comment by graemerocher** [comment]
I'm wondering that too

**Comment by dstepanov** [comment]
Micronaut Data document support is based on Micronaut Serialization. To convert an entity to a list of attributes I'm using this:
```java
    private <T> JsonNode persistAsJsonNode(T object) {
        try {
            JsonNodeEncoder encoder = JsonNodeEncoder.create();
            Argument<Object> type = (Argument<Object>) Argument.of(object.getClass());
            Serializer.EncoderContext encoderContext = serdeRegistry.newEncoderContext(null);
            final Serializer<Object> serializer = encoderContext.findSerializer(type).createSpecific(encoderContext, type);
            serializer.serialize(encoder, encoderContext, type, object);
            return encoder.getCompletedValue();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private <T> T readFromJsonNode(JsonNode tree, Argument<T> type) {
        try {
            Deserializer.DecoderContext decoderContext = serdeRegistry.newDecoderContext(null);
            final Deserializer<? extends T> deserializer = decoderContext.findDeserializer(type).createSpecific(decoderContext, type);
            return deserializer.deserialize(JsonNodeDecoder.create(tree), decoderContext, type);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

And I'm working with `JsonNode` tree.

**Comment by yawkat** [comment]
You can use JsonMapper.readValueFromTree(tree, Object.class) to go from node to Map

**Comment by dstepanov** [comment]
Is there a way to do it without injecting `JsonMapper`? Imho the methods are still useful, maybe `from` method is a bit controversial

**Comment by yawkat** [comment]
jsonnodedecoder.readArbitrary i guess

**Comment by yawkat** [comment]
JsonNodeDecoder and JsonNodeEncoder are internal in serialization though and i recently changed them with the limits PR

**Comment by dstepanov** [comment]
Looks like `toArbitrary` can be converted to use my changes

**Comment by dstepanov** [comment]
```java
private static Object toArbitrary(JsonNode node) {
        if (node.isNull()) {
            return null;
        } else if (node.isNumber()) {
            return node.getNumberValue();
        } else if (node.isBoolean()) {
            return node.getBooleanValue();
        } else if (node.isString()) {
            return node.getStringValue();
        } else if (node.isArray()) {
            List<Object> transformed = new ArrayList<>();
            for (JsonNode value : node.values()) {
                transformed.add(toArbitrary(value));
            }
            return transformed;
        } else if (node.isObject()) {
            Map<String, Object> transformed = new LinkedHashMap<>();
            for (Map.Entry<String, JsonNode> entry : node.entries()) {
                transformed.put(entry.getKey(), toArbitrary(entry.getValue()));
            }
            return transformed;
        } else {
            throw new AssertionError(node);
        }
    }
```

This can be simply replaced with `.getValue()`

**Comment by yawkat** [comment]
yea i just dont really like exposing this

**Comment by yawkat** [comment]
generally discouraged to first go to one tree type and then to another

**Comment by dstepanov** [comment]
@yawkat You don't like these changes at all?

**Comment by yawkat** [comment]
im not a fan, but i dont think it's a big deal either.

**Review by yawkat — APPROVED** [review]

**Pull request merged**
