### PR TITLE
RecoveryInterceptor performance improvement

### PR DESCRIPTION
**Pull request by dstepanov**
I have noticed RecoveryInterceptor is called for all methods, PR caches some of the extractions and is able to skip it on the next call, not sure if MethodExecutionHandle is cacheable.

The other solution would be to set some boolean into context.setAttribute indicating that there is no fallback.

Should the execution of the fallback happen in a separate thread?

### CODE REVIEW

**Comment by graemerocher** [comment]
I think an attribute makes more sense then have another global cache. I'm not sure it is possible to generalize what thread a fallback should be executed on.

**Comment by dstepanov** [comment]
Changed, maybe it would be better to always require "@Recoverable" in the future major version.

**Comment by graemerocher** [comment]
Yes I agree

**Comment by jameskleeh** [comment]
@graemerocher @dstepanov Can one of you please file an issue to track the discussion around the proposed change to require `@Recoverable`?

**Comment by dstepanov** [comment]
Created https://github.com/micronaut-projects/micronaut-core/issues/3719

**Pull request merged**
