### PR TITLE
Amazon Corretto support

### LINKED ISSUE #2628: Build Micronaut core with Amazon Corretto
Docker images are here https://hub.docker.com/_/amazoncorretto

One option is to use the official setup-java action with a custom JDK downloaded: https://github.com/sormuras/bach/blob/80347b6178bc3ca6a8d58abc929013d6c2a753f6/.github/workflows/jdks.yml#L20-L36

### PR DESCRIPTION
**Pull request by alvarosanchez**
Fixes #2628.

### CODE REVIEW

**Comment by graemerocher** [comment]
Could we run the the tests Amazon Linux instead of Ubuntu? This is what is used in the AWS environment

**Comment by graemerocher** [comment]
https://hub.docker.com/_/amazonlinux

**Comment by alvarosanchez** [comment]
I may have missed the requirement of using Amazon Linux. I'll rework the PR to use it.

**Comment by graemerocher** [comment]
It may need a custom github action that runs in a container I imagine

**Comment by alvarosanchez** [comment]
Now it's being run under Amazon Linux 2.

image

Ready to be merged.

**Comment by alvarosanchez** [comment]
@graemerocher don't merge it yet, there are tests failing because of the file encoding. Need to investigate.

**Pull request merged**
