### PR TITLE
Upgrade to Kotlin 1.6.0

### PR DESCRIPTION
**Pull request by ilopmar**
Upgrade to Kotlin 1.6.0 that supports JDK 17

### CODE REVIEW

**Comment by ilopmar** [comment]
After this is merged we need to merge https://github.com/micronaut-projects/micronaut-starter/pull/970

**Comment by ilopmar** [comment]
The tests in `inject-kotlin-test` fail with

```
  java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.openapi.util.BuildNumber$Holder
      at org.jetbrains.kotlin.com.intellij.openapi.util.BuildNumber.currentVersion(BuildNumber.java:297)
      at org.jetbrains.kotlin.com.intellij.ide.plugins.PluginManagerCore.getBuildNumber(PluginManagerCore.java:876)
      at org.jetbrains.kotlin.com.intellij.ide.plugins.PluginManagerCore.lambda$createLoadingResult$16(PluginManagerCore.java:822)
      at org.jetbrains.kotlin.com.intellij.ide.plugins.DescriptorListLoadingContext.getDefaultVersion(DescriptorListLoadingContext.java:145)
      at org.jetbrains.kotlin.com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.java:166)
      at org.jetbrains.kotlin.com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromJar(PluginDescriptorLoader.java:94)
      at org.jetbrains.kotlin.com.intellij.ide.plugins.PluginManagerCore.registerExtensionPointAndExtensions(PluginManagerCore.java:1325)
      at org.jetbrains.kotlin.com.intellij.core.CoreApplicationEnvironment.registerExtensionPointAndExtensions(CoreApplicationEnvironment.java:287)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerApplicationExtensionPointsAndExtensionsFrom(KotlinCoreEnvironment.kt:631)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:601)
      at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForTests(KotlinCoreEnvironment.kt:515)
      at io.micronaut.annotation.processing.test.KotlinCompileHelper.run0(KotlinCompileHelper.kt:126)
      at io.micronaut.annotation.processing.test.KotlinCompileHelper.run(KotlinCompileHelper.kt:68)
      at io.micronaut.annotation.processing.test.AbstractKotlinCompilerSpec.buildClassLoader(AbstractKotlinCompilerSpec.groovy:37)
      at io.micronaut.annotation.processing.test.AbstractKotlinCompilerSpec.buildBeanDefinition(AbstractKotlinCompilerSpec.groovy:90)
      at io.micronaut.annotation.processing.test.Test.build bean definition(Test.groovy:57)
```

@yawkat can you please take a look at this? :pray:

**Comment by yawkat** [comment]
if this is blocking you, you can revert a949a27c69ff00fe50fa751adf0501540aee79b2 for now, it's only a debugging help anyway. I will take a look but I suspect this needs to be rewritten

**Comment by yawkat** [comment]
actually nvm the patch is easy

**Comment by ilopmar** [comment]
Thanks Jonas, you're awesome :100:

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
