### PR TITLE
limit loadNestedJarUri calls to only embedded jar files

### PR DESCRIPTION
**Pull request by hayeskl**
Error starting server when BeanDefinitionReference was included from BOOT-INF/classes

jar:file:/Users/khayes/foobar/build/libs/foobar-0.1.jar!/BOOT-INF/classes!/META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference

### CODE REVIEW

**Comment by hayeskl** [comment]
This fixes:
#https://github.com/grails/grails-core/issues/12589

**Comment by puneetbehl** [comment]
Thank you for the pull request. Please check #7705 which might be a better alternative than checking for `.jar`.

**Comment by hayeskl** [comment]
Confirmed #7705 also fixed my issue.

**Comment by yawkat** [comment]
sorry i didnt see this PR when it was created. superseded by #7705

**Pull request closed without merging**
