### PR TITLE
Update BeanDefinitionInjectProcessor.java

### PR DESCRIPTION
**Pull request by bvella**
fix issue introduced in 8f539ac4fa2f7c6db500e213b57b9a92dffab018

### CODE REVIEW

**Comment by bvella** [comment]
I had opened issue  #1649 and submitted merge request #1650 to fix it by allowing types in error to be delayed until the next annotation processing round.

In #1650 I asked for guidance or a suggestion how to include an integration test, as this requires an annotation processor. I had a small gradle project that replicated the issue, which I can find and give you or refactor into an integration test with some guidance. 

The commit 8f539ac introduced a regression which I encountered when I upgraded from 1.2.0 to 1.2.2, because the AnnBeanElementVisitor constructor now does work which can throw PostponeToNextRoundException, hence why I moved the line in the try catch block. We can reopen #1649 and link this pr to it.

**Comment by jameskleeh** [comment]
@bvella Perhaps try adding a test for this in `test-suite-java`. You should be able to do whatever needs done there to replicate the issue

**Comment by jameskleeh** [comment]
Also if this is to target a 1.2 release this needs rebased to the 1.2.x branch

**Comment by bvella** [comment]
Ok. I will see what I can do tomorrow as it's 10:20 pm in my time zone. Cheers

**Comment by bvella** [comment]
I opened #2160 with the above changes

**Pull request closed without merging**
