### PR TITLE
Add more media types

### PR DESCRIPTION
**Pull request by altro3**
Also order them by group

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks @altro3 , can you update `MediaTypeSpec` with the new types?

**Review by graemerocher — APPROVED** [review]

**Review by sdelamo — CHANGES_REQUESTED** [review]
What new media types did you add? It is difficult to see since you mixed the reorder of the class in the same PR.

**Comment by altro3** [comment]
@sdelamo 
```
application/yang
application/x-cue
application/toml
application/rtf
application/zlib
application/zstd

text/markdown
text/css
text/javascript
text/ecmascript

image/apng
image/bmp
image/x-icon
image/tiff
image/avif
image/svg+xml
image/xbm
image/wmf
```

**Comment by graemerocher** [comment]
@altro3 pls rebase

**Comment by altro3** [comment]
@sdelamo done

**Pull request merged**
