### PR TITLE
Added custom @Request scope (PR for #1578)

### PR DESCRIPTION
**Pull request by marceloverdijk**
This PR adds a `@Request` custom scope to create a new bean instance per request.

### CODE REVIEW

**Comment by graemerocher** [comment]
Some comments:

* A filter will need to be involved that cleans up at the end of a request and removes the beans, currently it seems to be relying on GC and WeakHashMap to do bean cleanup, this is not a viable approach IMO.
* It should be named `RequestScope` and not `Request`

**Comment by jameskleeh** [comment]
@graemerocher Is it possible to know when a request is finished? You couldn't use `doOnNext(response ->` in a filter and remove the bean because the filter could be called again for error responses. You can't know if it's going to be called again or not

**Comment by jameskleeh** [comment]
Nitpick `@since 1.2` -> `@since 1.2.0`

**Comment by marceloverdijk** [comment]
@graemerocher why would you want `RequestScope` instead of `Request`? Other scopes also don't have the `Scope` suffix in the class name.

Maybe overkill, but would it be an idea to have Request events similar as the Session events?

**Comment by graemerocher** [comment]
Consistency with other frameworks. In Spring it is `RequestScope` and in JavaEE it is `RequestScoped`

**Comment by graemerocher** [comment]
@jameskleeh no they would not, a request is bound on a netty channel and not statically stored anywhere. When the channel is closed the request goes away. 

I am also unsure why this implementation is creating its own map and storing reference to the request at all since each `HttpRequest` can have attributes and what makes most sense is that the beans are simply stored a request attribute.

The only question then remains is when to call `destroyBean` because you probably want `@PreDestroy` hooks to be invoked. IMO this should take place in `NettyHttpRequest.remove(..)` which removes the request from the channel.

**Comment by marceloverdijk** [comment]
I renamed `@Request` to `@RequestScope` but I'm not sure if this PR is the right direction (looking at the comments).

**Comment by graemerocher** [comment]
Replaced by https://github.com/micronaut-projects/micronaut-core/pull/1676

**Pull request closed without merging**
