### PR TITLE
fix-cacheable-called-multiple-times

### PR DESCRIPTION
**Pull request by ikovalyov**

### CODE REVIEW

**Comment by ikovalyov** [comment]
sorry for the mess, still need to fix the same issue with publisher

**Comment by ikovalyov** [comment]
*Signed the CLA but looks like app having issues with updating status.

**Comment by graemerocher** [comment]
Regarding the CLA it is because you did the commits without an email address associated that matches your github email

**Comment by ikovalyov** [comment]
@graemerocher do I need to do something extra regarding CLA?
Thanks

**Comment by graemerocher** [comment]
Modify the commits and make sure you have configured git correctly. See https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by ikovalyov** [comment]
@graemerocher thanks, it worked

**Comment by ikovalyov** [comment]
So the idea of this MR:
When intercepter called it immediately adds completable future to the cache without waiting for results.

If new call was intercepted this cached future will be returned as result. Which means all calls will get same future as response linked to the same result.

When initial future resolved cached future will be replaced with invocation result.


Unfortunately there are some issues. If resulting type is a string then converter will convert any class to the string type. Which is avoided right now  by
```
&& !o.get().toString().contains("io.micronaut.cache.interceptor.CacheInterceptor$CompletableFutureWrapper")
```
check.

better workaround is to use internal cache for such intermediate results but it would involve more changes. Do you think it's a good idea?

Thanks.

**Comment by alvarosanchez** [comment]
@graemerocher what is the status of this?

**Comment by graemerocher** [comment]
No idea

**Comment by ilopmar** [comment]
@ikovalyov do you need to do more work on this? Please rebase master and fix conflicts...

**Comment by ikovalyov** [comment]
> @ikovalyov do you need to do more work on this? Please rebase master and fix conflicts...

ok, will work on it, thanks.

**Pull request closed without merging**
