### PR TITLE
Allow `@RequestScope` beans to get access to the request

### PR DESCRIPTION
**Pull request by jameskleeh**
The goal here is to reduce another lookup to the context holder since we already have access to the request and the bean it should not be necessary

### CODE REVIEW

**Comment by graemerocher** [comment]
I wonder if this makes sense or would it be better to allow `@Parameter HttpRequest request`? The latter allows for immutable objects

**Comment by jameskleeh** [comment]
@graemerocher To allow the request to be injected in that manner would mean it would be possible for all beans since the the custom scope has no control over the bean creation process, correct? If that is the case then I think it would lead to confusing behavior for users because it would only work in very specific use cases like `@RequestScope`. The problem is that it would work sometimes in other scenarios.

**Comment by graemerocher** [comment]
True. I guess this is ok then.

**Comment by jameskleeh** [comment]
@graemerocher Perhaps a note for 2.0 would be to allow for a function that takes an `Object[]` instead of a provider. Then the scope could provide custom arguments

**Comment by graemerocher** [comment]
Yeah could be nice idea

**Pull request merged**
