### PR TITLE
[#256] use picocli for command line parsing

### PR DESCRIPTION
**Pull request by remkop**
Please take a look at this PR for #256 using picocli for command line parsing.

* All commands are loaded at startup in this version. (It's possible to optimize this if the performance impact is too large.) 
* All commands show usage help in ANSI colors, in standard *nix format
* All commands now have `-h`, `-help` and `-V`, `-version` options
* Removed 17 classes (parser and multi-step/yaml command)
* Added 9 classes, including enums used in micronaut-profiles
* Removed completion-candidates building logic from individual commands; instead use enum types or specify a [`completionCandidates`](http://picocli.info/#__code_completion_candidates_code_variable) class that generates completion candidates
* I haven't yet generated a bash completion script for the mn command hierarchy

I'm happy to improve on this, would appreciate feedback.
When running this PR, be sure to also install the associated `micronaut-profiles` PR https://github.com/micronaut-projects/micronaut-profiles/pull/47.

Known issue:
`mn create-profile` throws a `ArtifactNotFoundException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)` (I may need help with this)

### CODE REVIEW

**Comment by jameskleeh** [comment]
Was the ability to create multi step yaml commands removed? If so, why?

**Comment by remkop** [comment]
Yes, please see discussion with @graemerocher on https://github.com/micronaut-projects/micronaut-core/issues/256#issuecomment-400576744

> `DefaultMultiStepCommand` is not used at the moment. The Groovy DSL for commands is nicer in many ways so we could simply abandon support for YAML defined commands.

**Comment by graemerocher** [comment]
@remkop Thanks for the pull request, looks very extensive and certainly an improving in terms of the code. A few comments:

1. Could you re-base against master as there are some failures unrelated to the change.
2. Could we remove the println for `Loading commands` or at least make it a status update so it disappears
3. Creating an app seems to work but if I run from the CLI `mn create-controller test` it drops me into interactive mode
4. From interactive mode if I run `create-controller  test` I get `| Error Command not found mn` so something seems to be broken there.

Thanks and looking forward to evolving this into something we can merge.

**Comment by jameskleeh** [comment]
@remkop It is not possible to switch profiles. The profile is selected at app creation and historically does not change. We store which profile was used to create the app in `micronaut-cli.yml`. Technically a user could change that value to a different profile and as long as that profile was shipped with the current version of Micronaut, they could access commands from the new profile.

**Comment by remkop** [comment]
Thanks for the clarification. So when project files exist the CLI could just load the commands relevant for that profile. (This would make it easy to show projectContext-relative help and do auto-completion for example).

What about the opposite case, when no project files exist: would there be any problem if the CLI loaded the commands for _all_ profiles before parsing the command line? How different or similar are commands across profiles? 

For example, is it possible for the `create-bean` command of the `function` profile to have option flags `-x`, `-y` and `-z`, while the same `create-bean` command for the `federation` profile does _not_ have those flags but has the `-a`, `-b` and `-c` flags instead?

**Comment by jameskleeh** [comment]
@remkop It is possible for 2 different profiles to have the same command name with different arguments. The case you are talking about "no project files exist", if you mean an app has not been created, ie running `mn` in an empty folder, then its not possible to access profile commands since the profile is not known.

**Comment by jameskleeh** [comment]
@remkop The `create-controller` command can only be run in the context of an application. Within that context the profile is known and the command can be looked up.

I believe Graeme was running `create-controller` within the context of an application.

**Comment by remkop** [comment]
Aha! That would explain things! Thanks a lot!

**Comment by remkop** [comment]
Closing this PR: it has been superseded by https://github.com/micronaut-projects/micronaut-core/pull/385

**Pull request closed without merging**
