### PR TITLE
Spring Cloud config server client

### PR DESCRIPTION
**Pull request by thiagolocatelli**
This is the pull request related to the issue #501, to include the configuration client for Spring Cloud config client.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks. I think we have to resolve the lack of tests before merging. But it looks like a good start

**Comment by graemerocher** [comment]
Sorry the wording on the CLA changed to fix a typo, could you sign again?

**Comment by thiagolocatelli** [comment]
Signed

**Comment by graemerocher** [comment]
Thanks for the pointer

**Comment by graemerocher** [comment]
Merged with the documentation, improvements and a test (although test coverage could be improved). Thanks for the contribution https://github.com/micronaut-projects/micronaut-core/commit/bfcf63e948332c555170198ae008047433feb275

**Comment by thiagolocatelli** [comment]
Thank you @graemerocher

**Pull request merged**
