### PR TITLE
TCK: constraint handler improve

### PR DESCRIPTION
**Pull request by andriy-dmytruk**
This would solve this issue: https://github.com/micronaut-projects/micronaut-oracle-cloud/issues/925 that the oracle cloud HTTP functions are facing with server TCK.

### CODE REVIEW

**Comment by graemerocher** [comment]
probably this is small enough to target 4.5.x

**Review by graemerocher — APPROVED** [review]

**Comment by yawkat** [comment]
I don't think this change is correct. I believe we have code that relies on the controller body type being set in the request in case of validation error.

@sdelamo do you know more? since you wrote this tck test.

**Comment by sdelamo** [comment]
yes,  the test was verifying that you could access the method annotated with `@Error` the request body with the same type used in the `@Post` methods.

**Comment by yawkat** [comment]
Then we need to revert this

**Pull request merged**
