### PR TITLE
Micrometer metrics configuration

### PR DESCRIPTION
**Pull request by ctoestreich**
Cleaning up the graphite library and adding the statsd configuration.

I tried to create a management endpoint for metrics where the metrics registries were injected, but I didn't want to depend the management module on the metrics config.  I will defer that to @graemerocher and team to present a solution if they want this in the management module.  I didn't see any configurations that provided their own "management" endpoints, but that was the direction I wasn't leaning.  Still learning how things are wired up and how that would be possible.

### CODE REVIEW

**Comment by ctoestreich** [comment]
Not sure who jfrosch is, but that is blocking the CLA.

**Comment by graemerocher** [comment]
Thanks for this, looks like good initial progress. Probably won't make M1, but we should progress this towards M2

@jfrosch Please set your email address in your git commits, re-submit the pull request and sign the CLA

**Comment by ctoestreich** [comment]
The spring boot metrics are all wired via the library [spring-boot-actuator-autoconfigure](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-actuator-autoconfigure).

The pattern there is that the library includes ALL the things you want metrics on but includes them as optional so that they are only actually wired/provide metrics when the specific libraries are included in projects.  I assume the pattern would be similar for Micronaut in that either the management package now has a bunch of optional deps, but can wire up metrics or management pulls in another library like 'metrics' that does that instead.  

The core set of metrics for boot are [these](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics) (for reference).  

screen shot 2018-05-25 at 9 49 53 am

I would suggest the pattern be that all the configurations now optionally require a common metrics library and participate in wiring up any metrics necessary so that in the presence of the metrics configuration (which may actually always be included), they can participate in providing metrics, similar to how the HealthIndicator stuff appears to work in Micronaut.

**Comment by ctoestreich** [comment]
I took a swag at adding the endpoint and some docs.

**Comment by ctoestreich** [comment]
I have a commit coming tomorrow with endpoint working along with binders for JVM, System and Logback.

**Comment by graemerocher** [comment]
Thanks will take a look

**Comment by ctoestreich** [comment]
Example repo: https://github.com/tardisoft/micronaut-metrics-example that works with this branch.

Some screens from the metrics endpoints:

screen shot 2018-05-29 at 9 46 43 pm

screen shot 2018-05-29 at 9 46 58 pm

**Comment by jfrosch** [comment]
Christian,

Thanks for your PR.  I'm finalizing the basic auto-configuration now and am working through the last couple of issues. It's mostly a functional equivalent to what Spring Boot 2.0 does, but there are some differences. As soon as I fix the few issues with the foundational autoconfiguration, I'll be in a better position to incorporate your contributions. I'll be in touch very soon.

Jack Frosch

**Comment by ctoestreich** [comment]
@jfrosch The only thing I haven't been able to work around is optionally including the SimpleMeterRegistry when no other meter registry except for composite exists.

**Comment by ctoestreich** [comment]
Merge from master appears to have broken build.  Master also appears broken.  I will merge again once master goes green.

**Comment by jfrosch** [comment]
Christian,

I reviewed most of the files in your PR and really like what you've done. A few are duplicates (like the JVM binder factory), but you have several excellent classes for implementing meters, like the MetricsPublisher, WebMeterRegistryFilter, etc.

The auto-configuration classes I implemented don't rely on a configurer class (which was the Spring Boot 2 approach), but instead on the bean lifecycle so whenever a MeterRegistry bean is created, the MeterRegistry customizers, MeterFilters, and MeterBindings are applied.  Also, the MeterRegistry customizer doesn't use Boot's "lambdaCallback" thing to swallow the ClassCastException when all customizers are applied to all registeries. Instead, I have an explicit **supports** method on the MeterRegistryCustomizer interface. This allows customization to be applied to specific MeterRegistry types, or any other criteria.  The List<MeterRegistryCustomer> is filtered based on whether the specific MeterRegistry that was just created is supported by the specific customizer.  Another differentiator with the boot approach is the bean scope. I found that the lazy initialization of these metric-related beans can cause filters, binders or customizers to be missed when the beans are scoped as @Singleton. Since some metrics potentially need to be available immediately after the application context is configured (i.e. JVM metrics), I found a more reliable scoping to be @Context.

I'd like to merge your implementations with my auto-configuration, or vice versa. What are your thoughts about this?

**Comment by graemerocher** [comment]
@jfrosch As discussed what makes the most sense is for you to send a pull request to Christian to combine whatever improvements are included in yours into a single pull request 

Please prepare a pull request to send to Christian so he can alter his PR

**Comment by graemerocher** [comment]
One other comment. If metrics can be made to work without using @context that would be better since that causes eager init which slows startup time

**Comment by ctoestreich** [comment]
@jfrosch thanks for the clarity.  I will keep testing with my chages and see if we can proceed without @context.  I think the endpoint bean seems to start the recursive wiring but I will verify if not actually invoking the endpoint still wires up the bean and binders.

**Comment by ctoestreich** [comment]
I do like how the boot 2 stuff works and I borrowed on that but I tried to rig it to fit better with the paradigms that align with what is available in micronaut.  As I mentioned earlier, I am still struggling to find a way to get the conditional wiring for simple meter regisrty working using the @Required(condition) with how the boot stuff works.  I will continue my journey with this tomorrow.

**Comment by ctoestreich** [comment]
@jfrosch my configurers are called by the bean life cycle event as well.

**Comment by ctoestreich** [comment]
In the case we need @Context, we could probably also get away with `public class StartupListener implements ApplicationEventListener<ServiceStartedEvent>` that just essentially focus wiring assuming that the ServiceStartedEvent doesn't block startup.

**Comment by ctoestreich** [comment]
With `compileOnly project(":management")` that means that the /metics endpoint won't work unless you also include management into your project.  Should should be compile in micrometer-core?

Current requirement given that the MetricsEndpoint class is in the micrometer-core but uses annotations, etc from management.

```
dependencies {
    ...
    compile "io.micronaut.configuration:micrometer-core"
    compile "io.micronaut:management"
    ...
}
```

**Comment by graemerocher** [comment]
Seems correct to me that the `/metrics` endpoint will be unavailable if `management` is not on the classpath

**Comment by jfrosch** [comment]
@graemerocher I think I'll put a period on this issue. You can just approve Christian's PR as is.

**Comment by graemerocher** [comment]
@ctoestreich I think we can merge the progress so far. Can you re-base against master to see if the tests pass

**Comment by ctoestreich** [comment]
The test that is failing has been flakey.  It is using an inline static factory with conditional bean wiring.  It would appear that the factory bean might not be recreating or initializing the beans in time for the test to run.  I have added a get beans of type that should resolve any lazy init, but this test has been working locally in all incarnations.  This particular one has been flakey on Travis.  It has been behaving as though the factory isn't wiring up for every Application.run that is invoked.

**Comment by graemerocher** [comment]
I have resolved some of the issues that were occurring on Travis in the latest code, so it may be better now

**Comment by graemerocher** [comment]
@ctoestreich There is one failing test with this pull request, is that something you are looking in to? Otherwise we are really to merge

**Comment by graemerocher** [comment]
@ctoestreich I will take a look

**Comment by ctoestreich** [comment]
Given the fix for the test appears to be simply forcing the creation of the beans, I am wondering if there should be an @Context on MeterRegistryFactory.  I got it passing by changing 

### Not Working

```java
void "test metrics endpoint with filtered metrics"() {
        given:
        EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer, [
                'endpoints.metrics.sensitive' : false,
                (MICRONAUT_METRICS_ENABLED)   : true,
                'metrics.test.filters.enabled': true
        ])
        URL server = embeddedServer.getURL()
        RxHttpClient rxClient = embeddedServer.applicationContext.createBean(RxHttpClient, server)

        when:
        def response = rxClient.exchange("/metrics", Map).blockingFirst()
        Map result = response.body()

        then:
        response.code() == HttpStatus.OK.code
        result.names.size() == 1
        !result.names[0].toString().startsWith("jvm")

        cleanup:
        embeddedServer.close()
    }

    @Factory
    static class MeterFilterFactory {
        @Bean
        @Singleton
        @Requires(property = "metrics.test.filters.enabled", value = "true", defaultValue = "false")
        MeterFilter denyNameStartsWithJvmFilter() {
            return MeterFilter.denyNameStartsWith("jvm")
        }

        @Bean
        @Singleton
        @Requires(property = "metrics.test.filters.enabled", value = "true", defaultValue = "false")
        MeterFilter maximumAllowableMetricsFilter() {
            return MeterFilter.maximumAllowableMetrics(1)
        }
    }
```

to this

### Working

```java
 void "test metrics endpoint with filtered metrics"() {
        given:
        EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer, [
                'endpoints.metrics.sensitive' : false,
                (MICRONAUT_METRICS_ENABLED)   : true,
                'metrics.test.filters.enabled': true
        ])
        URL server = embeddedServer.getURL()

        when:
        ApplicationContext context = embeddedServer.getApplicationContext()

        then:
        context.getBeansOfType(MeterFilter.class)?.size() == 2
        MicrometerMeterRegistryConfigurer configurer = context.getBean(MeterRegistryConfigurer)
        configurer.filters.size() == 2
        context.containsBean(MetricsEndpoint)
        context.containsBean(MeterRegistry)
        context.containsBean(CompositeMeterRegistry)
        context.containsBean(SimpleMeterRegistry)

        when:
        RxHttpClient rxClient = embeddedServer.applicationContext.createBean(RxHttpClient, server)
        def response = rxClient.exchange("/metrics", Map).blockingFirst()
        Map result = response.body()

        then:
        response.code() == HttpStatus.OK.code
        result.names.size() == 1
        !result.names[0].toString().startsWith("jvm")

        cleanup:
        embeddedServer.close()
    }

    @Factory
    static class MeterFilterFactory {
        @Bean
        @Singleton
        @Requires(property = "metrics.test.filters.enabled", value = "true", defaultValue = "false")
        MeterFilter denyNameStartsWithJvmFilter() {
            return MeterFilter.denyNameStartsWith("jvm")
        }

        @Bean
        @Singleton
        @Requires(property = "metrics.test.filters.enabled", value = "true", defaultValue = "false")
        MeterFilter maximumAllowableMetricsFilter() {
            return MeterFilter.maximumAllowableMetrics(1)
        }
    }
```

**Comment by graemerocher** [comment]
Sounds like the beans are not being initialized in time. So it may well be the case that `@Context` is required.

**Comment by graemerocher** [comment]
I am going to merge this, so that it is integrated it, we can continue to evolve it and trace the root cause of the travis issue (it is probably an intialization order problem). Thanks again for all your work on this.

**Pull request merged**
