### PR TITLE
build: Add OpenAPI BOM

### LINKED ISSUE #7490: build: remove swagger version from catalog
https://github.com/micronaut-projects/micronaut-core/pull/7457

### PR DESCRIPTION
**Pull request by timyates**
This results in the following diff in the published catalog:

```diff
108d107
< swagger = "2.2.0"
401a401
> micronaut-openapi-bom = {group = "io.micronaut.openapi", name = "micronaut-openapi-bom", version = "" }
560,562c560,562
< swagger = {group = "io.swagger.core.v3", name = "swagger-core", version.ref = "swagger" }
< swagger-annotations = {group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swagger" }
< swagger-models = {group = "io.swagger.core.v3", name = "swagger-models", version.ref = "swagger" }
---
> swagger-annotations = {group = "io.swagger.core.v3", name = "swagger-annotations", version = "" }
> swagger-core = {group = "io.swagger.core.v3", name = "swagger-core", version = "" }
> swagger-models = {group = "io.swagger.core.v3", name = "swagger-models", version = "" }
```

The main difference being that instead of `swagger`, we now have `swagger-core`

Is this ok for a minor release?  Or do we need to rename the managed swagger dependency in the openapi module?

Closes #7490

### CODE REVIEW

**Comment by timyates** [comment]
I guess we should mention catalog renames like this in `breaks.adoc` for 3.6.0

**Comment by sdelamo** [comment]
> I guess we should mention catalog renames like this in `breaks.adoc` for 3.6.0

We should not have any breaking change in 3.6.0. 

Would duplicating this line:

https://github.com/micronaut-projects/micronaut-openapi/blob/master/gradle/libs.versions.toml#L2

Instead of:

```toml
[versions]
managed-swagger = "2.2.1"
```

having:

```toml
[versions]
managed-swagger= "2.2.1"
managed-swagger-core = "2.2.1"
```

and a new release of OpenAPI avoid the breaking change?

**Comment by melix** [comment]
Yes I think we can duplicate the entries for now. I guess that's `managed-swagger` that we need to add to both `[versions]` and `[libraries]`

**Comment by timyates** [comment]
Could we just rename `managed-swagger-core` to `managed-swagger` in the openapi module?

**Comment by melix** [comment]
I think we can't do that easily since the catalog entry names are derived from project names and artifact id, basically.

**Comment by timyates** [comment]
So like this? https://github.com/micronaut-projects/micronaut-openapi/pull/758

**Comment by timyates** [comment]
@sdelamo This was done in https://github.com/micronaut-projects/micronaut-openapi/releases/tag/v4.4.0

I think it's ready for a review from you and @melix

**Review by sdelamo — APPROVED** [review]

**Comment by sdelamo** [comment]
@timyates @melix should this go in 3.6.x or 4.0.x?

**Comment by melix** [comment]
I don't know. If it's a breaking change, 4.x. Otherwise 3.6.x. However once you upgrade to the latest build plugins you'll see that the version catalog is breaking: it misses the `swagger` entry.

**Comment by timyates** [comment]
I guess we should put swagger back, and make a note to remove it in 4.0.0?

**Comment by melix** [comment]
Yes

**Comment by timyates** [comment]
@melix @sdelamo Done, what's the quickest way to locally update to the build plugin to check it's ok now?

**Comment by melix** [comment]
> Done, what's the quickest way to locally update to the build plugin to check it's ok now?

Simply upgrade to 5.3.13. Note that it will fail because there are other errors not related to this PR (`spring`, `springboot`, ...).

**Comment by timyates** [comment]
> > Done, what's the quickest way to locally update to the build plugin to check it's ok now?
> 
> Simply upgrade to 5.3.13. Note that it will fail because there are other errors not related to this PR (`spring`, `springboot`, ...).

I'm seeing

```
* What went wrong:
Could not determine the dependencies of task ':bom:checkVersionCatalogCompatibility'.
> Failed to query the value of task ':bom:checkVersionCatalogCompatibility' property 'baseline'.
   > Expected configuration ':bom:detachedConfiguration1' to contain exactly one file, however, it contains no files.
```

I must have missed something

**Comment by melix** [comment]
That's very strange. I took that branch, applied this diff:

```diff
--- a/settings.gradle
+++ b/settings.gradle
@@ -14,7 +14,7 @@ pluginManagement {
 }
 
 plugins {
-    id 'io.micronaut.build.shared.settings' version '5.3.12'
+    id 'io.micronaut.build.shared.settings' version '5.3.13'
 }
 
 rootProject.name = 'micronaut'
```

and ran `./gradlew :bom:checkVersionCatalogCompatibility` and I'm getting this: https://ge.micronaut.io/s/mru5e7i7vlygi/failure#1

There must be some issue with the baseline file not being fetched in your case :thinking:

**Comment by timyates** [comment]
Fixed the BOM baseline, and the swagger failure is now gone 👍 

```
Execution failed for task ':bom:checkVersionCatalogCompatibility'.
> Version catalogs are not compatible:
  The following versions were present in the baseline version but missing from this catalog:
    - springboot
    - spring
```

**Pull request merged**
