### PR TITLE
KSP: Exclude static properties

### PR DESCRIPTION
**Pull request by dstepanov**
Fixes partially https://github.com/micronaut-projects/micronaut-core/issues/10228

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Comment by dstepanov** [comment]
@altro3 This only fixes the static fields problem. `isAscending` is also working in Java (see test), and I cannot reproduce the  enum. How do you access it? Maybe you can modify the test to reproduce it.

**Comment by altro3** [comment]
@dstepanov About method `isAscending` - yeah, sorry, this is my fault. I agree, java visitor has this property too. Just,  forget about this bug.

About enum `io.micronaut.data.model.Sort$Order$Direction`: There is still a problem, I identified the place where classElement is returned, instead of enumElement.

Problem inside method `KotlinSimplePropertyElement.getGenericType()`. Look to the sreenshot (KSP):
изображение
As you see, method `publicField.getType()` return right `KotlinEnumElement`, but method `publicField.getGenericType()` return `KotlinClassElement`.

Same code with java:
изображение
As you see, both methods return the same `JavaEnumElement`

**Comment by dstepanov** [comment]
Added a fix for enums

**Comment by altro3** [comment]
@dstepanov Forgot to tell you about another one bug: As you see on screenshot

изображение

required properties list is different between java and kotlin. For example, property `number`. That's because of wrong return value for method `element.isNonNull()`

KSP `element.isNonNull()` returns `true`:
изображение

Java `element.isNonNull()` returns `false`:
изображение

Need to fix primitive types processing for KSP or for java. Which value is right in this case?

**Pull request merged**
