### PR TITLE
Issue #3598 - RxNettyHttpClientRegistry.resolveClient() configuration…

### PR DESCRIPTION
**Pull request by croudet**
… can be null.

Use default configuration if configuration argument is null.

### CODE REVIEW

**Comment by jameskleeh** [comment]
Can you please merge master into this branch?

**Comment by croudet** [comment]
Do you want me to rebase this branch with master?

**Comment by jameskleeh** [comment]
@croudet You can just merge master into this branch, rebase isn't necessary

**Comment by croudet** [comment]
Done

**Pull request merged**
