### PR TITLE
#256 cli module v2

### PR DESCRIPTION
**Pull request by remkop**
Please take a look at this PR for #256 using picocli for command line parsing. 
This PR supersedes https://github.com/micronaut-projects/micronaut-core/pull/368.

Changes:
* rebased on current master
* println for `Loading commands` removed
* fixed issues with profile-specific commands, so `mn create-controller test` now works from the CLI and `create-controller test` now works in interactive mode

Looking forward to further feedback.

When running this PR, be sure to also install the associated `micronaut-profiles` PR https://github.com/micronaut-projects/micronaut-profiles/pull/47.

### CODE REVIEW

**Comment by graemerocher** [comment]
@remkop Thanks! Seems almost there. Few things I spotted in testing. If I go into interactive mode and do:

```
mn> create-app test3 -lang kotlin -profile function -build maven 
```

I get this error:

```
| Initializing application. Please wait.....
| Application created at /Users/graemerocher/micronaut/apps/picotest/test3
| Initializing application. Please wait...
| Error Command [mn] error: null (Use --stacktrace to see the full trace)
```

If I try add the `-stacktrace` flag I get:

```
mn> create-app test3 -lang kotlin -profile function -build maven -stacktrace
| Error Unmatched argument [-tacktrace]
```

Seems it takes off the first `s` from stack trace and doesn't show the stacktrace.

Nearly there though.

One other small thing. TAB completion doesn't seem to work when completing flag names. For example:

```
mn> create-app test3 -lang kotlin -profile function -bu
```

If I hit `TAB` with the above input nothing happens but it should complete to `-build`. However this issue is minor and can probably be fixed in a future pull request in order not to hold this one up.

**Comment by remkop** [comment]
Thanks for checking. Now investigating.

In interactive mode, if I run `--stacktrace create-app test3 -lang kotlin -profile function -build maven` I do see the stack trace.  Unsure still why the stack trace is not shown when the option is specified on the `create-app` subcommand but is shown when specified on the top-level command...

Quick question: how many leading hyphens should options have?

Currently the following are "common" options shared by the top-level command and the creation commands (I should probably also add them to the list-profile and the profile-specific commands):
```
  -h, -help, --help         Show this help message and exit.
  -p, --plain-output        Use plain text instead of ANSI colors and styles.
  -s, --stacktrace          Show full stack trace when exceptions occur.
  -v, --verbose             Create verbose output.
  -V, -version, --version   Print version information and exit.
```

I wasn't sure about how many prefix hyphens each option should have. The `--stacktrace`  option has two because the error message says "Use --stacktrace to see the full trace". For help and version I added two long forms, with one and two leading hyphens. The Micronaut docs show examples where long options like `-lang` have only one leading hyphen. It's a bit inconsistent now. Do you want to standardize this?

If you feel that these common options give too much visual clutter, it is possible to declare an option as "hidden" in which case the parser will accept them, but they are not shown in the usage help.

**Comment by graemerocher** [comment]
Yeah we should probably standardise on 2 for long options (like --stacktrace) and 1 for short cuts like (-h)

**Comment by graemerocher** [comment]
Note that in that case the TAB completion should also be consistent and tab complete to 2 hyphens, currently in interactive mode it tab completes to 1

**Comment by remkop** [comment]
Yes, tab completion has a bug in completing option names. It displays the list of options, and works for option values but partially typed options are not completed. I will look at this after fixing the NPE and the problem with --stacktrace option not working.

Fixing completion will need a picocli release. 

Completion is driven off the option definitions so if we standardize on 2 hyphens for long form and 1 hypen for short form the TAB completion will reflect this.

**Comment by remkop** [comment]
Just to confirm: is it okay to change these options to have two leading hypens?
(That means the CLI user manual docs need to be updated also.)

```
      -build=BUILD-TOOL     Which build tool to configure. Possible values: gradle, maven.
      -features=FEATURE     The features to use
      -inplace              Create a service using the current directory
      -lang=LANG            Which language to use. Possible values: java, groovy, kotlin.
      -profile=PROFILE      The profile to use
```

**Comment by graemerocher** [comment]
Yes. We will need to note this in the breaking changes. See `breaking.adoc`

**Comment by remkop** [comment]
I've pushed some commits with the following changes:

* fix NPE that occurred when re-initializing the completers after creating an app
* ensure `--stacktrace` option value is reset before parsing new input
* standardize short and long option form
* ensure all commands have the common options (help, version, plain-output, verbose and stacktrace)

I also updated the profile-specific commands in https://github.com/micronaut-projects/micronaut-profiles/pull/47:
* standardize short and long option form
* ensure all commands have the common options (help, version, plain-output, verbose and stacktrace)

Please re-install micronaut-profiles to Maven Local `micronaut-profiles$ ./gradlew clean publishToMavenLocal` before testing.

I'll take a look at the docs later.
Is `breaking.adoc`  in a different project? I can't find it in the micronaut-core project.

**Comment by graemerocher** [comment]
Sorry it is `breaks.adoc`

**Comment by remkop** [comment]
Do you also see this error with `create-profile`?

```
mn> -x create-profile
| Error Also: C:\Users\remko\.m2\repository\io\micronaut\profiles\profile\maven-metadata-local.xml not found
| Error Command [mn] error: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.springframework.boot.cli.compiler.grape.DependencyResolutionFailedException: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:324)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:129)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:121)
        at io.micronaut.cli.profile.repository.MavenProfileRepository.resolveProfile(MavenProfileRepository.groovy:112)
        at io.micronaut.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:95)
        at io.micronaut.cli.profile.repository.MavenProfileRepository.getProfile(MavenProfileRepository.groovy:103)
        at io.micronaut.cli.profile.commands.AbstractCreateCommand.handle(AbstractCreateCommand.groovy:268)
        at io.micronaut.cli.profile.commands.CreateAppCommand.handle(CreateAppCommand.groovy:74)
        at io.micronaut.cli.MicronautCli.executeCommand(MicronautCli.groovy:330)
        at io.micronaut.cli.MicronautCli$_execute_closure2.doCall(MicronautCli.groovy:241)
        at com.sun.proxy.$Proxy13.handleCommand(Unknown Source)
        at io.micronaut.cli.MicronautCli.handleCommand(MicronautCli.groovy:396)
        at io.micronaut.cli.MicronautCli$_handleCommandWithCancellationSupport_closure6.doCall(MicronautCli.groovy:498)
        at io.micronaut.cli.MicronautCli$_handleCommandWithCancellationSupport_closure6.call(MicronautCli.groovy)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:319)
        ... 13 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 14 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 16 more
| Error Command [mn] error: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.micronaut.profiles:profile:jar: in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

**Comment by remkop** [comment]
@ZacharyKlein  I tried cherry-picking https://github.com/micronaut-projects/micronaut-core/commit/b3030df395ccbeea52d1963e98e093bfbea90423 but it is already in my branch...

**Comment by remkop** [comment]
@ZacharyKlein  when I revert HEAD back to that commit and rebuild the core and profiles projects, I cannot start the CLI:

```
C:\Users\remko\IdeaProjects\micronaut-core\cli\build\bin>mn --stacktrace
Resolving dependencies...
| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:profile:jar:1.0.0.BUILD-SNAPSHOT in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots) (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.micronaut.profiles:profile:jar:1.0.0.BUILD-SNAPSHOT in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.resolve(AetherGrapeEngine.java:319)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:129)
        at org.springframework.boot.cli.compiler.grape.AetherGrapeEngine.grab(AetherGrapeEngine.java:121)
        at io.micronaut.cli.profile.repository.MavenProfileRepository.getAllProfiles(MavenProfileRepository.groovy:175)
        at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:230)
        at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:159)
| Error Error occurred running Micronaut CLI: Could not find artifact io.micronaut.profiles:profile:jar:1.0.0.BUILD-SNAPSHOT in micronautSnapshots (https://oss.sonatype.org/content/repositories/snapshots)
```

FYI When I navigate to `C:\Users\remko\.m2\repository\io\micronaut\profiles\profile\1.0.0.BUILD-SNAPSHOT`, I only see a file `resolver-status.properties` (timestamp around the time I rebuilt the projects from master).

**Comment by ZacharyKlein** [comment]
@remkop the `create-profile` command is still broken, I would not try to use it at the moment and just clone an existing profile and go from there. I'm working on the fix.

**Comment by remkop** [comment]
FYI I am planning to release a new version of picocli that fixes the TAB completion issue today or tomorrow.

**Comment by graemerocher** [comment]
@remkop Once you have could we rebase this? If we can get it merged Monday or Tuesday it can go into M3

@jameskleeh Anything to add?

**Comment by remkop** [comment]
@graemerocher Understood. Will rebase.

**Comment by jameskleeh** [comment]
@graemerocher Looks ok to me

**Comment by remkop** [comment]
Latest commits fix the TAB completion and shows suggested solutions to users when commands or options are mistyped.

Still todo:
* rebase to incorporate @ZacharyKlein 's fix for the issue with create-profile 
* update docs

**Comment by remkop** [comment]
Closing this PR: it has been superseded by https://github.com/micronaut-projects/micronaut-core/pull/400

**Pull request closed without merging**
