### PR TITLE
Add/Remove static routes programmatically

### PR DESCRIPTION
**Pull request by croudet**

### CODE REVIEW

**Comment by jameskleeh** [comment]
@croudet Can you explain the use case? This seems odd to do given the changes wouldn't persist a restart

**Comment by croudet** [comment]
I have some routes  whose paths contains a java constant. With a controller I can do:`@Get("/path/" + VERSION + "/")`

I don't want the final user to update the configuration file when the version changes, so I 'd like to add the routes at startup.

**Comment by jameskleeh** [comment]
@croudet Couldn't you achieve that by supplying a property source in the main method?

**Comment by croudet** [comment]
How can I update the static route?

**Comment by croudet** [comment]
There is other of doing this, closing.

**Pull request closed without merging**
