### PR TITLE
Refactor instrumentation WIP

### PR DESCRIPTION
**Pull request by dstepanov**
Not finished.

I tried to refactor instrumentation to reduce call stack described in https://github.com/micronaut-projects/micronaut-core/issues/2338

There are a few problems:
- I have created ExecutorServiceInstrumenter in `runtime` module and it looks like some tests want to inject `ThreadPoolExecutor` which is missing after instrumentation.
- Haven't found a good way to set context request in `ServerRequestContext`
- Some classes are deleted or removed, mostly internal. I don't know if it's a breaking change.

I did some testing and it looks like the call stack is smaller a bit.

@graemerocher Can you take a look and let me know if it makes sense or not?

### CODE REVIEW

**Comment by graemerocher** [comment]
@dstepanov Interesting progress. This is a pretty delicate area so we have to tread with care.

* I am not sure about ThreadPoolExecutor. Could you fix the checkstyle problems so we can get teh tests running?
* Yeah `ServerRequestContext` is pretty important :)
* For classes that are `public` and not marked with `@Internal` you can deprecate them but leave the classes there. If they are beans you can remove the `@Singleton` definitions so that they are not beans anymore.

**Comment by jameskleeh** [comment]
If its reasonable to assume the beans are being used a client application then we couldn't make them not beans anymore in a 1.x branch.

**Comment by graemerocher** [comment]
I don't think it is reasonable to assume any of these beans are being used directly. Looking at the ones impacted I am not sure why we didn't mark them as internal in the first place

**Comment by dstepanov** [comment]
Regarding the changes I made:

`InvocationInstrumenter` - this should be a new interface to instrument invocation without enlarging call stack

`InvocationInstrumenterFactory` - Just like `ReactiveInstrumenter` creates instrumenters only if needed. They are instrumenting `ThreadFactory` and `ExecutorService`.

`ReactiveInvocationInstrumenterFactory` - The same as above but instrumenting RxJava2

`TracingInvocationInstrumenterFactory` - more a marker interface to get the main tracing instrumenter and used somewhere else like Hystrix.

`ReactiveInstrumenter` - previous interface, still being used for RxJava2 after refactoring, there are no implementations in core

`RunnableInstrumenter` - previous interface, this was only used in RxJava2Instrumentation and I kept it there, there are no implementations in core

**Comment by dstepanov** [comment]
I think I managed to solve most of the problems, there are still a few things:
- Because of instrumentation 'ExecutorService' you cannot inject 'ThreadPoolExecutor', it does work in tests because I disabled instrumentation if there are no instrumentors. That was like this before.
- Need to come with a better change in 'ServerRequestContext'
- Revert some important classes if needed
- Maybe somebody can redo javadoc/naming of classes

**Comment by graemerocher** [comment]
> I think I managed to solve most of the problems, there are still a few things:
> 
>     * Because of instrumentation 'ExecutorService' you cannot inject 'ThreadPoolExecutor', it does work in tests because I disabled instrumentation if there are no instrumentors. That was like this before.

This seems fine to me.

> 
>     * Need to come with a better change in 'ServerRequestContext'

What is the current change?

> 
>     * Revert some important classes if needed

Yeah we might want to revert the deletions and mark this classes as deprecated (for deletion) instead.
> 
>     * Maybe somebody can redo javadoc/naming of classes

Will take a look. Thanks.

**Comment by dstepanov** [comment]
I had to make `set` in `ServerRequestContext` public, it doesn't look nice.
I think the best way would be to add a method to return `InvocationInstrumenter` but the interface is in `runtime` module and `http` module doesn't include it.

It would be nice to refactor `ServerRequestTracingPublisher`, `ClientServerRequestTracingPublisher` and other duplicates to use `InvocationInstrumenter`

**Comment by graemerocher** [comment]
Right I see what you are saying. Thanks for the feedback.

**Comment by dstepanov** [comment]
@graemerocher Did you have time to take a look? WDYT?

**Comment by graemerocher** [comment]
@dstepanov not yet, on my todo list. Will be away for a week or so from end of tomorrow. Definitely want to integrate this for the next milestone of 1.3 though. Thanks

**Comment by dstepanov** [comment]
@graemerocher Made some changes based on how https://github.com/reactiverse/reactive-contexts is instrumenting RX; added new hooks, removed scheduler hook, haven't found any `Single/Maybe` classes that extends `Callable` so I have deleted those. We can probably delete `setOnConnectableFlowableAssembly`, `setOnConnectableObservableAssembly` and `setOnParallelAssembly`.

Looking at your changes in `RxInstrumenterFactory` I think you misunderstood two collections that are there, both of them are factories, one of them is a collection of new instrumenters and other of old-style wrappers to maintain backward compatibility, both of them need to be resolved during the `create` call. 

If we would be able to remove old `ReactiveInstrumenter` then `RxInstrumenter` can be replaced by a single `InvocationInstrumenter` and all calls can be inlined.

Not sure why tests are failing, everything is passing locally.

**Comment by graemerocher** [comment]
I think we should be able to inline if no ReactiveInstrumenter beans are present no?

**Comment by dstepanov** [comment]
If `ReactiveInstrumenter` can be removed, it would be possible to remove `RxInstrumenter` and refactor all `RxInstrumented*` classes to something like this:

```
       try {
            instrumenter.beforeInvocation();
            source.subscribe(o);
        } finally {
            instrumenter.afterInvocation();
        }
```

Instead of an extra call to `RxInstrumenter`.

**Comment by graemerocher** [comment]
@dstepanov I think that would be better from a performance perspective. Since after this PR there are no `ReactiveInstrumenter` implementations I am not sure if it is worth keeping?

**Comment by dstepanov** [comment]
The only reason to keep it for backward compatibility, if you are OK I can inline calls to `RxInstrumenter`.

**Comment by graemerocher** [comment]
Yeah I think it is the right thing to do. Deprecate the interface and leave it in place and alter the runtime to inline the calls and ignore `ReactiveInstrumenter`

**Comment by graemerocher** [comment]
@dstepanov Latest changes have introduced a new test failure, are you looking into that?

**Comment by dstepanov** [comment]
@graemerocher I have no idea why tests are failing, locally eveything is passing.

**Comment by dstepanov** [comment]
@graemerocher Not so easy. The problem was that `beforeInvocation` method was called twice because of the nested call during RX invocation.

There are a few solutions, create instrumenter instance per call like here:
https://github.com/reactiverse/reactive-contexts/blob/master/propagators-rxjava2/src/main/java/io/reactiverse/reactivecontexts/propagators/rxjava2/ContextPropagatorOnFlowableAssemblyAction.java

Or using stacks:
```
            private final Deque<Optional<HttpRequest<Object>>> requests = new ArrayDeque<>(1);

            @Override
            public void beforeInvocation() {
                requests.push(ServerRequestContext.currentRequest());
                ServerRequestContext.set(invocationRequest);
            }

            @Override
            public void afterInvocation() {
                ServerRequestContext.set(requests.pop().orElse(null));
            }
```

I think the best one would be the first solution.

**Comment by graemerocher** [comment]
Yes the first solution is the best

**Comment by graemerocher** [comment]
@dstepanov Do you want me to look at that or were you going to?

**Comment by dstepanov** [comment]
@graemerocher I’m going to give it a try

**Comment by dstepanov** [comment]
@graemerocher Take a look, I did refactor it a bit

**Comment by dstepanov** [comment]
@graemerocher Simplified a bit

**Comment by graemerocher** [comment]
@dstepanov Thanks will look in a bit, trying to finish this Gradle 6 upgrade

**Comment by graemerocher** [comment]
@dstepanov Could you rebase to master? I am slightly confused by this because if I setup a break point on `TracedController.hello` it never wraps any of the flowables since `newInvocationInstrumenter()` never returns anything other than Optional.empty() for all of the active `InvocationInstrumenterFactory` instances.

**Comment by dstepanov** [comment]
@graemerocher Done, I can see begin is beeing called on the same thread as `spanCustomizer.tag`

**Comment by graemerocher** [comment]
@dstepanov  This is the stacktrace I see when running `HttpTracingSpec`.

Screenshot 2019-12-16 at 10 43 38

As you can see, none of the flowables seem be instrumented at all hence I am not sure this PR is working as we think it is working or am I missing something?

**Comment by dstepanov** [comment]
@graemerocher That's correct, tracing is skipped when no previous one is found, that works the same as before. In the master, you will see instrumented classes but no wrapped calls.

To see instrumented RX classes add this class:

```
@Singleton
public class MyInst implements ReactiveInvocationInstrumenterFactory {
    @Override
    public Optional<InvocationInstrumenter> newReactiveInvocationInstrumenter() {
        return Optional.of(new InvocationInstrumenter() {
            @Override
            public void beforeInvocation() {
            }

            @Override
            public void afterInvocation() {
            }
        });
    }
}
```

**Comment by graemerocher** [comment]
OK yeah I see now, thanks for the clarification

**Comment by graemerocher** [comment]
@dstepanov I merged this with some changes to avoid the wrapping cost of `Optional`. Thanks for looking into this, it will help us progress forward the optimization of the http layer

**Comment by dstepanov** [comment]
@graemerocher Great!

**Pull request merged**
