### PR TITLE
added doc text for using logback

### PR DESCRIPTION
**Pull request by andreashe**
As it did not use logback out of the box but it was mentioned, I wanted to add the solution to get it work.

### CODE REVIEW

**Comment by jameskleeh** [comment]
I think this is a little out of place. It makes sense to me to create a top level section in the docs called "Logging" that describes the default setup and how to change it. The configuration for the loggers could be placed there as well

**Comment by andreashe** [comment]
> I think this is a little out of place. It makes sense to me to create a top level section in the docs called "Logging" that describes the default setup and how to change it. The configuration for the loggers could be placed there as well

Good point. Do you mean an menu entry in the main document or a separate one?

**Comment by jameskleeh** [comment]
@andreashe A top level menu item, like `13 Logging` that has a document explaining that we use Slf4j and the default implementation is logback, how to configure, maybe show an example of how to switch to log4j2 etc..

**Comment by andreashe** [comment]
> @andreashe A top level menu item, like `13 Logging` that has a document explaining that we use Slf4j and the default implementation is logback, how to configure, maybe show an example of how to switch to log4j2 etc..

OK fine. I can create one with the knowledge I have. How to switch to log4j, I don't know. I guess it makes sense to move also the http logging to that page? I would also describe usage of lombok for logging.

**Pull request closed without merging**
