### PR TITLE
Fix field generics of inner class

### LINKED ISSUE #11162: Wrong field type when it GenericPlaceholderElement in inner classes
### Expected Behavior

Sample classes structure:
```java
@Controller("/test")
class TestController {
    @Get
    public HttpResponse<ResponseObject<List<Dto>>> endpoint() {
        return null;
    }
    
    public static class ResponseObject<T> {

        public T body;
    }

    public static class Dto {

        public Locale locale;
    }
}
```
`HttpResponse` is `io.micronaut.http.HttpResponse`

The problem with process type `HttpResponse<ResponseObject<List<Dto>>>`, more precisely, with type `ResponseObject<List<Dto>>`.

That's what I see, when process ResponseObject class:
изображение

As you see, generic type is correct - `type.getTypeArguments().get("T") = java.util.List`

But when I get field `body` I see type `java.lang.Object`, but must be  `java.util.List` with generic `Dto`

### Version

4.6.4

### PR DESCRIPTION
**Pull request by altro3**
Fixed #11162

### CODE REVIEW

**Comment by dstepanov** [comment]
Please create a new test. Don't modify existing one.

**Comment by altro3** [comment]
That's was code formatting. Reverted it. I've added single test: `test field type with generic in inner class`

**Comment by altro3** [comment]
@dstepanov from logs of this failed job:
изображение

**Review by dstepanov — APPROVED** [review]

**Comment by dstepanov** [comment]
Thanks @altro3 !

**Comment by altro3** [comment]
@dstepanov Are you planning release 4.6.6? Because target branch of this PR was 4.6.x

**Comment by dstepanov** [comment]
Yes, but probably next week

**Comment by altro3** [comment]
@dstepanov Hi! Any news about release `4.6.6`?

**Pull request merged**
