### PR TITLE
Consider retryable predicate in circuit breaker

### PR DESCRIPTION
**Pull request by l0co**
Fix for #5037

### CODE REVIEW

**Comment by jameskleeh** [comment]
In general modifying existing tests is not preferred because it makes it impossible to tell if the changes broke the existing tests or not. That is an indicator that the change might be considered to be breaking. Just FYI for the future. You have contributed a lot to the framework and we really appreciate it! 🥇

**Comment by jameskleeh** [comment]
I've created a new PR that targets 2.4 and makes the interface change backwards compatible

**Comment by l0co** [comment]
OK, I understand the requirement but tests were written having the previous logic in the mind, ie. `includes` does not affect `@CircutBreaker`, only underlying `@Retryable`, so they failed. If I will send a PR with a breaking change like this in the future - should I left failed tests to be resolved by you?

**Comment by jameskleeh** [comment]
You don't have to leave the test in a failing state, but instead change it the minimal amount possible to get it to pass so its easy to see what is changing

**Pull request closed without merging**
