### PR TITLE
Enlarge PropertySourcePropertyResolver.catalog so it can hold z

### PR DESCRIPTION
**Pull request by BartRobeyns**

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks.. sill bug this 🤦‍♂️

**Comment by graemerocher** [comment]
Sorry the wording on the CLA changed to fix a typo, could you sign again?

**Comment by BartRobeyns** [comment]
Sure, happy to.

**Comment by graemerocher** [comment]
Applied manually with https://github.com/micronaut-projects/micronaut-core/commit/fdbc4595eb2eb3fcf66635a58b09ef0c0410713a

Thanks!

**Pull request closed without merging**
