### PR TITLE
Predictible order for BeanDefinitionWriter.interfaceTypes & loadTypeM…

### PR DESCRIPTION
**Pull request by l0co**
Relates to #3734

### CODE REVIEW

**Comment by l0co** [comment]
@graemerocher I'm not 100% sure this will work, because it still depends on the order of calling particular `interfaceTypes.add()` invocations, and there are a few of them in the `BeanDefinitionWriter` code. But this should be reviewed by someone who sits closer to this code...

Maybe using `TreeSet` with class name comparator will be safer?

**Comment by l0co** [comment]
Build failed after switching from `HashSet` to `LinkedHashSet`? :)

**Comment by ilopmar** [comment]
@l0co we had an issue with the Spock version. Please rebase master.

**Comment by ilopmar** [comment]
@l0co I've merged master and the build is green now :-)

**Comment by graemerocher** [comment]
I would say we should perform a sort by interface name as well yes

**Comment by l0co** [comment]
@graemerocher  I've changed `LinkedHashSet` to `TreeSet` and now I think this will work in all screnarios.

@ilopmar Thanks for merging. However, now, after merging my own branch with current master it shows that `micronautSqlVersion` was increased from `2.3.8` to `2.3.9` in my branch. I don't know why, because this change is already done in master (?).

**Comment by ilopmar** [comment]
@l0co you may want to try to rebase master

**Comment by l0co** [comment]
@ilopmar I did that and it turned our wrong, because now a new commit has been created. I should just have merged master in my branch... Anyway, if you merge this change soon before next `micronautSqlVersion` bump it shouldn't be harmful. Otherwise I can close this PR and create another one, clean.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
