### PR TITLE
Add link for CLA agreement

### PR DESCRIPTION
**Pull request by ashishkujoy**
CLA is a mandatory step for doing any code contribution to micronaut, but this information is not mentioned in CONTRIBUTING.md, I think it will be better for new contributors to know this upfront so that it does not come up as surprise when they submit pull request.

Signed-off-by: ashishku <ashishku@thoughtworks.com>

### CODE REVIEW

**Comment by graemerocher** [comment]
Perhaps worth updating the project template as well https://github.com/micronaut-projects/micronaut-project-template/blob/master/CONTRIBUTING.md

**Comment by ashishkujoy** [comment]
I added in the project template and realized that CLA is per repo base, so may we need to some github action will trigger when some create a new project from template, that GitHub action will update the CLA link.

**Comment by ashishkujoy** [comment]
Jetbrains does something similar around this for plugin templates. https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/.github/workflows/template-cleanup.yml 

Maybe i can add something similar to update CLA url for each new project created with that template.

**Comment by ashishkujoy** [comment]
Added GitHub action to update CLA URL for each new project created using the template. 
https://github.com/micronaut-projects/micronaut-project-template/pull/142

**Comment by ashishkujoy** [comment]
Is this good to merge, or are is there is any feedback on this to be implemented?

**Pull request closed without merging**
