### PR TITLE
Support storing property files in config folder

### PR DESCRIPTION
**Pull request by dstepanov**
Not sure if it needs to be configured or it's fine to have it like this.

### CODE REVIEW

**Comment by graemerocher** [comment]
@dstepanov I'm not sure this should be done by default as it adds overhead. We already have `-Dmicronaut.config.files` which allow applies if specified either by an environment variable or a system property.

If we were to consider something like this (maybe `-Dmicronaut.config.dirs` it would need to be disabled by default)

**Comment by dstepanov** [comment]
Maybe if I add a check if dir exists, that should't be a big overhead?

**Comment by graemerocher** [comment]
It is disk I/O on startup which we are trying to minimize as much as possible for serverless. In general the PR is maybe a bit opinionated about the directory location, name etc. 

Another option instead of system properties is to modify `ApplicationContextBuilder` to allow this behaviour to be customized

**Comment by dstepanov** [comment]
Added option to override default config location in a similar way as the boot.
Also, boot by default has `classpath:/config/` it can be easily added.

**Pull request merged**
