### PR TITLE
Cleanup Mdc, Fixes #3106

### LINKED ISSUE #3106: MDC is leaking out to other threads
The MDC is leaking out of the context to other threads.

I am using micronaut 1.3.4 with MdcInstrumenter.
The MDC set in one thread leaks in another thread.
See the failing test there: https://github.com/tom59/micronaut-mdc-issue/blob/master/src/test/java/mn/mdc/instrumenter/MDCTest.java

### Expected Behaviour

The MDC should not leak into other requests.

### Actual Behaviour

The MDC sets for one request ends up in another request.
It is going there: https://github.com/tom59/micronaut-mdc-issue/blob/master/src/main/java/mn/mdc/instrumenter/RequestIdFilter.java#L25

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 1.3.4
- **JDK Version:** 11

### Example Application

- https://github.com/tom59/micronaut-mdc-issue

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by graemerocher** [comment]
The MDC tests are failing still

**Comment by dstepanov** [comment]
Runnable and Callable is now by default set to clean after itself which is correct when used in Executor and ThreadFactory. I find it's strange that all Runnable and Callable is required to celan by default, I think it would be better to call to clean only in specific places like Executor, ThreadFactory and Netty filter.

**Comment by graemerocher** [comment]
Also we would need to add this test to the code base https://github.com/tom59/micronaut-mdc-issue/blob/master/src/test/java/mn/mdc/instrumenter/MDCTest.java

I was not able to get this test to pass with a similar fix to yours

**Comment by dstepanov** [comment]
I have a new PR for 2.0 that uses the test.

**Pull request closed without merging**
