### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by zendern**
Found that just simply pointing SDKMAN to the checked out code dir did not work. So instead figured out what SDKMAN expected in the directory and found where in the project that was generated and updated the instructions accordingly.

### CODE REVIEW

**Comment by jameskleeh** [comment]
I'm not certain this is correct. Here is the link for my current `dev` which does work

`lrwxr-xr-x   1 jameskleeh  staff   65 May 31  2018 dev -> <projectsdir>/micronaut-core/cli/build`

**Comment by zendern** [comment]
> I'm not certain this is correct. Here is the link for my current `dev` which does work
> 
> `lrwxr-xr-x 1 jameskleeh staff 65 May 31 2018 dev -> <projectsdir>/micronaut-core/cli/build`
> 
> In your example what are you unzipping?

I ran a pTML and unzipped the corresponding zip that was created. What's your build dir contain??

**Comment by jameskleeh** [comment]
Yeah you don't have to pTML and unzip anything.

You just clone the repository and `./gradlew cliZip`. That will build the CLI

**Comment by zendern** [comment]
Cool. I'll update the doc to say that then 👍

**Comment by zendern** [comment]
@jameskleeh ^^^ how's that look??

**Pull request merged**
