### PR TITLE
build: open java.lang

### PR DESCRIPTION
**Pull request by sdelamo**
Cherry pick changes from @altro3 in https://github.com/micronaut-projects/micronaut-core/pull/9596

> without it tests doesn't work on Windows and I see exception with SystemLambda

### CODE REVIEW

**Comment by sdelamo** [comment]
@guillermocalvo can you check this helps for you in windows?

**Comment by dstepanov** [comment]
Does it need to be for Kotlin as well?

**Review by guillermocalvo — APPROVED** [review]
> @guillermocalvo can you check this helps for you in windows?

@sdelamo Yes it does; without those changes, some tests fail on Windows with:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final ... accessible: module java.base does not "opens java.lang" to unnamed module @5f683daf
  at com.github.stefanbirkner.systemlambda.SystemLambda$WithEnvironmentVariables.getFieldValue(SystemLambda.java:1380)
  at com.github.stefanbirkner.systemlambda.SystemLambda$WithEnvironmentVariables.getTheCaseInsensitiveEnvironment(SystemLambda.java:1358)
  at com.github.stefanbirkner.systemlambda.SystemLambda$WithEnvironmentVariables.restoreOriginalVariables(SystemLambda.java:1322)
  at com.github.stefanbirkner.systemlambda.SystemLambda$WithEnvironmentVariables.execute(SystemLambda.java:1233)
```

**Comment by sdelamo** [comment]
> Does it need to be for Kotlin as well?

@guillermocalvo can you verify if `inject-kotlin-test` changes are necessary?

**Comment by guillermocalvo** [comment]
> > Does it need to be for Kotlin as well?
> 
> @guillermocalvo can you verify if `inject-kotlin-test` changes are necessary?

@sdelamo I don't think `inject-kotlin-test` needs the changes. Tests pass without them.

**Comment by sdelamo** [comment]
> > > Does it need to be for Kotlin as well?
> > 
> > 
> > @guillermocalvo can you verify if `inject-kotlin-test` changes are necessary?
> 
> @sdelamo I don't think `inject-kotlin-test` needs the changes. Tests pass without them.

@dstepanov  I have removed it from `inject-kotlin-test`

**Review by dstepanov — APPROVED** [review]

**Pull request merged**
