### PR TITLE
test: ReactiveSequenceSpec ignore if jdk17 and CI

### PR DESCRIPTION
**Pull request by sdelamo**
The test is really flaky. 

see: https://github.com/micronaut-projects/micronaut-core/pull/6989/checks?check_run_id=5417864613

or https://github.com/micronaut-projects/micronaut-core/pull/6906/checks?check_run_id=5413571969

### CODE REVIEW

**Comment by timyates** [comment]
I can't see how that is only getting a single book 🤔

I worry this may actually be an issue?

**Comment by sdelamo** [comment]
I think we should revisit it. But for now, I think it is best to ignore it. It is making every build fail.

**Review by timyates — APPROVED** [review]
👍

**Comment by sdelamo** [comment]
I've created an [issue](https://github.com/micronaut-projects/micronaut-core/issues/7010) so that we don't forget.

**Pull request merged**
