### PR TITLE
#2688 Add possibility to include/exclude set of exceptions using base one

### PR DESCRIPTION
**Pull request by Im-dex**

### CODE REVIEW

**Comment by jameskleeh** [comment]
Is the goal here to allow for subclasses to match the value passed to `excludes` ?

**Comment by jameskleeh** [comment]
I think this could be achieved with a single attribute (`includeSubtypes = true`)

**Comment by Im-dex** [comment]
@jameskleeh

> Is the goal here to allow for subclasses to match the value passed to `excludes` ?

Yes, for `includes` or `excludes`

> I think this could be achieved with a single attribute (`includeSubtypes = true`)

It is a little bit less flexible approach I think because then you can't use concrete exception types in a  combination with the base exception types.

**Comment by jameskleeh** [comment]
@Im-dex I think this should target 2.0.0 and just change includes and excludes to include subclasses. One could use `include` to add a subclass of an `exclude`d exception and vice versa. Please update the `breaks.adoc` to document this change.

**Comment by Im-dex** [comment]
@jameskleeh Ok, I'll submit a new PR targeting master branch.

**Pull request closed without merging**
