### PR TITLE
Add propagated context to the reactive controller methods Reactor context

### PR DESCRIPTION
**Pull request by dstepanov**
We already do it for interceptors, but not for controllers.

### CODE REVIEW

**Comment by dstepanov** [comment]
FYI @n0tl3ss

**Review by yawkat — APPROVED** [review]

**Comment by sdelamo** [comment]
please, add prs and issues to GitHub projects

**Comment by sdelamo** [comment]
@dstepanov CI failed

**Review by graemerocher — APPROVED** [review]

**Comment by dstepanov** [comment]
Looking at the reactive context propagation tests, I think those are now very well done. Essentially to have the proper Reactor propagation we should recommend including Micrometer Propagated context dependency.

**Review by yawkat — APPROVED** [review]

**Pull request merged**
