### PR TITLE
Fix for custom validators on nested pojos

### PR DESCRIPTION
**Pull request by tbodor**
Fix for issue #5986 (validator not handling nested custom validations). Note that the example linked from that issue is also missing the @Valid annotation on the list of nested POJOs.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Comment by tchiotludo** [comment]
@graemerocher @jameskleeh this PR was never merge on the 3.x branch, do you need a PR that merge this one ?

**Comment by jameskleeh** [comment]
@tchiotludo In general no we merge up but it doesn't seem like this one exists in 3.2.x so sure

**Comment by AndrejMitrovic** [comment]
Hello,

It seems v2.5.14 was never released?

https://github.com/micronaut-projects/micronaut-core/commit/38754651c6562c7483ba456109182c8ca7d20d1f includes it in `2.5.14-SNAPSHOT`, but this is no longer available in the maven repository?

At least this is what we're getting from our build log:

> Could not resolve dependencies for project io.truweb:commons:jar:0.1: Failed to collect dependencies at io.micronaut:micronaut-inject:jar:2.5.14-SNAPSHOT: Failed to read artifact descriptor for io.micronaut:micronaut-inject:jar:2.5.14-SNAPSHOT: Could not transfer artifact io.micronaut:micronaut-inject:pom:2.5.14-SNAPSHOT from/to ossrh (https://s01.oss.sonatype.org/content/repositories/snapshots): Failed to transfer file https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/micronaut-inject/2.5.14-SNAPSHOT/micronaut-inject-2.5.14-SNAPSHOT.pom with status code 502 -> [Help 1]

Do you think someone could do a 2.5.14 release?

**Pull request merged**
