### PR TITLE
Small RequestHandler refactor

### PR DESCRIPTION
**Pull request by yawkat**
This PR replaces the StreamedHttpRequest passed to RequestHandler by a separate ByteBody argument. This removes the need for some instanceof checks.

This is a small part of #10131, but it makes for annoying merge conflicts, so I want to pull it into 4.3.x. It should have no functional or performance difference.

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Review by timyates — CHANGES_REQUESTED** [review]
Does this break micronaut-session?

https://github.com/micronaut-projects/micronaut-session/blob/fc12567831df42216e947f8c6781df18be7b3cae/session/src/test/groovy/io/micronaut/session/http/CookieHttpSessionStrategySpec.groovy#L51

**Review by timyates — APPROVED** [review]
I guess that's just a test...

**Comment by yawkat** [comment]
huh, i didnt know it had external deps. but since it's just a test we can fix it in session.

**Review by sdelamo — COMMENTED** [review]
There are some sonar issues. Could you check them @yawkat ?

**Comment by yawkat** [comment]
they arent in the diff

**Comment by timyates** [comment]
> they arent in the diff

[This one is](https://sonarcloud.io/project/issues?resolved=false&pullRequest=10326&id=micronaut-projects_micronaut-core&open=AYzUajdG3Wisr06qDPtK) 😜

**Comment by yawkat** [comment]
ive marked it as wontfix

**Pull request merged**
