### PR TITLE
Issue #1846  Heartbeat event is disabled by default

### PR DESCRIPTION
**Pull request by ggavriilidis**
This PR fixes the issue in Micronaut 1.1.3 in which Heartbeat is disabled if not explicitly enabled in the config. This contradicts the documentation which states that Heartbeat is enabled by default. 
See https://github.com/micronaut-projects/micronaut-core/issues/1846 for full details

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the PR. Could you rebase this again 1.1.x branch?

**Comment by ggavriilidis** [comment]
> Thanks for the PR. Could you rebase this again 1.1.x branch?

Thanks for having a look. I have rebased 1.1.x branch into this one

**Comment by graemerocher** [comment]
It is still targeting master.. please target `1.1.x`. Thanks

**Comment by graemerocher** [comment]
Seems you have included all the changes in master in the PR for 1.1.x 

Please rebase properly and include just the changes that resolve the issue. Thanks.

**Comment by ggavriilidis** [comment]
Initially I thought the PR would be against master so I branched off master. As I understand now the PR is against 1.1.x so it is simpler to just branch off the newest version of 1.1.x, apply my changes and create a new PR. 
The new PR is ready: 
https://github.com/micronaut-projects/micronaut-core/pull/1855
We could close this one if you have no objections and reference the new PR in the issue.
Thanks.

**Pull request closed without merging**
