### PR TITLE
Add a test module to verify simple native execution

### LINKED ISSUE #7691: Create test module to verify simple native image generation and execution
The goal is to catch errors such as https://github.com/micronaut-projects/micronaut-core/issues/7671 earlier. 

I think we could add a submodule which use the [Gradle graalvm plugin](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#testing-support) to run a [Junit native test via  `./gradlew nativeTest`](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#testing-support)

I think we could do `check` depends on `nativeTest` for that module. 

A test such as: 

```java
package com.example;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import java.util.Collections;
import java.util.Map;

@Controller
public class HomeController {

    @Get
    Map<String, Object> index() {
           return Collections.singletonMap("message", "Hello World");
    }
}

```

```java
package com.example;

import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@MicronautTest
class HomeControllerTest {

    @Inject
    @Client("/")
    HttpClient httpClient;

    @Test
    void helloWorld() {
        assertEquals("Hello World",
                httpClient.toBlocking().retrieve("/", Map.class).get("message"));
    }
}
```

should help us catch most issues. 

It would be good to create such a module, branching of [the commit which fixed native image](https://github.com/micronaut-projects/micronaut-core/commit/204e4d1de554e5821a462b46f5dc88565e5ce35b) and see if the module test fails.

### PR DESCRIPTION
**Pull request by timyates**
We detect issues with native compilation quite far down the release chain.

This causes problems, and delays when releasing a new version of Micronaut, especially minor or major releases.

This commit adds a new module test-suite-graal which runs nativeTest against a simple micronaut application.

This should pass once https://github.com/micronaut-projects/micronaut-core/pull/8125 and https://github.com/micronaut-projects/micronaut-core/pull/8126 are merged into 4.0.x and back into here

### CODE REVIEW

**Comment by timyates** [comment]
I think there's also an issue with caffeine if I pull in `project(':session')`... Investigating

**Comment by timyates** [comment]
Fix for AttributeKey is here https://github.com/micronaut-projects/micronaut-core/pull/8125

**Comment by timyates** [comment]
Fix for Caffeine errors is here: https://github.com/micronaut-projects/micronaut-core/pull/8126

**Comment by timyates** [comment]
I think we have issues if I pull in :management, but I am not sure what they are

**Review by sdelamo — APPROVED** [review]

**Comment by timyates** [comment]
Cannot get this to work at the moment with 4.0.0-SNAPSHOT in such flux

I've reproduced for 3.7.x over here https://github.com/micronaut-projects/micronaut-core/pull/8280 and we can fix it up when it gets merged back in

**Pull request closed without merging**
