### PR TITLE
Deprecate HttpStatus.UNORDERED_COLLECTION

### PR DESCRIPTION
**Pull request by yawkat**
For #8123

### CODE REVIEW

**Review by timyates — COMMENTED** [review]
Should we add

```
TOO_EARLY(425, "Too Early"),
```

To give users a migration path?

**Comment by timyates** [comment]
Is adding an enum binary compatible? 🤔 🤯

**Comment by yawkat** [comment]
we dont have precedent for multiple enum values with the same code, not sure. adding an enum value is binary compatible.

i was going to suggest users use numeric status codes, but apparently #8147 is 4.0 only

**Comment by yawkat** [comment]
though i guess people *can* still use numeric status codes here, since 425 is not invalid in either 3.x or 4.0, it's just represented by different enum values

**Comment by timyates** [comment]
Trying to see what JapiCmp says about

```diff
diff --git a/http/src/main/java/io/micronaut/http/HttpStatus.java b/http/src/main/java/io/micronaut/http/HttpStatus.java
index 81ec802227..b5901afb12 100644
--- a/http/src/main/java/io/micronaut/http/HttpStatus.java
+++ b/http/src/main/java/io/micronaut/http/HttpStatus.java
@@ -74,6 +74,7 @@ public enum HttpStatus implements CharSequence {
      */
     @Deprecated
     UNORDERED_COLLECTION(425, "Unordered Collection"),
+    TOO_EARLY(425, "Too Early"),
     UPGRADE_REQUIRED(426, "Upgrade Required"),
     PRECONDITION_REQUIRED(428, "Precondition Required"),
     TOO_MANY_REQUESTS(429, "Too Many Requests"),
```

But it's currently not running 😿

**Comment by timyates** [comment]
@yawkat japicmp says the above diff change is fine (once you work around Gradle bug above locally)...  Can you think of an edge case where it won't work?

**Comment by yawkat** [comment]
No, unless you're relying on an exhaustive switch, or on the ordinals of other status codes

**Review by timyates — APPROVED** [review]

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
