### PR TITLE
ErrorHandlerStringTest fix

### PR DESCRIPTION
**Pull request by n0tl3ss**
Test should be passing because string "hello" is not `MediaType.APPLICATION_JSON` type. It should be  `MediaType.TEXT_PLAIN`

### CODE REVIEW

**Comment by timyates** [comment]
Is this another breaking change of behaviour that needs documenting here https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/src/main/docs/guide/appendix/breaks.adoc#exceptionhandler-with-pojo-response-type-no-longer-results-in-an-error-response

?

**Comment by sdelamo** [comment]
@n0tl3ss I think the test was verifying the that default content type for a exception handler returning string is application/json 

Why did you change the test?

**Comment by n0tl3ss** [comment]
I think we should return correct content type of response. String "hello" is not json it makes more sense to be text/plain. I edited test with @Produce annotation but maybe we want to return correct media type by default.

**Comment by sdelamo** [comment]
> I think we should return correct content type of response. String "hello" is not json it makes more sense to be text/plain. I edited test with @produce annotation but maybe we want to return correct media type by default.

we could change `hello` with `{"message": "hello"}"` but I don't think we should change the test and add annotations. The goal of the test is to verifies what is the default content type for a return String when no `@Produces` annotations  are present.

**Comment by graemerocher** [comment]
the default if no produces is specified is `application/json` and as @n0tl3ss said "hello" is not valid JSON

**Comment by sdelamo** [comment]
@n0tl3ss I have changed the string to be a valid JSON and removed the @Produces annotation. Let me know if you are ok.

**Pull request merged**
