### PR TITLE
KSP: Visit synthetic properties in factories with advice

### PR DESCRIPTION
**Pull request by graemerocher**
In order for advice to apply to Groovy/Kotlin synthetic properties we need to visit these in the implementation of `@Factory`. This replicates the same logic as for introduction advice.

### CODE REVIEW

**Comment by timyates** [comment]
Tested it against the [guide for configuration](https://scans.gradle.com/s/6oa3veavk726s/console-log?task=:kspKotlin), and the [rabbit guide book project](https://scans.gradle.com/s/o7d4s6rachdgs/console-log?task=:kspKotlin), both failed with ksp errors 🤔

**Comment by jeffscottbrown** [comment]
Is this a change that will likely result in an RC2 prior to GA?

Thank you for any input!

**Comment by dstepanov** [comment]
I did fix some of the problems, but still we have failures. Some of the tests don't expect synthetic methods. We might need to add more options to the methods query. Right now we have duplicate methods provided from the properties and the query methods. We might want to have `ALL_METHODS.includePropertyMethods` or `.includeSynthetic`

**Comment by dstepanov** [comment]
We should validate that the logic is consistent with the Groovy implementation.

**Comment by jeffscottbrown** [comment]
btw... my question above regarding RC2 isn't expressing a preference in favor of RC2 or expressing concern about doing an RC2 or anything like that. I am only asking for planning purposes.  

Thank you!

**Comment by sdelamo** [comment]
> Is this a change that will likely result in an RC2 prior to GA?

No.

**Comment by timyates** [comment]
Still seeing mockito failures with this in the rabbitmq guide

```
org.mockito.exceptions.misusing.NotAMockException: 
Argument passed to verify() is of type $BookControllerTest$AnalyticsClient0$Definition$Intercepted and is not a mock!
Make sure you place the parenthesis correctly!
See the examples of correct verifications:
    verify(mock).someMethod();
    verify(mock, times(10)).someMethod();
    verify(mock, atLeastOnce()).someMethod();
	at app//example.micronaut.BookControllerTest.testMessageIsPublishedToRabbitMQWhenBookFound(BookControllerTest.kt:31)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
```

It works with kapt 🤔

**Comment by graemerocher** [comment]
@dstepanov changed the fix to use the existing synthetic properties stuff, should work for Groovy too

**Comment by graemerocher** [comment]
@timyates can you retest the current changes

**Comment by timyates** [comment]
Will try asap...  Groovy compilation seems to be failing here with `Unknown annotation metadata`?

**Comment by timyates** [comment]
So, I believe this was the originator of this PR? https://github.com/micronaut-projects/micronaut-serialization/issues/513

Running the `micronaut-configuration` guide with this branch published to maven local, all the tests pass!

https://scans.gradle.com/s/xz4jioxbmnt46/tests/overview

We still have an issue testing the rabbit guide with this branch [published to mavenLocal](https://scans.gradle.com/s/ibwjpiiyfk64m/dependencies?focusedDependency=WzAsMTEsMixbMCwxMSxbMl1dXQ&toggled=W1swXSxbMCwxMV1d), I still see the [issues with mockito](https://scans.gradle.com/s/ibwjpiiyfk64m/tests/overview?outcome=failed)

**Comment by jeffscottbrown** [comment]
> No.

Thank you for the info @sdelamo.

**Comment by timyates** [comment]
Testing against the k8s guide where we have

```
    @get:Get("/orders")
    val orders: List<Order>
```

Think we just get the mockito error...

Is it the case that when a Client is constructed from

```
@Client("orders") // <1>
interface OrdersClient {

    @Post("/orders")
    fun createOrder(@Body order: Order?): Order
}
```

the `createOrder` method is not `open`? 🤔

**Review by dstepanov — APPROVED** [review]

**Review by timyates — APPROVED** [review]
Any ideas on https://github.com/micronaut-projects/micronaut-core/pull/9553#issuecomment-1630849539 ?

**Comment by dstepanov** [comment]
@timyates What exatly is the problem there?

**Comment by timyates** [comment]
@dstepanov When we have a Client defined as so:

```
@Client("orders") // <1>
interface OrdersClient {

    @Post("/orders")
    fun createOrder(@Body order: Order?): Order
}
```

Does the generated class have an `open` createOrder function? And is it open itself?

Trying to think why

```
`when`(ordersClient.createOrder(any())).thenReturn(order)
```

Fails with 

```
Misplaced or misused argument matcher detected here:

-> at example.micronaut.GatewayControllerTest.createOrder(GatewayControllerTest.kt:134)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(any());
    verify(mock).someMethod(contains("foo"))

This message may appear after an NullPointerException if the last matcher is returning an object 
like any() but the stubbed method signature expect a primitive argument, in this case,
use primitive alternatives.
    when(mock.get(any())); // bad use, will raise NPE
    when(mock.get(anyInt())); // correct usage use

Also, this error might show up because you use argument matchers with methods that cannot be mocked.
Following methods *cannot* be stubbed/verified: final/private/equals()/hashCode().
Mocking methods declared on non-public parent classes is not supported.

Path Taken: GatewayControllerTest.setOrdersClient([OrdersClient <set-?>])
```

**Comment by dstepanov** [comment]
We don't generate anything different for KSP. If it works for Java it should work for Kotlin. Do you use https://github.com/mockito/mockito-kotlin ?

**Comment by timyates** [comment]
> We don't generate anything different for KSP. If it works for Java it should work for Kotlin. Do you use https://github.com/mockito/mockito-kotlin ?

Yeah tried with that and no difference... We use the `all open` plugin with kapt but it doesn't work with ksp, and I remember @yawkat did something to work around this limitation. I guess I wonder if this workaround also works for things generated from interfaces it abstract classes

Or maybe it's something totally different...

**Comment by dstepanov** [comment]
Can you try mock a method without a body?

**Comment by timyates** [comment]
It's specifically when we make use of `any()` in the matcher...  This works

```
        `when`(usersClient.getById(user.id)).thenReturn(user)
```

But this shows the above error

```
        `when`(ordersClient.createOrder(any())).thenReturn(order)
```

I don't know enough Mockito (or Kotlin it seems) to know why it's failing with KSP

Not sure if this answers

>  Can you try mock a method without a body?

If not, what do you mean?

**Comment by dstepanov** [comment]
Right, so I guess the open plugin somehow doesn't work so it cannot create a body mock. Maybe try `any(Order.class)`

**Comment by timyates** [comment]
> Right, so I guess the open plugin somehow doesn't work so it cannot create a body mock. Maybe try `any(Order.class)`

Yeah, I'd tried that

```
        `when`(ordersClient.createOrder(any(Order::class.java))).thenReturn(order)
```

Same error

**Comment by dstepanov** [comment]
Try to open the class file of `Order` and see if it's final

**Comment by timyates** [comment]
@dstepanov It is, but if I change it from a `data class` to an `open class`, it makes no difference :-(

**Pull request merged**
