### PR TITLE
Use the version of projectreactor from micronaut-reactor

### LINKED ISSUE #7638: Remove manage-reactor as it is in the BOM
### Issue description

Once https://github.com/micronaut-projects/micronaut-reactor/pull/201 is merged and 2.3.0 is out, we should add the BOM to the dependency catalog, and remove `managed-reactor`

Check the TOML keeps the same names with `./gradlew pAPTBR`

### PR DESCRIPTION
**Pull request by timyates**
Instead of having to keep it aligned.

@melix is this right?  Project reactor no longer appears in the bom-pom

### micronaut-bom Pom changes

```diff
82d81
<     <reactor.version>3.4.18</reactor.version>
119c118
<     <micronaut.reactor.version>2.2.2</micronaut.reactor.version>
---
>     <micronaut.reactor.version>2.3.0</micronaut.reactor.version>
637,641d635
<         <groupId>io.projectreactor</groupId>
<         <artifactId>reactor-core</artifactId>
<         <version>${reactor.version}</version>
<       </dependency>
<       <dependency>
```

### micronaut-bom toml changes

```diff
78c78
< micronaut-reactor = "2.2.2"
---
> micronaut-reactor = "2.3.0"
101d100
< reactor = "3.4.18"
553c552,553
< reactor = {group = "io.projectreactor", name = "reactor-core", version.ref = "reactor" }
---
> reactor = {group = "io.projectreactor", name = "reactor-core", version = "" }
> reactor-core = {group = "io.projectreactor", name = "reactor-core", version = "" }
```

I suspect not, so creating this as a draft

Closes #7638

### CODE REVIEW

**Comment by melix** [comment]
Well both the BOM and catalog have breaking changes, so I guess not. This could be done for 4.0.

**Comment by timyates** [comment]
Moved it to 4.0.0 👍

**Review by sdelamo — APPROVED** [review]

**Comment by dstepanov** [comment]
IMHO reactor is so essential to the core, I wouldn't move the version away. We would need to bump Micronaut-Reactor all the time which I don't think is needed.

**Comment by sdelamo** [comment]
I agree with @dstepanov I think it is better to keep core decoupled from any module.

**Pull request closed without merging**
