### PR TITLE
Support for repeatable qualifiers

### PR DESCRIPTION
**Pull request by graemerocher**
* Optimizes named qualifier creation
* Optimizes annotation qualifier creation
* Optimizes composite qualifier creation
* Adds support for repeatable qualifiers

Repeatable qualifiers are a CDI requirement https://github.com/micronaut-projects/micronaut-core/issues/4658

### CODE REVIEW

**Comment by dstepanov** [comment]
Can we have a simple test that checks that it's possible to read repeatable annotations from `InjectionPoint`?

**Comment by graemerocher** [comment]
There is no `getQualifier()` method on `InjectionPoint`?

**Comment by dstepanov** [comment]
I'm thinking of a scenario where would you like to extract all variations of `@Location(...)` and inject something accordingly.

**Comment by graemerocher** [comment]
There is no general API today for doing detecting the type of qualifier and materializing a `Qualifier` instance from the metadata not for repeatable annotations, nor for any other type of qualifier.

Any code that uses the `InjectionPoint` to materialize qualifiers would have to current explicitly handle each case accordingly. I don't see that as in scope for this PR, perhaps it belongs as part of the repeatable annotation in metadata PR but not this one.

**Review by dstepanov — APPROVED** [review]

**Pull request merged**
