### PR TITLE
Use 'extension' field in exception message because it more informative then 'fileName'

### PR DESCRIPTION
**Pull request by aleksandr-chermashentsev**
Fix for issue https://github.com/micronaut-projects/micronaut-core/issues/5418

### CODE REVIEW

**Comment by graemerocher** [comment]
The tests will need updating too

**Comment by jameskleeh** [comment]
The filename is shown because the extension doesn't tell you what file had the issue. You could improve this by showing both

**Comment by aleksandr-chermashentsev** [comment]
> The filename is shown because the extension doesn't tell you what file had the issue. You could improve this by showing both

Fixed with using absolute path of configuration file in exception

**Comment by jameskleeh** [comment]
I can see how it may be undesirable for an absolute file path to be logged. Please just use the file name

**Comment by aleksandr-chermashentsev** [comment]
I have ran tests locally and they are good. What's wrong with build action?

**Comment by jameskleeh** [comment]
Another PR made this change

**Pull request closed without merging**
