### PR TITLE
KSP: use `overrides` method instead of `findOverridee()`

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by graemerocher** [comment]
broken?

**Comment by dstepanov** [comment]
I have deleted all injection private-package tests. Kotlin doesn't have a package-private scope.

**Comment by graemerocher** [comment]
What does this fix?

**Comment by dstepanov** [comment]
Nothing was reported, and two tests got un-pending after this change.
I noticed that this method exists while fixing some other KSP stuff, and I assume it's faster than the previous one.

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
