### PR TITLE
feat: disable endpoints filter via configuration

### PR DESCRIPTION
**Pull request by sdelamo**
This is useful if you want to avoid loading the endpoints filter because you are going to handle security with your own filter.

### CODE REVIEW

**Comment by graemerocher** [comment]
I don't think we need a whole new configuration properties bean just for this, also it is not even used in the code.

**Comment by sdelamo** [comment]
The advantage of having a `@ConfigurationProperties` file is that it generates documentation automatically. Thus, users are able to discover this feature.

**Comment by graemerocher** [comment]
There is already https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/management/src/main/java/io/micronaut/management/endpoint/EndpointDefaultConfiguration.java which can be reused rather than adding a whole new configuration for 1 property

**Comment by sdelamo** [comment]
I thought about adding it to `EndpointDefaultConfiguration`. However, I thought the prefix `endpoints.all` may confuse users. I think `endpoints.filter.enabled` is nicer than `endpoints.all.filter-enabled` or `endpoints.all.filter` .

**Comment by jameskleeh** [comment]
We already have a way to effectively disable the filter and adding this configuration creates two ways to do the same thing. For most users the fact that this is done via a filter is an implementation detail so adding the config exposes the implementation. I don't see an issue with the current process so I think we should close this

**Pull request closed without merging**
