### PR TITLE
Update bouncy castle bcpkix

### PR DESCRIPTION
**Pull request by viniciusxyz**
The version bcpkix-jdk15on don´t work with java 21, error:

```sh
Caused by: java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate. See debug log for the root cause.
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:254)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:166)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:115)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:90)
	at io.micronaut.http.server.netty.ssl.SelfSignedSslBuilder.getKeyStore(SelfSignedSslBuilder.java:67)
	at io.micronaut.http.server.netty.ssl.AbstractServerSslBuilder.getKeyManagerFactory(AbstractServerSslBuilder.java:161)
	... 36 common frames omitted
	Suppressed: java.lang.NoClassDefFoundError: org/bouncycastle/cert/X509v3CertificateBuilder
		at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:240)
		... 41 common frames omitted
	Caused by: java.lang.ClassNotFoundException: org.bouncycastle.cert.X509v3CertificateBuilder
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
		... 42 common frames omitted
Caused by: java.lang.UnsupportedOperationException: OpenJdkSelfSignedCertGenerator not supported on the used JDK version
	at io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator.generate(OpenJdkSelfSignedCertGenerator.java:167)
	at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:251)
	... 41 common frames omitted
```

Update to bcpkix-jdk18on fix issue and according to the bouncy castle documentation, this version is suported for java 8+

### CODE REVIEW

**Comment by sdelamo** [comment]
@viniciusxyz do you have a link to the bouncy castle documentation ?

**Comment by viniciusxyz** [comment]
> @viniciusxyz do you have a link to the bouncy castle documentation ?

Sure https://www.bouncycastle.org/download/bouncy-castle-java/

image

**Comment by viniciusxyz** [comment]
I just tested again and strangely now I worked with bcpkix-jdk15on, maybe there was some incorrect caching in the IDE, anyway updating the library might be a good idea since maven central also shows that this was moved to jdk18on


image


image

Even the latest version of jdk15 contains several vulnerabilities that appear to have been fixed later in jdk18

**Review by sdelamo — APPROVED** [review]

**Comment by drwille** [comment]
@viniciusxyz should these lines have been updated as well?
https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/gradle/libs.versions.toml#L4
https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/gradle/libs.versions.toml#L180

**Comment by viniciusxyz** [comment]
> @viniciusxyz should these lines have been updated as well? https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/gradle/libs.versions.toml#L4 https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/gradle/libs.versions.toml#L180

I imagine so, I don't know what TOML is used for, probably some template file or something like that, I didn't pay attention to that, but anyway since the edition numerous versions of bouncy have been released including vulnerability fixes so I think it's time to update again, can you open the MR for this? If not as soon as I have some time I will do it

image

**Pull request merged**
