### PR TITLE
Bump Micronaut Test Resources version

### PR DESCRIPTION
**Pull request by melix**

### CODE REVIEW

**Comment by graemerocher** [comment]
Shouldn't this target 3.7.x?

**Comment by melix** [comment]
I was pretty conservative by targetting 3.6.x but we can target 3.7.

**Comment by sdelamo** [comment]
> I was pretty conservative by targetting 3.6.x but we can target 3.7.

Yes, it should target 3.7.x. We don't bump minor version of modules in patch releases.

**Review by sdelamo — APPROVED** [review]
I have changed the base and resolved the merge.

**Pull request merged**
