### PR TITLE
Implement enum constant in kotlin element factory

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by altro3** [comment]
@dstepanov Hi! Could you help with this change? Without it we can't use micronaut-openapi with KSP for enums. But I did something wrong and now I have this exception in test:

изображение

Need help!

**Comment by altro3** [comment]
@dstepanov Continue #9771 here

**Comment by dstepanov** [comment]
Please add test

**Comment by altro3** [comment]
@dstepanov done, but this test works fine.... When I try to use this snapshot inside test project, i have this error:
изображение

**Comment by dstepanov** [comment]
I will check

**Comment by altro3** [comment]
@dstepanov I figured out what the problem was and fixed it. Now everything works correctly, checked with micronaut-openapi :-)

**Comment by dstepanov** [comment]
Thanks!

**Pull request merged**
