### PR TITLE
Handler for wrapped HttpStatusExceptions 

### PR DESCRIPTION
**Pull request by ratcashdev**
wrapped by CompletionExceptions (used by CompletableFutures) to solve https://github.com/micronaut-projects/micronaut-core/issues/2973

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the PR, can you provide an example of what problem this PR is trying to fix? When is `HttpStatusException` causing a problem?

**Comment by ratcashdev** [comment]
@graemerocher see the linked issue for the problem description: https://github.com/micronaut-projects/micronaut-core/issues/2973

**Comment by ratcashdev** [comment]
@jameskleeh does line 274 have any relation to https://github.com/micronaut-projects/micronaut-core/blob/ae5430bfec4cd2fe838e2df874509b0403158795/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L416 ? Or one is for sync calls and the other for async?

**Comment by jameskleeh** [comment]
@ratcashdev That line 416 is only invoked if the exception handler throws an exception, so I don't think that has any bearing on this fix.

>  should we do a separate PR, or revert the unnecessary changes in this one?

I would say just revert the changes here and use the existing PR

> would the implemention in method exceptionCaughtInternal correctly call the handler

Yes it will

**Comment by ratcashdev** [comment]
@jameskleeh so will this get into 1.3.4?

**Pull request merged**
