### PR TITLE
Improved Eureka registration support

### LINKED ISSUE #1021: Improve Eureka support
Eureka client should be improved in order to allow better customization and to support containerized environments (for example AWS ECS).

I'm willing to contribute the code, i need to implement it anyway for my needs.

### Motivation

If micronaut service is started in docker container that container might contain bridged networking and hostname that is not reachable/resolvable by eureka server or clients that want to use them. For example, machine running docker container might have ip address `1.2.3.4` and docker container exposed port `9090`, but process in container has actual ip address `172.28.0.100` and listening port `8080`. In this case micronaut application should register in eureka as ip `1.2.3.4` and listening port `9090`, otherwise clients will try to contact unreachable address/port.

### Task List

- [x] improve default eureka application id, because current implementation doesn't work well if there are multiple instances of the same app are registered in eureka
- [x] add ability to register application in eureka under different name than `${micronaut.application.name}`
- [x] add ability to register with different hostname/ip-addr than `${micronaut.server.addr}`
- [x] add ability to register with different listening port than `${micronaut.server.port}`

### PR DESCRIPTION
**Pull request by bfg**
* eureka instance application name, hostname, ip address and exposed
  port can be now customized via configuration
* updated eureka related documentation

Closes #1021

### CODE REVIEW

**Comment by bfg** [comment]
@graemerocher since you've added this to 1.0.3 milestone, should i open this pr against `1.0.x` branch?

**Comment by graemerocher** [comment]
Yes that would help

**Comment by bfg** [comment]
done.

**Comment by graemerocher** [comment]
I have made some changes to the code to simplify configuration and remove the manual lookups. I also removed the change to disable `explicitInstanceId` is that would result in `ServiceIdGenerator` no longer working which is a breaking change.

I also restored the original constructor to avoid binary compatibility problems.

If you wish to verify the fix you can do so by adding the snapshot repo to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.0.3.BUILD-SNAPSHOT'
    }
}
```

**Comment by bfg** [comment]
I'll check in a few minutes. I think that some of your changes are a bit tricky (instance-id) generation.

**Comment by graemerocher** [comment]
Sorry I think maybe the build didn't complete and you used an out of date snapshot. Note that you should also specify `prefer-ip-address:true`. Please wait for https://travis-ci.org/micronaut-projects/micronaut-core/builds/470912034 to go green and try again with the newest snapshot

Sorry for the hassle.

**Comment by bfg** [comment]
@graemerocher okay, i'll retry a bit later.

I firmly believe that `prefer-ip-address:true` is not the right way of doing it, because we should not force users to register to eureka using ip address as instance hostname; please consider the scenario that micronaut app, running on AWS ECS which uses bridged networking and uses SSL certificate gets registered to eureka; This will mean that you'll have to create certificates that contain ip addresses in subject altnames.

This is exact reason why i've implemented it in a way i did. It adds flexibility, makes everything configurable from the outside (our startup scripts detect runtime environment and mapped networking and sets appropriate system properties) while retaining original behavior if configuration is not overriden.

**Comment by graemerocher** [comment]
The change to always return `true` from `explicitInstanceId ` removes the interaction with `ServiceIdGenerator` and actually reduces flexibility since the strategy is now hard coded and if you look at the implementation of that it may contain heuristics to work out the instance id for the cloud environment. With your change it is no longer possibly to replace the implementation with another bean.

See https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/discovery/DefaultServiceInstanceIdGenerator.java

As far as I see the only change to your tests that my changes introduce is that `prefer-ip-address` must be `true`. If this is not desirable we need another way to enable/disable `ServiceIdGenerator` as part of these changes, otherwise this results in the breaking change described above.

**Pull request merged**
