### PR TITLE
Upgrade reactive-pg-client

### PR DESCRIPTION
**Pull request by aaloise**
Version 0.11.1 was recently released.

### CODE REVIEW

**Comment by aaloise** [comment]
Vertx version had to be upgraded to 3.6.2, since reactive-pg-client was build on top of it. Now it passes.

**Comment by jameskleeh** [comment]
Unfortunately vertx 3.6 includes breaking changes, which means we can't upgrade this in a non major release. https://github.com/vert-x3/wiki/wiki/3.6.0-Deprecations-and-breaking-changes

**Comment by graemerocher** [comment]
I am not sure about that. We don’t have expose Vertx directly. Only the driver API

**Comment by jameskleeh** [comment]
Updating the client would force users to upgrade otherwise they would encounter the exception found in this build. That is a breaking change as far as I can see

**Comment by graemerocher** [comment]
I don’t think so because the dependency is transitive of the postgres-reactive configuration. Users shouldn’t have to change anything

**Comment by jameskleeh** [comment]
That is assuming they have no code that is using vertx directly

**Comment by aaloise** [comment]
Assuming that this would be a breaking change... it's only applicable between major versions?

I understand @jameskleeh point of view, but a "breaking change" section explaining this wouldn't be enough? I'm pointing this out because Vert.x 4 will bring a **lot** of deprecated code and breaking changes, so I think that v4 could be actually seen as a really breaking change.

But, it's just a thought. You guys decide what is best for the framework.

**Comment by jameskleeh** [comment]
> a "breaking change" section explaining this wouldn't be enough?

No. We are following semantic versioning. https://semver.org/

**Comment by aaloise** [comment]
Ok. It's your call.

**Comment by graemerocher** [comment]
This was fixed here https://github.com/micronaut-projects/micronaut-sql/commit/ba0a8070ae1e6f7f6f257149ad6101a529cb7bd6

**Pull request closed without merging**
