### PR TITLE
Do not auto configure DataSourceTransactionManagerFactory if  is present.

### PR DESCRIPTION
**Pull request by RaviH**
https://github.com/micronaut-projects/micronaut-core/issues/787

### CODE REVIEW

**Comment by RaviH** [comment]
I have signed the CLA but not sure why it's not updating here. Let me create the PR again.

**Comment by graemerocher** [comment]
@RaviH it is probably because you need to configure your git email and username for when you push your commits. See https://help.github.com/articles/setting-your-commit-email-address-in-git/

**Comment by RaviH** [comment]
Is something missing?

image

**Comment by graemerocher** [comment]
looks ok now, but maybe the commits you did without these settings?

**Pull request closed without merging**
