### PR TITLE
use Milestone versions

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you check why this fails?

**Comment by timyates** [comment]
Failing scan here (obfuscated in the action) https://ge.micronaut.io/s/cizejqpdmkbeq

**Comment by timyates** [comment]
The management test was failing as micronaut-sql was adding a constraint on a newer version of H2 than we had in core (so the version string was different)

I've fixed the version string in the test, and aligned the version here to match that in micronaut-sql

**Comment by timyates** [comment]
For the KSP error, we need M3 of the validation library with https://github.com/micronaut-projects/micronaut-validation/commit/eea7bd05b8761fccf13f5307f8b9d512a0e0011e

**Pull request merged**
