### PR TITLE
Enable to disable KubernetesDiscoveryClient

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by graemerocher** [comment]
The motivation for this is?

**Comment by sdelamo** [comment]
I think in general it is a good practice to leave users the ability to disable beans (via configuration) specially beans which implement a type which are almost impossible to disable unless you provide with a dummy replacement. 

For Kubernetes, users may use this bean:

https://github.com/micronaut-projects/micronaut-kubernetes/blob/master/kubernetes-discovery-client/src/main/java/io/micronaut/kubernetes/discovery/KubernetesDiscoveryClient.java

I think that it would be good for users to control which bean is loaded as `DiscoveryClient`.

**Comment by alvarosanchez** [comment]
I am thinking that the bean you linked should `@Replaces` the one in core.

**Comment by sdelamo** [comment]
> I am thinking that the bean you linked should `@Replaces` the one in core.

Independently of the `KubernetesDiscoveryClient.java` replacing the other one, I think having the ability of disabling via configuratio the KubernetesDiscoveryClient  bean based on  Env. Variables  n is a good idea.

**Comment by graemerocher** [comment]
Since this client has been deprecated and scheduled for removal I don't think we need to merge this.

**Pull request closed without merging**
