### PR TITLE
Array binding

### PR DESCRIPTION
**Pull request by jameskleeh**
The change here that affects apps not using `list = true` is that list and map values will have their collapsed keys added to the property catalog.

`foo: ['abc', 'def']` would previously result in a single entry `foo` in the catalog. Now it will result in 3 entires. 

1. The same `foo` entry as before
2. `foo[0]` with a value of `abc`
3. `foo[1]` with a value of `def`

I'll add some documentation after this change is OK'd

### CODE REVIEW

**Comment by graemerocher** [comment]
Looks good, probably just need to rebase to get the tests passing

**Comment by graemerocher** [comment]
Can you remove the commits that modify the workflow files

**Comment by jameskleeh** [comment]
@graemerocher I just had to merge master, done

**Comment by graemerocher** [comment]
I guess the only thing that is missing here is documentation

**Pull request merged**
