### PR TITLE
Merge up 4.0.x into 4.1.x

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@dstepanov can you check the failures. Attempting to merge-up causes a lot of tests to start failing https://ge.micronaut.io/s/eozd3bv5w4jck I assume it is #9752

**Comment by dstepanov** [comment]
@sdelamo Where is it failing? Looks like some Kotlin stuff

**Comment by sdelamo** [comment]
It does not fail on CI but it fails for me on MacOS:

./gradlew :test-suite-kotlin:test

https://ge.micronaut.io/s/xo37irwltiki2

Are you running MacOS @dstepanov ? 

@timyates can you verify if it fails for you?

**Comment by dstepanov** [comment]
It passes or me https://ge.micronaut.io/s/xp72qms7gchgy
You might have some corrupted cache

**Comment by timyates** [comment]
@sdelamo Passes for me too...  Even if I turn off PTS and the build cache

https://ge.micronaut.io/s/apdygb2lyztcg

**Comment by sdelamo** [comment]
🤷‍♂️. I will merge it if it passes.

**Pull request merged**
