### PR TITLE
Merge 4.2.x into 4.3.x

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@yawkat I am trying to merge 4.2.x into 4.3.x. However, `io.micronaut.http.server.netty.stream.StreamPressureSpec`, introduced in [#10138](https://github.com/micronaut-projects/micronaut-core/pull/10138) fails. Is this something you could investigate?

**Comment by yawkat** [comment]
it passes for me

**Comment by sdelamo** [comment]
It fails for me consistently MacOS Sonoma. OpenJDK Runtime Environment Corretto-17.0.8.7.1 (build 17.0.8+7-LTS)

https://ge.micronaut.io/s/dpdmnicl7tdcg

Can it be failing only on MacOS? @graemerocher @timyates could either or you the following test passes or fails locally: 

./gradlew :http-server-netty:test --tests io.micronaut.http.server.netty.stream.StreamPressureSpec

**Comment by timyates** [comment]
@yawkat fails for me too on OSX. Seems to just hang

And then fails after 5 minutes https://ge.micronaut.io/s/2cclcontziw3u/tests/task/:http-server-netty:test/details/io.micronaut.http.server.netty.stream.StreamPressureSpec/consumer%20pressure?top-execution=1

**Comment by sdelamo** [comment]
[I ignored it on MacOS](https://github.com/micronaut-projects/micronaut-core/pull/10329/commits/2f3d519da8854613355fe14433901f001a1997ca)

**Pull request merged**
