### PR TITLE
Keep a copy of the features when creating a federation

### LINKED ISSUE #1541: CLI - create-federation does not include features in multiple services
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

mn create-federation fed --features aws-api-gateway,security-jwt,file-watch --services picard,kirk

### Expected Behaviour

I believe the expected behavior is a root directory called 'fed' with two subprojects: 'picard' and 'kirk'. Each subproject should include a sam.yaml file generated by the aws-api-gateway feature and should include file watch and jwt config in application.yml.

### Actual Behaviour

Sam.yml and config in application.yml was only included in one of the projects. However, it appears as if both build.gradle files in the subprojects have the same dependencies.

### Environment Information

- **Operating System**: macOS Mojave 10.14.4
- **Micronaut Version:** 1.1.0
- **JDK Version:** 1.8.0_201

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #1541

### CODE REVIEW

**Comment by jameskleeh** [comment]
I'm confused on how this change would have any affect. How does assigning the features to a variable change anything?

**Comment by jameskleeh** [comment]
Fixed this differently

**Comment by ilopmar** [comment]
@jameskleeh The change just saves a copy of the list of features. When doing:
```
mn create-federation fed --features aws-api-gateway,security-jwt,file-watch --services picard,kirk
```
Only the first service (`picard`) is created correctly. For `kirk` the list of features is empty and it's created only with the gradle skeleton but without any features. I tried with the latest changes and the issue still happends.
```
fed 
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
├── kirk
│   ├── build.gradle
│   ├── Dockerfile
│   ├── micronaut-cli.yml
│   ├── settings.gradle
│   └── src
│       └── main
│           └── resources
│               └── application.yml
├── picard
│   ├── build.gradle
│   ├── Dockerfile
│   ├── micronaut-cli.yml
│   ├── sam.yaml
│   ├── settings.gradle
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── picard
│       │   │       ├── Application.java
│       │   │       └── StreamLambdaHandler.java
│       │   └── resources
│       │       ├── application.yml
│       │       └── log4j2.xml
│       └── test
│           └── java
│               └── picard
└── settings.gradle
```

**Comment by ilopmar** [comment]
Forget about the this. It's working properly.

**Pull request closed without merging**
