### PR TITLE
Update what's new guide

### PR DESCRIPTION
**Pull request by graemerocher**

### CODE REVIEW

**Comment by graemerocher** [comment]
@jameskleeh please update this PR with the MQTT stuff

**Comment by graemerocher** [comment]
@ilopmar please update with the module / dependency updates

**Comment by graemerocher** [comment]
@ilopmar when you are done with the module updates please update the "Module Upgrades" and "Dependency Upgrades" section https://github.com/micronaut-projects/micronaut-core/blob/update-whats-new/src/main/docs/guide/introduction/whatsNew.adoc

**Comment by ilopmar** [comment]
Yes, I'm on it. I'll update what has been releases so far and update it again probably tomorrow.

**Comment by ilopmar** [comment]
First version of modules and dependencies upgrades. Will update it tomorrow with new versions released today.

**Comment by graemerocher** [comment]
I'm going to merge this for now because it includes the Graal upgrade which we need to test

**Comment by ilopmar** [comment]
Sure, I'll open a new PR with the latest upgrades.

**Pull request merged**
