### PR TITLE
simplified return statement on a doc snippet

### PR DESCRIPTION
**Pull request by St3S0f**
while reading the docs, I noticed the return statement could be simplified to just returning the declared variable.

### CODE REVIEW

**Comment by graemerocher** [comment]
Could you sign the CLA? The test failures are unrelated so don't worry about that. Thanks

**Comment by St3S0f** [comment]
already did, but just realized I need to set email too in my commits to be able to be properly linked as github user. I will make sure I do it correctly on the next one. For now I committed a dummy change and removed it on next commit.  First PR ever here, getting the hang of it.

**Comment by St3S0f** [comment]
now it's recognizing my initial commit as different user and not ticking the CLA... shall I maybe open a new PR? sorry for the mess

**Comment by graemerocher** [comment]
no worries, seems like you did the commits with a different account to the one with which you submitted the PR?

**Comment by St3S0f** [comment]
same account, but my IDE settings had no email set for the git commit, that made github "fail" to recognize the user as my github account (user icon stayed gray). I closed the PR and opened a new one. Thanks for the patience

**Pull request closed without merging**
