### PR TITLE
Update HelloClientSpec.java

### PR DESCRIPTION
**Pull request by stevez**
added the Junit Test tag

### CODE REVIEW

**Comment by ilopmar** [comment]
@stevez Travis is failing because of missing import.

**Comment by stevez** [comment]
Just added the junit import

**Comment by jameskleeh** [comment]
@stevez Please sign the CLA

**Comment by stevez** [comment]
@jameskleeh, the build passed the tests because the tests was disabled before, and when I enabled it by adding @Test annotation, the test failed, and the error message was:
"io.micronaut.docs.server.intro.HelloClientSpec > testHelloWorldResponse() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException: Page Not Found"

But so far I don't know how to resolve it. 

@graemerocher, could provide some insight?

**Comment by stevez** [comment]
@jameskleeh, thank you fixing the failing test. When could you accept my pull request?

**Pull request merged**
