### PR TITLE
Modifies CompletableFutureContinuation to implement kotlin debug clas…

### PR DESCRIPTION
**Pull request by willbuck**
…s CoroutineStackFrame (#4438)

### CODE REVIEW

**Comment by willbuck** [comment]
Closes #4438

**Comment by graemerocher** [comment]
This is an internal class?

**Comment by graemerocher** [comment]
Nevermind read the comments on the linked issue

**Comment by willbuck** [comment]
Yeah James and I also thought at first this wasn't the way to go, but @qwwdfsad has informed us despite being in a package labeled internal, it is a public facing interface meant to be implemented:

https://github.com/Kotlin/kotlinx.coroutines/issues/2386

**Comment by timducheyne** [comment]
Hi @graemerocher,

 I see you fixed it in CompletableFutureContinuation 

but there is also another location that will need the same fix:
io.micronaut.http.bind.binders.ContinuationArgumentBinder#CustomContinuation

kind regards,
Tim

**Comment by willbuck** [comment]
@timducheyne Appreciate the heads up! If you feel comfortable PRing that (or any other Continuation related classes we have)  please feel free to submit them, otherwise I will try to get to it eventually

Thanks!

**Comment by timducheyne** [comment]
@willbuck I added a fix for this in the PR for the request scope fix 
https://github.com/micronaut-projects/micronaut-core/pull/4661

grtz,
Tim

**Pull request merged**
