### PR TITLE
build: bump up slf4j to 2.0.4 and logback to 1.4.4

### PR DESCRIPTION
**Pull request by graemerocher**

### CODE REVIEW

**Review by melix — APPROVED** [review]
I guess we'll need to double check what it means for native builds, as we need config for both logback and slf4j.

**Comment by graemerocher** [comment]
@timyates has the smoke test for GraalVM been merged into 4.0.x?

**Comment by timyates** [comment]
> @timyates has the smoke test for GraalVM been merged into 4.0.x?

It's still languishing on 3.8.x, we should merge up... ~~Should I do it via a PR?~~ Jonas is looking in to the conflicts 🤩

**Comment by timyates** [comment]
`test-suite-graal` will be on 4.0.x once https://github.com/micronaut-projects/micronaut-core/pull/8363 passes and is accepted

**Pull request merged**
