### PR TITLE
Preserves original HTTP method while following permanent redirection

### PR DESCRIPTION
**Pull request by loicgreffier**
Attempt to address #9275

### CODE REVIEW

**Comment by yawkat** [comment]
reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections , i think it should be changed so that only 303 forces GET

**Comment by loicgreffier** [comment]
Well as specified, for `301` and `302`, the other HTTP methods "**may or may not be changed to GET**".

I believe preserving redirections with `GET` for HTTP codes different from 307 and 308 is justified and will avoid some breaking changes.

**Comment by yawkat** [comment]
yes, and I think we should only use GET for 303. but either way is acceptable.

**Comment by loicgreffier** [comment]
@yawkat CI is failing due to:

```
http-client/src/test/groovy/io/micronaut/http/client/StreamRequestSpec.groovy | Expected exception of type 'java.lang.RuntimeException', but no exception was thrown
```

Not sure it is related to this PR, can you confirm ?

**Comment by yawkat** [comment]
it's unrelated

**Review by yawkat — APPROVED** [review]

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
