### PR TITLE
Instrumentation Refactor WIP

### PR DESCRIPTION
**Pull request by graemerocher**

### CODE REVIEW

**Comment by graemerocher** [comment]
@dstepanov I created this to make modifications to the PR. I have cleaned up the use of optional and the continued recreation of the `RxInstrumenter` which seemed unnecessary for the new approach: https://github.com/micronaut-projects/micronaut-core/pull/2397/commits/672a30a2476754614d58c96b6edde9c852a1c80a

I also deprecated `ReactiveInstrumenter` since there are no implementations anymore. I am not sure of another way to not make the `set` method public. That seems required with this new approach.

Like you see to further reduce the call stack we would need to get rid of some of the `Publisher` implementations like `ServerRequestTracingPublisher` and so on.

**Comment by dstepanov** [comment]
@graemerocher Looks good, the best solution would be to return the server context implementation of `InvocationInstrumenter` from `ServerRequestContext` and refactor `ServerRequestTracingPublisher` and `Publisher`s with it, but the interface is not in imported dependencies.

**Comment by dstepanov** [comment]
@graemerocher Check out https://github.com/reactiverse/reactive-contexts this looks much better for RxJava2 instrumentation

**Comment by graemerocher** [comment]
Indeed that does look good

**Pull request closed without merging**
