### PR TITLE
build: graal to 22.1.0

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Review by alvarosanchez — COMMENTED** [review]
You also need to upgrade version in gradle.properties

**Comment by alvarosanchez** [comment]
This is failing due to https://github.com/oracle/graal/issues/4518

**Comment by sdelamo** [comment]
> This is failing due to [oracle/graal#4518](https://github.com/oracle/graal/issues/4518)

[I have rolled back GraalVM svm to 22.0.0.2](https://github.com/micronaut-projects/micronaut-core/pull/7478/commits/7d9a9764590352422105356bbcc6825d7949a3b3)

**Comment by alvarosanchez** [comment]
@sdelamo GraalVM team suggests as you did: keeping the `svm` dependency at 22.0.x. Should be OK since it's a `compileOnly` dependency.

However, we still must generate a `<graal.version>22.1.0</graal.version>` property in the BOM. Will your latest commit make that happen?

**Comment by sdelamo** [comment]
I think it is correct.

```
rm -rf build/repo && ./gradlew pAPTBR  
% cat build/repo/io/micronaut/micronaut-bom/3.5.0-SNAPSHOT/micronaut-bom-3.5.0-20220523.083414-1.pom | grep graal
    <graalSdk.version>22.1.0.1</graalSdk.version>
    <graal.svm.version>22.0.0.2</graal.svm.version>
    <graal.version>22.1.0</graal.version>
        <groupId>org.graalvm.nativeimage</groupId>
        <version>${graal.svm.version}</version>
        <groupId>org.graalvm.sdk</groupId>
        <artifactId>graal-sdk</artifactId>
        <version>${graalSdk.version}</version>
        <artifactId>micronaut-graal</artifactId>
```

**Review by alvarosanchez — APPROVED** [review]

**Review by melix — APPROVED** [review]

**Pull request merged**
