### PR TITLE
Add support for Oracle Cloud hosting environment

### PR DESCRIPTION
**Pull request by recursivecodes**
Previous PR [1540](https://github.com/micronaut-projects/micronaut-core/pull/1540) cancelled to add support for virtual network metadata.

This PR adds support for Environment.ORACLE_CLOUD to provide compute instance metadata for Micronaut applications hosted on Oracle Cloud Infrastructure.

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks for the PR, we are considering it. Do you know if there is anyway to detect an Oracle compute instance without making the network call?

**Comment by recursivecodes** [comment]
@graemerocher I'll look into it - I'm sure there's a way. I have an appointment this morning and a JUG presentation this evening so it might take me a day or so.

**Comment by recursivecodes** [comment]
The network call is only hitting the local cloud-init server.  I suppose I could change to read the cloud-init JSON files and check that way, but would the File IO operation be more expensive than a network call to a locally running server?  I'd also have to detect Windows and handle that case differently (we use cloudbase-init for Windows instances and I'm not terribly familiar with where it stores the JSON files).  If you think this approach is better let me know and I'll dig into it.

**Comment by recursivecodes** [comment]
I'm going to take an approach similar to how EC2 is detected - will work on this today.

**Comment by recursivecodes** [comment]
@graemerocher OK, refactored to remove network calls.  Let me know if you have any other suggestions.

**Comment by graemerocher** [comment]
Thanks we will make sure to include this in 1.2

**Comment by recursivecodes** [comment]
Made a [change](https://github.com/micronaut-projects/micronaut-core/pull/1543/commits/c5393bf778874897e26214efae8baa911337d6c3) to ensure the check works on both native and k8s - build seems to be failing for unrelated checkstyle violations related to files I did not touch.

**Comment by graemerocher** [comment]
Merging as is for now, we need to undertake a general review of how to make this mechanism more extensible but that is beyond the scope of this PR.

Thanks for the contribution!

**Pull request merged**
