### PR TITLE
Updated Micronaut-GraphQL version and added GraphQL-Java extended sca…

### PR DESCRIPTION
**Pull request by marceloverdijk**
…lars dependency version

### CODE REVIEW

**Comment by jameskleeh** [comment]
Why should this library be part of the BOM?

**Comment by marceloverdijk** [comment]
I thought it could be useful for users who want to include the `graphql-java-extended-scalars` dependency and that this was common, but maybe not.
I can remove it?

**Comment by graemerocher** [comment]
Yeah you can remove it

**Comment by marceloverdijk** [comment]
I will create another PR.

**Pull request closed without merging**
